objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Logo__c</fullName>
        <label>Logo</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Tags__c</fullName>
        <description>Full List of CB Tags: https://docs.google.com/spreadsheets/d/1erIdqoy60JwLAnpb91EfoJV5YrXDnbwSaA-aqcBlw48/edit#gid=1111933207</description>
        <label>Tags</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Raised__c</fullName>
        <label>Raised</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Sector__c</fullName>
        <description>Full List: https://docs.google.com/spreadsheets/d/1erIdqoy60JwLAnpb91EfoJV5YrXDnbwSaA-aqcBlw48/edit#gid=1561611259</description>
        <label>Sector</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Facebook__c</fullName>
        <label>Facebook</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Industry__c</fullName>
        <description>Full List: https://docs.google.com/spreadsheets/d/1erIdqoy60JwLAnpb91EfoJV5YrXDnbwSaA-aqcBlw48/edit#gid=1561611259</description>
        <label>Industry*</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LinkedIn__c</fullName>
        <label>LinkedIn</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Time_Zone__c</fullName>
        <label>Time Zone</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Legal_Name__c</fullName>
        <label>Legal Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State_Code__c</fullName>
        <label>State Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <label>Postal Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country_Code__c</fullName>
        <label>Country Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Founded_Year__c</fullName>
        <label>Founded Year</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sub_industry__c</fullName>
        <description>Full List: https://docs.google.com/spreadsheets/d/1erIdqoy60JwLAnpb91EfoJV5YrXDnbwSaA-aqcBlw48/edit#gid=1561611259</description>
        <label>Sub-industry</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Technologies__c</fullName>
        <label>Technologies</label>
        <length>45000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Phone_Numbers__c</fullName>
        <label>Phone Numbers</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Street_Number__c</fullName>
        <label>Street Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Domain_Aliases__c</fullName>
        <label>Domain Aliases</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Industry_Group__c</fullName>
        <label>Industry Group</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Email_Addresses__c</fullName>
        <label>Email Addresses</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Employees_Range__c</fullName>
        <label>Employees Range_Delete</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fiscal_Year_Ends__c</fullName>
        <label>Fiscal Year Ends</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company_Description__c</fullName>
        <label>Company Description</label>
        <length>100000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Parent_Company_Website__c</fullName>
        <label>Parent Company Website</label>
        <type>Url</type>
    </fields>
</CustomObject>

objects/cbit__Clearbit__c.object
<CustomObject>
</CustomObject>

objects/Contact.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LinkedIn__c</fullName>
        <label>LinkedIn</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <description>The most accurate location we have (City, State, Country)</description>
        <inlineHelpText>The most accurate location we have (City, State, Country)</inlineHelpText>
        <label>Location</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Time_Zone__c</fullName>
        <label>Time Zone</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State_Code__c</fullName>
        <label>State Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country_Code__c</fullName>
        <label>Country Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SystemAccScriptUpdated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>SystemAccScriptUpdated</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunity</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account_Name__c</fullName>
        <formula>Account.Name</formula>
        <label>Account Name</label>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Industry__c</fullName>
        <formula>Account_Name__r.ZI_Industry__c</formula>
        <label>Industry</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Initial Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account_Name__c</fullName>
        <description>Lookup to Account</description>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Master_User_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master User Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Project_User__c.object
<CustomObject>
    <label>Project User</label>
    <nameField>
        <label>Project User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Project Users</relationshipLabel>
        <relationshipName>Project_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Project Users</relationshipLabel>
        <relationshipName>Project_Users</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Master_User__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Master User</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SystemAccScriptUpdated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>SystemAccScriptUpdated</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

classes/UpdateSystemAccountWithClearbit_SERV.cls
public class UpdateSystemAccountWithClearbit_SERV {

	/*
	 *	----------------- PHASE 1 SERVICE METHODS --------------------------------------------
	 */

	public static Integer updateAccountOnMasterContactsAndProjects(List<Contact> contactsToUpdate, List<Project__c> projectsToUpdate, Integer insertedAccounts, String eachEmail, Integer contactLimit) {
		// load all records		
		Id systemAccountId = Account_DAO.getSystemAccount().Id;
		List<Contact> masterContacts = Contact_DAO.getAllMasterContactsWithClearbitRecordSystemAcc(systemAccountId, contactLimit);
		Integer size = masterContacts.size();
		List<Id> clearbitIds = new List<Id> ();
		List<Id> masterContactsIds = new List<Id> ();
		for (Contact c : masterContacts) {
			masterContactsIds.add(c.Id);
			clearbitIds.add(c.cbit__Clearbit__c);
		}
		List<Project__c> projects = Project_DAO.getProjectsByListOfMasterContactIds(masterContactsIds);
		List<cbit__Clearbit__c> clearbitRecords = Clearbit_DAO.getClearbitRecordsByListOfIds(clearbitIds);
		List<Account> salesforceAccounts = Account_DAO.getAllAccounts();

		List<Contact> masterContactsWithClearbitCompany = getContactsWithClearbitCompany(masterContacts, clearbitRecords);
		size = masterContactsWithClearbitCompany.size();

		Integer tempCOunt = 0;
		for (Contact con : masterContactsWithClearbitCompany) {
			// get account ID to update
			if (tempCOunt <= 49) {
				eachEmail = con.Email;
				Id accountIdToUpdate;
				List<Project__c> masterContactProjects = getProjects(con.Id, projects);
				cbit__Clearbit__c cbit = getClearbitRecord(con.cbit__Clearbit__c, clearbitRecords);
				if (!masterContactProjects.isEmpty()) {
					if (cbit.cbit__CompanyName__c != null) {
						for (Account a : salesforceAccounts) {
							if (a.Name.toUpperCase().equals(cbit.cbit__CompanyName__c.toUpperCase())) {
								accountIdToUpdate = a.Id;
							}
						}
						if (accountIdToUpdate == null) {
							Account insertedAcc = createNewAccount(cbit);
							accountIdToUpdate = insertedAcc.Id;
							salesforceAccounts.add(insertedAcc);
							tempCOunt++;
							insertedAccounts++;
						}
					}

					// add contact and its projects to update queue
					con.AccountId = accountIdToUpdate;
					con.SystemAccScriptUpdated__c = true;
					contactsToUpdate.add(con);
					for (Project__c pr : masterContactProjects) {
						pr.Account_Name__c = accountIdToUpdate;
						projectsToUpdate.add(pr);
					}
				} else {
					con.SystemAccScriptUpdated__c = true;
					contactsToUpdate.add(con);
				}
			} else {
				break;
			}
		}
		return insertedAccounts;
	}

	public static void setSuccessResultPhase1(Map<String, String> result, List<Contact> contactsToUpdate, List<Project__c> projectsToUpdate, Integer insertedAccounts) {
		result.put('Contacts updated', String.valueOf(contactsToUpdate.size()));
		result.put('Projects updated', String.valueOf(projectsToUpdate.size()));
		result.put('Accounts inserted', String.valueOf(insertedAccounts));
		result.put('Success result', 'Update on contacts and projects was successfullly proceeded!');
	}

	public static void setSuccessResultPhase2(Map<String, String> result, List<Contact> contactsToUpdate, List<Opportunity> oppsToUpdate) {
		result.put('Pu contacts updated', String.valueOf(contactsToUpdate.size()));
		result.put('Opps updated', String.valueOf(oppsToUpdate.size()));
		result.put('Success result', 'Update on pu contacts and projects ops was successfullly proceeded!');
	}

	public static void setErrorResultPhase1(Map<String, String> result, Exception e, String eachEmail) {
		result.put('Cause', String.valueOf(e.getCause()));
		result.put('Line Number', String.valueOf(e.getLineNumber()));
		result.put('Exception Type Name', e.getTypeName());
		result.put('Contact Email', eachEmail);
		result.put('Update failed', e.getMessage());
	}

	public static void setErrorResultPhase2(Map<String, String> result, Exception e) {
		result.put('Cause', String.valueOf(e.getCause()));
		result.put('Line Number', String.valueOf(e.getLineNumber()));
		result.put('Exception Type Name', e.getTypeName());
		result.put('Update failed', e.getMessage());
	}

	public static List<Project__c> getProjects(Id contactId, List<Project__c> projects) {
		List<Project__c> contactProjects = new List<Project__c> ();
		for (Project__c pr : projects) {
			if (pr.Master_User_Contact__c.equals(contactId)) {
				contactProjects.add(pr);
			}
		}
		return contactProjects;
	}

	public static cbit__Clearbit__c getClearbitRecord(Id cbitId, List<cbit__Clearbit__c> clearbits) {
		cbit__Clearbit__c clearbitRecord;
		for (cbit__Clearbit__c cb : clearbits) {
			if (cb.Id.equals(cbitId)) {
				clearbitRecord = cb;
			}
		}
		return clearbitRecord;
	}

	public static List<Contact> getContactsWithClearbitCompany(List<Contact> contactsWithClearbit, List<cbit__Clearbit__c> clearbits) {
		List<Contact> markContactAsUpdated = new List<Contact> ();
		for (Integer i = 0; i<contactsWithClearbit.size(); i++) {
			Contact con = contactsWithClearbit.get(i);
			cbit__Clearbit__c cb = getClearbitRecord(con.cbit__Clearbit__c, clearbits);
			if (cb.cbit__CompanyName__c == null) {
				con.SystemAccScriptUpdated__c = true;
				markContactAsUpdated.add(con);
				contactsWithClearbit.remove(i);
			}
		}
		update markContactAsUpdated;
		return contactsWithClearbit;
	}

	public static Account createNewAccount(cbit__Clearbit__c cbit) {
		Account acc = new Account();
		acc.Name = cbit.cbit__CompanyName__c;
		acc.Parent_Company_Website__c = cbit.cbit__CompanyParentDomain__c;
		acc.Company_Description__c = cbit.cbit__CompanyDescription__c;
		acc.Location__c = cbit.cbit__CompanyLocation__c;
		acc.Phone_Numbers__c = cbit.cbit__CompanySitePhoneNumbers__c;
		acc.Email_Addresses__c = cbit.cbit__CompanySiteEmailAddresses__c;
		acc.Time_Zone__c = String.valueOf(cbit.cbit__UtcOffset__c);
		acc.Website = cbit.cbit__CompanyDomain__c;
		acc.NumberOfEmployees = Integer.valueOf(cbit.cbit__CompanyMetricsEmployees__c);
		acc.Sector__c = cbit.cbit__CompanyCategorySector__c;
		acc.Industry__c = cbit.cbit__CompanyCategoryIndustry__c;
		acc.Industry_Group__c = cbit.cbit__CompanyCategoryIndustryGroup__c;
		acc.Sub_industry__c = cbit.cbit__CompanyCategorySubIndustry__c;
		acc.Street__c = cbit.cbit__CompanyGeoStreetName__c;
		acc.Street_Number__c = cbit.cbit__CompanyGeoStreetNumber__c;
		acc.City__c = cbit.cbit__CompanyGeoCity__c;
		acc.Postal_Code__c = cbit.cbit__CompanyGeoPostalCode__c;
		acc.Country__c = cbit.cbit__CompanyGeoCountry__c;
		acc.Country_Code__c = cbit.cbit__CompanyGeoCountryCode__c;
		acc.State__c = cbit.cbit__CompanyGeoState__c;
		acc.State_Code__c = cbit.cbit__CompanyGeoStateCode__c;
		acc.ShippingStreet = cbit.cbit__CompanyGeoStreetName__c + ' ' + cbit.cbit__CompanyGeoStreetNumber__c;
		acc.ShippingCity = cbit.cbit__CompanyGeoCity__c;
		acc.ShippingCountry = cbit.cbit__CompanyGeoCountry__c;
		acc.ShippingState = cbit.cbit__CompanyGeoState__c;
		acc.ShippingPostalCode = cbit.cbit__CompanyGeoPostalCode__c;
		acc.Legal_Name__c = cbit.cbit__CompanyLegalName__c;
		acc.Domain_Aliases__c = cbit.cbit__CompanyDomainAliases__c;
		acc.Tags__c = cbit.cbit__CompanyTags__c;
		acc.Technologies__c = cbit.cbit__CompanyTech__c;
		acc.Founded_Year__c = cbit.cbit__CompanyFoundedYear__c;
		acc.Phone__c = cbit.cbit__CompanyPhone__c;
		acc.Logo__c = cbit.cbit__CompanyLogo__c;
		acc.Raised__c = cbit.cbit__CompanyMetricsRaised__c;
		acc.Fiscal_Year_Ends__c = String.valueOf(cbit.cbit__CompanyMetricsFiscalYearEnd__c);
		acc.Employees_Range__c = cbit.cbit__CompanyMetricsEmployeesRange__c;
		acc.Facebook__c = 'www.facebook.com/' + cbit.cbit__CompanyFacebookHandle__c;
		acc.LinkedIn__c = 'www.linkedin.com/' + cbit.cbit__CompanyLinkedinHandle__c;
		insert acc;
		return acc;
	}

	/*
	 *	----------------- PHASE 2 SERVICE METHODS --------------------------------------------
	 */

	public static void updateAccOnPuContactsAndProjectOpps(List<Contact> puContactsToUpdate, List<Opportunity> oppsToUpdate, Integer pusLimit) {
		Id systemAccId = Account_DAO.getSystemAccount().Id;

		// get pu contacts no masters
		List<Project_User__c> projectUsers = ProjectUser_DAO.getProjectUsersWithLimit(pusLimit);
		List<Id> puContactsIds = new List<Id> ();
		for (Project_User__c pu : projectUsers) {
			puContactsIds.add(pu.Contact__c);
		}
		List<Contact> puContacts = Contact_DAO.getContactbyListOfIds(puContactsIds);

		// get project opportunities
		List<Project__c> projects = getPusProjects(projectUsers);

		List<Id> projectsIds = new List<Id> ();
		List<Id> projectOppsIds = new List<Id> ();
		Set<Id> projectOppsIdsNoDupl = new Set<Id> ();

	/*//projopp 	for (Project__c pr : projects) {
			if (pr.Opportunity__c != null) {
				projectOppsIds.add(pr.Opportunity__c);
				projectsIds.add(pr.Id);
			}
		}
        */

		List<Opportunity> projectOpps = Opportunity_DAO.getOppsByListOfIds(projectOppsIds);
		Integer size = projectOpps.size();

		List<Project_User__c> setPusAsUpdated = new List<Project_User__c> ();
		// set pu contacts for update
		for (Project_User__c pu : projectUsers) {
			pu.SystemAccScriptUpdated__c = true;
			setPusAsUpdated.add(pu);
			if (!pu.Master_User__c) {
				Project__c puProject = getPuProject(pu.Project__c, projects);
				Id accountIdToUpdate = puProject.Account_Name__c;
				if (accountIdToUpdate != null) {
					if (!accountIdToUpdate.equals(systemAccId)) {
						Contact puContact = getPuContact(pu.Contact__c, puContacts);
						if (!puContact.AccountId.equals(accountIdToUpdate)) {
							puContact.AccountId = accountIdToUpdate;
							puContactsToUpdate.add(puContact);
						}
					}
				}
			}
		}

		// set opps for update
	/*//projopp 	for (Project__c pr : projects) {
			Id accountIdToUpdate = pr.Account_Name__c;
			Opportunity prOpp = getProjectOpp(pr.Opportunity__c, projectOpps);
			if (prOpp != null) {
				if (!prOpp.AccountId.equals(accountIdToUpdate) && accountIdToUpdate != null) {
					prOpp.AccountId = accountIdToUpdate;
					projectOppsIdsNoDupl.add(prOpp.Id);
				}
			}
		}

		// set opps for update to list
		for(Id oppId : projectOppsIdsNoDupl) {
			oppsToUpdate.add(getProjectOpp(oppId,projectOpps));
		}
        */
		//oppsToUpdate = Opportunity_DAO.getOppsBySetOfIds(projectOppsIdsNoDupl);
		//size = oppsToUpdate.size();
		//size = 0;
		update setPusAsUpdated;
	}

	public static Project__c getPuProject(Id projectId, List<Project__c> projects) {
		Project__c project;
		for (Project__c pr : projects) {
			if (projectId.equals(pr.Id)) {
				project = pr;
			}
		}
		if (project == null) {
			throw new ProductboardException('Project was not found for the project user.', 1);
		}
		return project;
	}

	public static Contact getPuContact(Id conId, List<Contact> contacts) {
		Contact con;
		for (Contact c : contacts) {
			if (conId.equals(c.Id)) {
				con = c;
			}
		}
		if (con == null) {
			throw new ProductboardException('Contact was not found for the project user.', 1);
		}
		return con;
	}

	public static Opportunity getProjectOpp(Id oppId, List<Opportunity> opps) {
		Opportunity prOpp;
		for (Opportunity opp : opps) {
			if (opp != null) {
				if (oppId != null) {
					if (oppId.equals(opp.Id)) {
						prOpp = opp;
					}
				}
			}


			//throw new ProductboardException('Opp was not found for the project .', 1);
		}
		return prOpp;
	}

	public static List<Project__c> getPusProjects(List<Project_User__c> projectUsersExceptMasters) {
		Set<Id> puProjectsIds = new Set<Id> ();
		List<Id> puProjectIdsInList = new List<Id> ();
		List<Project__c> puProjects = new List<Project__c> ();
		for (Project_User__c pu : projectUsersExceptMasters) {
			puProjectsIds.add(pu.Project__c);
		}
		for (Id prId : puProjectsIds) {
			puProjectIdsInList.add(prId);
		}
		puProjects = Project_DAO.getProjectsByListOfIds(puProjectIdsInList);
		return puProjects;
	}

}