objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Number__c</fullName>
        <label>Street Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Asset.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Period__c</fullName>
        <label>Period</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BI_City__c</fullName>
        <label>BI City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CC_City__c</fullName>
        <label>CC City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BI_State__c</fullName>
        <label>BI State</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CC_State__c</fullName>
        <label>CC State</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cancelled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Cancelled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BI_Address__c</fullName>
        <label>BI Address</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BI_Country__c</fullName>
        <label>BI Country</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CC_Address__c</fullName>
        <label>CC Address</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CC_Country__c</fullName>
        <label>CC Country</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Discount_Type__c</fullName>
        <label>Discount Type</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BI_Postal_Code__c</fullName>
        <label>BI Postal Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CC_Postal_Code__c</fullName>
        <label>CC Postal Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Discount_Fixed__c</fullName>
        <label>Discount Fixed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BI_Company_Name__c</fullName>
        <label>BI Company Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Discount_Credit__c</fullName>
        <label>Discount Credit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CC_Billing_Email__c</fullName>
        <label>CC Billing Email</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Discount_Percent__c</fullName>
        <label>Discount Percent</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Discount_Subtype__c</fullName>
        <label>Discount Subtype</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Remaining_Credit__c</fullName>
        <label>Remaining Credit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Discount_Length_ms__c</fullName>
        <label>Discount Length ms</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Price_Without_Discount__c</fullName>
        <label>Price Without Discount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Discount_Fixed_Rest_Below_Zero__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Discount Fixed Rest Below Zero</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

objects/Contact.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isTrial__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isTrial</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>hasSubscription__c</fullName>
        <defaultValue>false</defaultValue>
        <label>hasSubscription</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

objects/IntegrationLog__c.object
<CustomObject>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>IL-{YY}-{MM}-{DD}-{00000}</displayFormat>
        <label>Integration Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunity</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subtype__c</fullName>
        <description>Identifying opportunities for user and system</description>
        <label>Subtype</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>User</fullName>
                    <default>true</default>
                    <label>User</label>
                </value>
                <value>
                    <fullName>System</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Price_Book__c</fullName>
        <formula>Pricebook2.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Price Book</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stripe_Invoice_ID__c</fullName>
        <externalId>true</externalId>
        <label>Stripe Invoice ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscription_End_Date__c</fullName>
        <formula>Project__r.ETL_Subscription_End__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Subscription End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Subscription_Start_Date__c</fullName>
        <formula>Project__r.ETL_Subscription_Start__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Subscription Start Date</label>
        <type>Date</type>
    </fields>
    <recordTypes>
        <fullName>Self_Service</fullName>
        <active>true</active>
        <businessProcess>Self Service</businessProcess>
        <description>Non Sales Opportunities</description>
        <label>Self Service</label>
    </recordTypes>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Period__c</fullName>
        <label>Period</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Discount_Type__c</fullName>
        <label>Discount Type</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Discount_Fixed__c</fullName>
        <label>Discount Fixed</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>List_Price_TMP__c</fullName>
        <label>List Price TMP</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Discount_Credit__c</fullName>
        <label>Discount Credit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Discount_Percent__c</fullName>
        <label>Discount Percent</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Discount_Subtype__c</fullName>
        <label>Discount Subtype</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Remaining_Credit__c</fullName>
        <label>Remaining Credit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Discount_Length_ms__c</fullName>
        <label>Discount Length ms</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Price_Without_Discount__c</fullName>
        <label>Price Without Discount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Discount_Fixed_Rest_Below_Zero__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Discount Fixed Rest Below Zero</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
</CustomObject>

objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active_Delete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BI_City__c</fullName>
        <label>BI City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CC_City__c</fullName>
        <label>CC City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BI_State__c</fullName>
        <label>BI State</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CC_State__c</fullName>
        <label>CC State</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date_Delete</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Cancelled__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>not correct? Checked for paying active subscriptions</inlineHelpText>
        <label>Cancelled_Delete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BI_Address__c</fullName>
        <label>BI Address</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BI_Country__c</fullName>
        <label>BI Country</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CC_Address__c</fullName>
        <label>CC Address</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CC_Country__c</fullName>
        <label>CC Country</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price_Book__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Cycle</label>
        <referenceTo>Pricebook2</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Product</description>
        <label>Plan</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BI_Postal_Code__c</fullName>
        <label>BI Postal Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CC_Postal_Code__c</fullName>
        <label>CC Postal Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BI_Company_Name__c</fullName>
        <label>BI Company Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CC_Billing_Email__c</fullName>
        <label>CC Billing Email</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscription_End_Date__c</fullName>
        <label>Subscription End Date_Delete</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Subscription_Start_Date__c</fullName>
        <label>Subscription Start Date_Delete</label>
        <type>DateTime</type>
    </fields>
</CustomObject>

objects/Project_User__c.object
<CustomObject>
    <label>Project User</label>
    <nameField>
        <label>Project User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Project Users</relationshipLabel>
        <relationshipName>Project_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Project Users</relationshipLabel>
        <relationshipName>Project_Users</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Cancelled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Cancelled</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

classes/SubscriptionOps_SERV.cls
public class SubscriptionOps_SERV {

	public static void setHasSubscriptionOnUsers(Project__c pr, Boolean newHasSubscriptionValue) {
		List<Id> conIds = new List<Id> ();
		for (Project_User__c pu : ProjectUser_DAO.getProjectUsersByProjectId2(pr.Id)) {
			conIds.add(pu.Contact__c);
		}
		List<Contact> cons = Contact_DAO.getContactbyListOfIds(conIds);
		for (Contact c : cons) {
			c.hasSubscription__c = newHasSubscriptionValue;
			c.isTrial__c = newHasSubscriptionValue;
		}
		update cons;
	}

	public static void setHasSubscriptionOnUsers(List<Project_User__c> pus, Boolean newHasSubscriptionValue) {
		List<Id> conIds = new List<Id> ();

		for (Project_User__c pu : pus) {
			conIds.add(pu.Contact__c);
		}
		List<Contact> cons = Contact_DAO.getContactbyListOfIds(conIds);
		for (Contact c : cons) {
			c.hasSubscription__c = newHasSubscriptionValue;
			c.isTrial__c = newHasSubscriptionValue;
		}
		update cons;
	}

	//*****************************************************************************************************************************************************************
	//DISCOUNTED TOTAL PRICCE 
	//*****************************************************************************************************************************************************************     

	// counts total price on line item (with discount), fills discount fields on opp line item    
	public static OpportunityLineItem countDiscountedTotalPrice(OpportunityLineItem lineItem,
	                                                            Decimal discountValue, String discountType, String subtype, Integer discountLength, Datetime now/* MT_pricebookChange 19-09-03: , Integer periodCon*/)
	{
		Double remainingCredit;
		Double discountedTotalPrice = lineItem.Price_Without_Discount__c;
		Double priceWithoutDiscount = lineItem.Price_Without_Discount__c;
		Double amountOfUsers = lineItem.Quantity;
		lineItem.Discount_Fixed_Rest_Below_Zero__c = 0;
		if (discountType != null /* MM ZERO NUMBER OF USERS || lineItem.Quantity != 0*/) {

			lineItem.Discount_Subtype__c = subtype;

			// credit type
			if (discountType.equals('credit')) {
				lineItem.Discount_Credit__c = discountValue;
				lineItem.Discount_Type__c = discountType;
				// remainingCredit = priceWithoutDiscount - discountValue; // záporný, 0, nebo kladný
				if (discountValue > priceWithoutDiscount) {
					discountedTotalPrice = 0;
					remainingCredit = discountValue - priceWithoutDiscount;
				} else {
					discountedTotalPrice = priceWithoutDiscount - discountValue;
					remainingCredit = 0;
				}

			}
			// fix type
			if (discountType.equals('amount_off')) {
				lineItem.Discount_Fixed__c = discountValue;
				lineItem.Remaining_Credit__c = 0;
				lineItem.Discount_Type__c = discountType;


				Datetime discountEndDate = now.addMonths(discountLength);
				lineItem.Discount_Length_ms__c = discountEndDate.getTime() - now.getTime();
				//MitchiWork.MitchiEditInSubscriptionOpsIncountDiscountedTotalPriceFix

				if (subtype.equals('forever') && discountLength == 0) {
					discountedTotalPrice = (lineItem.List_Price_TMP__c * lineItem.Quantity /* MT_pricebookChange 19-09-03: * periodCon*/) - discountValue;
					if (discountedTotalPrice< 0) {
						lineItem.Discount_Fixed_Rest_Below_Zero__c = Math.abs(discountedTotalPrice);
						discountedTotalPrice = 0;
					}
				}

				if (subtype.equals('multi-month')) {
					discountEndDate = now.addMonths(discountLength);
					lineItem.Discount_Length_ms__c = discountEndDate.getTime() - now.getTime();

					discountedTotalPrice = (lineItem.List_Price_TMP__c * lineItem.Quantity /* MT_pricebookChange 19-09-03: * periodCon*/) - discountValue;
					if (discountedTotalPrice< 0) {
						lineItem.Discount_Fixed_Rest_Below_Zero__c = Math.abs(discountedTotalPrice);
						discountedTotalPrice = 0;
					}
				}

				// END FIX
			}

			// percent type
			if (discountType.equals('percent_off')) {
				lineItem.Discount_Percent__c = discountValue;
				lineItem.Discount_Type__c = discountType;


				Datetime discountEndDate = now.addMonths(discountLength);
				lineItem.Discount_Length_ms__c = discountEndDate.getTime() - now.getTime();
				//MitchiWork.MitchiEditInSubscriptionOpsIncountDiscountedTotalPricePercent

				if (subtype.equals('forever') && discountLength == 0) {
					discountedTotalPrice = (lineItem.List_Price_TMP__c * (1 - (discountValue * 0.01))) * lineItem.Quantity;
				}

				if (subtype.equals('multi-month')) {
					discountEndDate = now.addMonths(discountLength);
					lineItem.Discount_Length_ms__c = discountEndDate.getTime() - now.getTime();

					discountedTotalPrice = (lineItem.List_Price_TMP__c * (1 - (discountValue * 0.01))) * lineItem.Quantity;
				}

			}


		}

		lineItem.TotalPrice = discountedTotalPrice;
		lineItem.Remaining_Credit__c = remainingCredit;
		return lineItem;
	}


	//*****************************************************************************************************************************************************************
	// Find Accounts based on criteria     
	//*****************************************************************************************************************************************************************  
	public static List<Account> findAccountBasedOnCriteria(String companyName) {
		List<Account> existingAccounts = [Select Id, Name, Country__c, Street__c, Street_Number__c, City__c
		                                  from Account
		                                  where Name LIKE :companyName LIMIT 1];
		return existingAccounts;

	}

	//*****************************************************************************************************************************************************************
	// SubscriptionCalc_DTO_Info to Asset Object, Project__c Object
	//*****************************************************************************************************************************************************************

	public static void updateObjectsBasedOnDTO(SubscriptionCalc_DTO_Info calcDto) {
		Project__c updatedProject = calcDto.calcProject;
		Product2 updatedProduct2 = calcDto.calcProduct;
        Pricebook2 updatedPricebook2 = calcDto.calcPriceBook;
		//Asset Object
		if (calcDto.action.equals('DowngradeUpgrade')) {

            updatedProject.Product_Name__c = updatedProduct2.Id;
            updatedProject.Price_Book__c = updatedPricebook2.id;

		} else if (calcDto.action.equals('ChangePeriod') || calcDto.action.equals('ChangePeriod_DowngradeUpgrade')) {
            updatedProject.Product_Name__c = updatedProduct2.Id;
            updatedProject.Subscription_Start_Date__c = calcDto.now;
            if (calcDto.newPeriodType.equals('monthly')) {
                updatedProject.Subscription_End_Date__c = calcDto.now.addMonths(1);
            } else if (calcDto.newPeriodType.equals('yearly')) {
                updatedProject.Subscription_End_Date__c = calcDto.now.addYears(1);
            }
            updatedProject.Price_Book__c = updatedPricebook2.id;

		} else if (calcDto.action.equals('Cancel')) {
			// project cancellation
			updatedProject.Cancelled__c = true;
			updatedProject.Active__c = false;
			updatedProject.End_Date__c = calcDto.now;
            updatedProject.Subscription_End_Date__c = calcDto.now;
			for (Project_User__c projectUser : calcDto.allProjectUsers) {
				ProjectUser_SERV.setValueForProjectUser(projectUser, null, null, null, null, null, calcDto.now, 'Cancelled', false);
			}
			ProjectUser_DAO.updateProjectUserList(calcDto.allProjectUsers);
			updatedProject.Product_Name__c = null;
            updatedProject.Price_Book__c = null;

		}
		Project_DAO.updateProject(updatedProject);


	}

	//*****************************************************************************************************************************************************************
	// handle subs opportunity
	//*****************************************************************************************************************************************************************


	public static Opportunity setSubscriptionOpp(List<Opportunity> oppList, Id projectId, Id accId, String conName, Id planPricebookId, String stripeInvoiceId, IntegrationLog__c il){
		Opportunity opp = new Opportunity();
		if (oppList.isEmpty()) {
			//new opportunity and opportunity line item
			opp.project__c = projectId;
			opp.Name = conName + ', ' + Datetime.now();
			opp.CloseDate = Date.today();
			opp.RecordTypeId = OpportunityRecordTypes.self_service;
			opp.StageName = 'Free Trial';
			opp.Pricebook2Id = planPricebookId;
			opp.AccountId = accId;
			opp.Stripe_Invoice_ID__c = stripeInvoiceId;
			insert opp;
			il.Description__c += '\n- Opportunity inserted. id: ' + opp.Id;
		} else {
			opp = oppList[0];

			List<OpportunityLineItem> oldLineItems = OpportunityLineItem_DAO.getAllOppLineItemsByOppId(opp.Id);
			delete oldLineItems;
			il.Description__c += '\n- LineItems deleted. count: ' + oldLineItems.size();

			opp.project__c = projectId;
			opp.Pricebook2Id = planPricebookId;
			opp.AccountId = accId;
			opp.Stripe_Invoice_ID__c = stripeInvoiceId;   
			update opp;
			il.Description__c += '\n- Opportunity updated. id: ' + opp.Id;
		}

		opp.Subtype__c = 'System';
		opp.StageName = 'Closed Won';
		return opp;
	}

	public static void setValuesForOppLineItem(OpportunityLineItem li, Subscription_DTO_Req info, PricebookEntry pbe, Id oppId, Id productId, String pricebookName, Datetime now){
		Decimal discountValue;
		if (info.discountValue == null) {
			discountValue = 0;
		} else {
			discountValue = Decimal.valueOf(info.discountValue);
		}

		Integer discountLength;
		if (info.discountLength == null) {
			discountLength = 0;
		} else {
			discountLength = Integer.valueOf(info.discountLength);
		}

		li.PricebookEntryId = pbe.Id;
		li.OpportunityId = oppId;
		li.Product2Id = productId;
		li.Quantity = info.amountOfUsers;
		li.Period__c = pricebookName;
		li.List_Price_TMP__c = pbe.UnitPrice;
		li.Price_Without_Discount__c = info.amountOfUsers * pbe.UnitPrice;
		li = SubscriptionOps_SERV.countDiscountedTotalPrice(li, discountValue, info.discountType, info.discountSubtype, discountLength, now);
	}

	public static void setValuesForProject(Project__c project, Subscription_DTO_Req info, Id pricebookId, Id productId, Datetime now){
		project.CC_Address__c = info.ccAddress;
		project.CC_City__c = info.ccCity;
		project.CC_Country__c = info.ccCountry;
		project.CC_Postal_Code__c = info.ccPostalCode;
		project.CC_State__c = info.ccState;
		project.CC_Billing_Email__c = info.ccBillingEmail;

		if (info.billingInfoFlag) {
			project.BI_Company_Name__c = info.biCompanyName;
			project.BI_Address__c = info.biAddress;
			project.BI_City__c = info.biCity;
			project.BI_Postal_Code__c = info.biPostalCode;
			project.BI_State__c = info.biState;
			project.BI_Country__c = info.biCountry;
			project.BI_VAT_Number__c = info.biVATNumber;
			project.BI_Additional_Info__c = info.biAdditionalInfo;
		}

		project.Price_Book__c = pricebookId;
		project.Product_Name__c = productId;
		project.Subscription_Start_Date__c = now;
		if (info.frequency.equals('monthly')) {
			project.Subscription_End_Date__c = now.addMonths(1);
		} else if(info.frequency.equals('yearly')){
			project.Subscription_End_Date__c = now.addYears(1);
		} 
	}
}