objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>VAT__c</fullName>
        <label>VAT</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Logo__c</fullName>
        <label>Logo</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Tags__c</fullName>
        <description>Full List of CB Tags: https://docs.google.com/spreadsheets/d/1erIdqoy60JwLAnpb91EfoJV5YrXDnbwSaA-aqcBlw48/edit#gid=1111933207</description>
        <label>Tags</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Raised__c</fullName>
        <label>Raised</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Sector__c</fullName>
        <description>Full List: https://docs.google.com/spreadsheets/d/1erIdqoy60JwLAnpb91EfoJV5YrXDnbwSaA-aqcBlw48/edit#gid=1561611259</description>
        <label>Sector</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ticker__c</fullName>
        <label>Ticker</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Facebook__c</fullName>
        <label>Facebook</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Industry__c</fullName>
        <description>Full List: https://docs.google.com/spreadsheets/d/1erIdqoy60JwLAnpb91EfoJV5YrXDnbwSaA-aqcBlw48/edit#gid=1561611259</description>
        <label>Industry*</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LinkedIn__c</fullName>
        <label>LinkedIn</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Time_Zone__c</fullName>
        <label>Time Zone</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Indexed_At__c</fullName>
        <label>Indexed At</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Legal_Name__c</fullName>
        <label>Legal Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State_Code__c</fullName>
        <label>State Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UTC_Offset__c</fullName>
        <label>UTC Offset</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <label>Postal Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_premise__c</fullName>
        <label>Sub-premise</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country_Code__c</fullName>
        <label>Country Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Founded_Year__c</fullName>
        <label>Founded Year</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sub_industry__c</fullName>
        <description>Full List: https://docs.google.com/spreadsheets/d/1erIdqoy60JwLAnpb91EfoJV5YrXDnbwSaA-aqcBlw48/edit#gid=1561611259</description>
        <label>Sub-industry</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Technologies__c</fullName>
        <label>Technologies</label>
        <length>45000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Customer_Type__c</fullName>
        <label>Customer Type-Delete</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Self Service</fullName>
                </value>
                <value>
                    <fullName>VIP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phone_Numbers__c</fullName>
        <label>Phone Numbers</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Referenceable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Referenceable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Street_Number__c</fullName>
        <label>Street Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Domain_Aliases__c</fullName>
        <label>Domain Aliases</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Email_Provider__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check if email has a free provider</description>
        <inlineHelpText>Check if email has a free provider</inlineHelpText>
        <label>Email Provider_Delete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Industry_Group__c</fullName>
        <label>Industry Group</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Reference_type__c</fullName>
        <label>Reference Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Reference us to prospects</fullName>
                    <label>Sales Reference</label>
                </value>
                <value>
                    <fullName>Beta Test</fullName>
                </value>
                <value>
                    <fullName>Discovery Interview</fullName>
                </value>
                <value>
                    <fullName>Use the logo</fullName>
                    <label>Logo Use</label>
                </value>
                <value>
                    <fullName>Get testimonial</fullName>
                    <label>Content Collaboration</label>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>Do Not Contact</fullName>
                </value>
                <value>
                    <fullName>Quote</fullName>
                </value>
                <value>
                    <fullName>Slide</fullName>
                </value>
                <value>
                    <fullName>Customer Story</fullName>
                </value>
                <value>
                    <fullName>Event Speaker</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email_Addresses__c</fullName>
        <label>Email Addresses</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Employees_Range__c</fullName>
        <label>Employees Range_Delete</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Success_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Success Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Website_Heading__c</fullName>
        <label>Admin Test Field</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Fiscal_Year_Ends__c</fullName>
        <label>Fiscal Year Ends</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description_Author__c</fullName>
        <label>Description Author</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_External_ID__c</fullName>
        <label>Account External ID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company_Description__c</fullName>
        <label>Company Description</label>
        <length>100000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Customer_Type_Changed__c</fullName>
        <label>Customer Type Changed</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Automatically</fullName>
                    <default>true</default>
                    <label>Automatically</label>
                </value>
                <value>
                    <fullName>Manually</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Parent_Company_Website__c</fullName>
        <label>Parent Company Website</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Additional_Billing_Info__c</fullName>
        <label>Additional Billing Info</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Customer_Life_Cycle_Stage__c</fullName>
        <label>Customer Life Cycle Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Non-Convert</fullName>
                    <default>true</default>
                    <label>0.1 Non-Convert</label>
                </value>
                <value>
                    <fullName>Onboarding</fullName>
                    <label>1.0 Onboarding</label>
                </value>
                <value>
                    <fullName>Adoption</fullName>
                    <label>2.0 Adoption</label>
                </value>
                <value>
                    <fullName>Expansion</fullName>
                    <label>3.0 Expansion</label>
                </value>
                <value>
                    <fullName>Advocacy (successful customer)</fullName>
                    <label>4.0 Advocacy (successful customer)</label>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                    <label>5.0 Renewal</label>
                </value>
                <value>
                    <fullName>Churn</fullName>
                    <label>0.0 Churn</label>
                </value>
                <value>
                    <fullName>-1.0 Competitor</fullName>
                </value>
                <value>
                    <fullName>-1.0 Disqualified</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Customer_Type_VIP_assigned__c</fullName>
        <label>Customer Type VIP assigned</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Legacy_Account_Source_March_2019__c</fullName>
        <label>Legacy Account Source (March 2019)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Account User</fullName>
                </value>
                <value>
                    <fullName>Event/Webinar</fullName>
                </value>
                <value>
                    <fullName>Google AdWords</fullName>
                </value>
                <value>
                    <fullName>Newsletter</fullName>
                </value>
                <value>
                    <fullName>Paid Ad</fullName>
                </value>
                <value>
                    <fullName>Referral/Partner</fullName>
                </value>
                <value>
                    <fullName>Referral: Existing Customer</fullName>
                </value>
                <value>
                    <fullName>Sales Outbound</fullName>
                </value>
                <value>
                    <fullName>Trade Show/Sponsorships</fullName>
                </value>
                <value>
                    <fullName>Web Sign Up</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Ad - AdWords</fullName>
                </value>
                <value>
                    <fullName>Ad - Facebook</fullName>
                </value>
                <value>
                    <fullName>Ad - LinkedIn</fullName>
                </value>
                <value>
                    <fullName>Ad - Twitter</fullName>
                </value>
                <value>
                    <fullName>Ad - Quora</fullName>
                </value>
                <value>
                    <fullName>Ad - Media Sponsorship</fullName>
                </value>
                <value>
                    <fullName>Ad - Taboola</fullName>
                </value>
                <value>
                    <fullName>Ad - Outbrain</fullName>
                </value>
                <value>
                    <fullName>Content - Case Study</fullName>
                </value>
                <value>
                    <fullName>Content - eBook</fullName>
                </value>
                <value>
                    <fullName>Content - One Pager</fullName>
                </value>
                <value>
                    <fullName>Content - Webinar</fullName>
                </value>
                <value>
                    <fullName>Content - Video</fullName>
                </value>
                <value>
                    <fullName>Content - Sweepstakes</fullName>
                </value>
                <value>
                    <fullName>Event - Conference</fullName>
                </value>
                <value>
                    <fullName>Event - Happy Hour</fullName>
                </value>
                <value>
                    <fullName>Prospecting - LinkedIn</fullName>
                </value>
                <value>
                    <fullName>Prospecting - Scraping</fullName>
                </value>
                <value>
                    <fullName>Referral - Client</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

classes/Account_DAO.cls
public class Account_DAO  {
	
	public static Account getAccountById(Id accId) {
		List<Account> accounts = [SELECT AccountSource,Legacy_Account_Source_March_2019__c,Account_External_ID__c,Additional_Billing_Info__c,BillingAddress,BillingCity,
		BillingCountry,BillingGeocodeAccuracy,BillingLatitude,BillingLongitude,BillingPostalCode,BillingState,BillingStreet,cbit__ClearbitDomain__c,
		cbit__ClearbitReady__c,cbit__Clearbit__c,cbit__CreatedByClearbit__c,City__c,Company_Description__c,Country_Code__c,Country__c,CreatedById,
		CreatedDate,Customer_Life_Cycle_Stage__c,Customer_Type_Changed__c,Customer_Type_VIP_assigned__c,Customer_Type__c,Description,Description_Author__c,
		Domain_Aliases__c,Email_Addresses__c,Email_Provider__c,Employees_Range__c,Facebook__c,Fiscal_Year_Ends__c,Founded_Year__c,Id,Indexed_At__c,
		Industry,Industry_Group__c,Industry__c,IsDeleted,Jigsaw,JigsawCompanyId,LastActivityDate,LastModifiedById,LastModifiedDate,LastReferencedDate,
		LastViewedDate,Legal_Name__c,LinkedIn__c,Location__c,Logo__c,MasterRecordId,Name,NumberOfEmployees,OwnerId,ParentId,Parent_Company_Website__c,
		Phone,Phone_Numbers__c,Phone__c,PhotoUrl,Postal_Code__c,Raised__c,Referenceable__c,Reference_type__c,Sector__c,ShippingAddress,ShippingCity,
		ShippingCountry,ShippingGeocodeAccuracy,ShippingLatitude,ShippingLongitude,ShippingPostalCode,ShippingState,ShippingStreet,SicDesc,State_Code__c,
		State__c,Street_Number__c,Street__c,Sub_industry__c,Sub_premise__c,Success_Manager__c,SystemModstamp,Tags__c,Technologies__c,Ticker__c,
		Time_Zone__c,Type,UTC_Offset__c,VAT__c,Website,Website_Heading__c,Website_Title__c, MRR__c, ARR__c
		FROM Account
		WHERE Id = :accId];

		if(accounts.isEmpty()) {
			throw new ProductboardException('Account with ID ['+ accId +'] was not found.', ApiConstants.CODE_FAILED_RECORD_NOT_FOUND);
		}
		if(accounts.size() > 1) {
			throw new ProductboardException('There are more accounts with ID ['+ accId +'] in SF.', ApiConstants.CODE_FAILED_MORE_RECORDS_FOUND);
		}
		return accounts.get(0);
	}

	public static Account getSystemAccount() {
		List<Account> accounts = [SELECT AccountSource,Legacy_Account_Source_March_2019__c,Account_External_ID__c,Additional_Billing_Info__c,BillingAddress,BillingCity,
		BillingCountry,BillingGeocodeAccuracy,BillingLatitude,BillingLongitude,BillingPostalCode,BillingState,BillingStreet,cbit__ClearbitDomain__c,
		cbit__ClearbitReady__c,cbit__Clearbit__c,cbit__CreatedByClearbit__c,City__c,Company_Description__c,Country_Code__c,Country__c,CreatedById,
		CreatedDate,Customer_Life_Cycle_Stage__c,Customer_Type_Changed__c,Customer_Type_VIP_assigned__c,Customer_Type__c,Description,Description_Author__c,
		Domain_Aliases__c,Email_Addresses__c,Email_Provider__c,Employees_Range__c,Facebook__c,Fiscal_Year_Ends__c,Founded_Year__c,Id,Indexed_At__c,
		Industry,Industry_Group__c,Industry__c,IsDeleted,Jigsaw,JigsawCompanyId,LastActivityDate,LastModifiedById,LastModifiedDate,LastReferencedDate,
		LastViewedDate,Legal_Name__c,LinkedIn__c,Location__c,Logo__c,MasterRecordId,Name,NumberOfEmployees,OwnerId,ParentId,Parent_Company_Website__c,
		Phone,Phone_Numbers__c,Phone__c,PhotoUrl,Postal_Code__c,Raised__c,Referenceable__c,Reference_type__c,Sector__c,ShippingAddress,ShippingCity,
		ShippingCountry,ShippingGeocodeAccuracy,ShippingLatitude,ShippingLongitude,ShippingPostalCode,ShippingState,ShippingStreet,SicDesc,State_Code__c,
		State__c,Street_Number__c,Street__c,Sub_industry__c,Sub_premise__c,Success_Manager__c,SystemModstamp,Tags__c,Technologies__c,Ticker__c,
		Time_Zone__c,Type,UTC_Offset__c,VAT__c,Website,Website_Heading__c,Website_Title__c, MRR__c, ARR__c
		FROM Account
		WHERE Name = 'Customers_system_account'];

		if(accounts.isEmpty()) {
			throw new ProductboardException('System account [ Customers_system_account ] was not found.', ApiConstants.CODE_FAILED_RECORD_NOT_FOUND);
		}
		if(accounts.size() > 1) {
			throw new ProductboardException('There is more than one system account [ Customers_system_account ] in SF.', ApiConstants.CODE_FAILED_MORE_RECORDS_FOUND);
		}
		return accounts.get(0);
	}

	public static List<Account> getAllAccounts() {
		List<Account> accounts = [SELECT AccountSource,Legacy_Account_Source_March_2019__c,Account_External_ID__c,Additional_Billing_Info__c,BillingAddress,BillingCity,
		BillingCountry,BillingGeocodeAccuracy,BillingLatitude,BillingLongitude,BillingPostalCode,BillingState,BillingStreet,cbit__ClearbitDomain__c,
		cbit__ClearbitReady__c,cbit__Clearbit__c,cbit__CreatedByClearbit__c,City__c,Company_Description__c,Country_Code__c,Country__c,CreatedById,
		CreatedDate,Customer_Life_Cycle_Stage__c,Customer_Type_Changed__c,Customer_Type_VIP_assigned__c,Customer_Type__c,Description,Description_Author__c,
		Domain_Aliases__c,Email_Addresses__c,Email_Provider__c,Employees_Range__c,Facebook__c,Fiscal_Year_Ends__c,Founded_Year__c,Id,Indexed_At__c,
		Industry,Industry_Group__c,Industry__c,IsDeleted,Jigsaw,JigsawCompanyId,LastActivityDate,LastModifiedById,LastModifiedDate,LastReferencedDate,
		LastViewedDate,Legal_Name__c,LinkedIn__c,Location__c,Logo__c,MasterRecordId,Name,NumberOfEmployees,OwnerId,ParentId,Parent_Company_Website__c,
		Phone,Phone_Numbers__c,Phone__c,PhotoUrl,Postal_Code__c,Raised__c,Referenceable__c,Reference_type__c,Sector__c,ShippingAddress,ShippingCity,
		ShippingCountry,ShippingGeocodeAccuracy,ShippingLatitude,ShippingLongitude,ShippingPostalCode,ShippingState,ShippingStreet,SicDesc,State_Code__c,
		State__c,Street_Number__c,Street__c,Sub_industry__c,Sub_premise__c,Success_Manager__c,SystemModstamp,Tags__c,Technologies__c,Ticker__c,
		Time_Zone__c,Type,UTC_Offset__c,VAT__c,Website,Website_Heading__c,Website_Title__c, MRR__c, ARR__c
		FROM Account];
				
		return accounts;
	}

	public static void insertAccount(Account acc) {

		try {
			insert acc;
			System.debug('Account_DAO: insert - account was successfully inserted.');
		}
		catch(DmlException e) {
			System.debug('Account_DAO: insert - account ended with errors');
			throw new ProductboardException('Insert account was ended with errors: ' + e.getMessage(), ApiConstants.CODE_FAILED_DML_ERROR);
		}
	}

	
	public static void updateAccount(Account acc) {

		try {
			update acc;
			System.debug('Account_DAO: update - account was successfully updated.');
		}
		catch(DmlException e) {
			System.debug('Account_DAO: update - account ended with errors');
			throw new ProductboardException('Update account was ended with errors: ' + e.getMessage(), ApiConstants.CODE_FAILED_DML_ERROR);
		}

	}

	

	public static Account getAccountByName(String accName){
		List<Account> accs = [SELECT AccountSource,Legacy_Account_Source_March_2019__c,Account_External_ID__c,Additional_Billing_Info__c,BillingAddress,BillingCity,
		BillingCountry,BillingGeocodeAccuracy,BillingLatitude,BillingLongitude,BillingPostalCode,BillingState,BillingStreet,cbit__ClearbitDomain__c,
		cbit__ClearbitReady__c,cbit__Clearbit__c,cbit__CreatedByClearbit__c,City__c,Company_Description__c,Country_Code__c,Country__c,CreatedById,
		CreatedDate,Customer_Life_Cycle_Stage__c,Customer_Type_Changed__c,Customer_Type_VIP_assigned__c,Customer_Type__c,Description,Description_Author__c,
		Domain_Aliases__c,Email_Addresses__c,Email_Provider__c,Employees_Range__c,Facebook__c,Fiscal_Year_Ends__c,Founded_Year__c,Id,Indexed_At__c,
		Industry,Industry_Group__c,Industry__c,IsDeleted,Jigsaw,JigsawCompanyId,LastActivityDate,LastModifiedById,LastModifiedDate,LastReferencedDate,
		LastViewedDate,Legal_Name__c,LinkedIn__c,Location__c,Logo__c,MasterRecordId,Name,NumberOfEmployees,OwnerId,ParentId,Parent_Company_Website__c,
		Phone,Phone_Numbers__c,Phone__c,PhotoUrl,Postal_Code__c,Raised__c,Referenceable__c,Reference_type__c,Sector__c,ShippingAddress,ShippingCity,
		ShippingCountry,ShippingGeocodeAccuracy,ShippingLatitude,ShippingLongitude,ShippingPostalCode,ShippingState,ShippingStreet,SicDesc,State_Code__c,
		State__c,Street_Number__c,Street__c,Sub_industry__c,Sub_premise__c,Success_Manager__c,SystemModstamp,Tags__c,Technologies__c,Ticker__c,
		Time_Zone__c,Type,UTC_Offset__c,VAT__c,Website,Website_Heading__c,Website_Title__c
		FROM Account WHERE Name = :accName];

		return accs.get(0);
	}

}