objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LinkedIn__c</fullName>
        <label>LinkedIn</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Time_Zone__c</fullName>
        <label>Time Zone</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Indexed_At__c</fullName>
        <label>Indexed At</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Legal_Name__c</fullName>
        <label>Legal Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State_Code__c</fullName>
        <label>State Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UTC_Offset__c</fullName>
        <label>UTC Offset</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Country_Code__c</fullName>
        <label>Country Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Founded_Year__c</fullName>
        <label>Founded Year</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Phone_Numbers__c</fullName>
        <label>Phone Numbers</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Email_Addresses__c</fullName>
        <label>Email Addresses</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Employees_Range__c</fullName>
        <label>Employees Range_Delete</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fiscal_Year_Ends__c</fullName>
        <label>Fiscal Year Ends</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company_Description__c</fullName>
        <label>Company Description</label>
        <length>100000</length>
        <type>LongTextArea</type>
    </fields>
</CustomObject>

objects/Lead.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>country__c</fullName>
        <label>Person Country</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isAdmin__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isAdmin</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Enriched__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Clearbit enrichment</description>
        <label>Enriched</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LinkedIn__c</fullName>
        <label>LinkedIn</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>isEditor__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isEditor</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>isViewer__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isViewer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Full_Name__c</fullName>
        <label>Full Name</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Time_Zone__c</fullName>
        <label>Time Zone</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Indexed_At__c</fullName>
        <label>Indexed At</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Legal_Name__c</fullName>
        <label>Legal Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State_Code__c</fullName>
        <label>State Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UTC_Offset__c</fullName>
        <label>UTC Offset</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>User_PB_ID__c</fullName>
        <externalId>true</externalId>
        <label>User PB ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Company_City__c</fullName>
        <label>Company City</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company_Logo__c</fullName>
        <label>Company Logo</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Company_Type__c</fullName>
        <label>Company Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country_Code__c</fullName>
        <label>Country Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Founded_Year__c</fullName>
        <label>Founded Year</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Company_Phone__c</fullName>
        <label>Company Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Company_State__c</fullName>
        <label>Company State</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone_Numbers__c</fullName>
        <label>Phone Numbers</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>isContributor__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isContributor</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Company_Street__c</fullName>
        <label>Company Street</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company_Country__c</fullName>
        <label>Company Country</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_Addresses__c</fullName>
        <label>Email Addresses</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Employees_Range__c</fullName>
        <label>Employees Range</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company_LinkedIn__c</fullName>
        <label>Company LinkedIn</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Company_Location__c</fullName>
        <label>Company Location</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Fiscal_Year_Ends__c</fullName>
        <label>Fiscal Year Ends</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Personal_Website__c</fullName>
        <label>Personal Website</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Company_Time_Zone__c</fullName>
        <label>Company Time Zone</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Newsletter_Opt_In__c</fullName>
        <defaultValue>false</defaultValue>
        <description>User has opted in newsletter</description>
        <label>Newsletter Opt In</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Company_Indexed_At__c</fullName>
        <label>Company Indexed At</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Company_State_Code__c</fullName>
        <label>Company State Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company_UTC_Offset__c</fullName>
        <label>Company UTC Offset</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Person_External_ID__c</fullName>
        <label>Person External ID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Created_DT__c</fullName>
        <description>Datetime when a user creates the project or is invited to the project</description>
        <label>Project Created Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Company_Description__c</fullName>
        <label>Company Description</label>
        <length>100000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Company_External_ID__c</fullName>
        <label>Company External ID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company_Postal_Code__c</fullName>
        <label>Company Postal Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company_Sub_Premise__c</fullName>
        <label>Company Sub Premise</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company_Country_Code__c</fullName>
        <label>Company Country Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company_Street_Number__c</fullName>
        <label>Company Street Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company_Category_Sector__c</fullName>
        <label>[CB] Company Category Sector</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company_Category_Industry__c</fullName>
        <label>[CB] Company Category Industry</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company_Category_Sub_Industry__c</fullName>
        <label>[CB] Company Category Sub Industry</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Legacy_Lead_Source_March_2019__c</fullName>
        <description>Since LeadSource will be filling by Maketo, This field contains original value of leadSource before Marketo has been implemented</description>
        <label>Legacy Lead Source (March 2019)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Account User</fullName>
                </value>
                <value>
                    <fullName>Event/Webinar</fullName>
                </value>
                <value>
                    <fullName>Google AdWords</fullName>
                </value>
                <value>
                    <fullName>Newsletter</fullName>
                </value>
                <value>
                    <fullName>Paid Ad</fullName>
                </value>
                <value>
                    <fullName>Referral/Partner</fullName>
                </value>
                <value>
                    <fullName>Referral: Existing Customer</fullName>
                </value>
                <value>
                    <fullName>Sales Outbound</fullName>
                </value>
                <value>
                    <fullName>Trade Show/Sponsorships</fullName>
                </value>
                <value>
                    <fullName>Web Sign Up</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Ad - AdWords</fullName>
                </value>
                <value>
                    <fullName>Ad - Facebook</fullName>
                </value>
                <value>
                    <fullName>Ad - LinkedIn</fullName>
                </value>
                <value>
                    <fullName>Ad - Twitter</fullName>
                </value>
                <value>
                    <fullName>Ad - Quora</fullName>
                </value>
                <value>
                    <fullName>Ad - Media Sponsorship</fullName>
                </value>
                <value>
                    <fullName>Ad - Taboola</fullName>
                </value>
                <value>
                    <fullName>Ad - Outbrain</fullName>
                </value>
                <value>
                    <fullName>Content - Case Study</fullName>
                </value>
                <value>
                    <fullName>Content - eBook</fullName>
                </value>
                <value>
                    <fullName>Content - One Pager</fullName>
                </value>
                <value>
                    <fullName>Content - Webinar</fullName>
                </value>
                <value>
                    <fullName>Content - Video</fullName>
                </value>
                <value>
                    <fullName>Content - Sweepstakes</fullName>
                </value>
                <value>
                    <fullName>Event - Conference</fullName>
                </value>
                <value>
                    <fullName>Event - Happy Hour</fullName>
                </value>
                <value>
                    <fullName>Prospecting - LinkedIn</fullName>
                </value>
                <value>
                    <fullName>Prospecting - Scraping</fullName>
                </value>
                <value>
                    <fullName>Referral - Client</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Company_Category_Industry_Group__c</fullName>
        <label>[CB] Company Category Industry Group</label>
        <length>200</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/User.object
<CustomObject>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>Full_Name__c</fullName>
        <formula>FirstName &amp; &quot; &quot; &amp;  LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>First Name + Last Name</inlineHelpText>
        <label>Full Name</label>
        <type>Text</type>
    </fields>
</CustomObject>

classes/Lead_DAO.cls
public class Lead_DAO {
	public static List<Lead> getUnconvertedLeadsByEmail(String email) {
		return [
			SELECT
				Address,
				AnnualRevenue,
				City,
				City__c,
				Company,
				Company_Category_Industry__c,
				Company_Category_Industry_Group__c,
				Company_Category_Sector__c,
				Company_Category_Sub_Industry__c,
				User_PB_ID__c,
				Company_City__c,
				Company_Country__c,
				Company_Country_Code__c,
				Company_Description__c,
				Company_External_ID__c,
				Company_Indexed_At__c,
				Company_LinkedIn__c,
				Company_Location__c,
				Company_Logo__c,
				Company_Phone__c,
				Company_Postal_Code__c,
				Company_State__c,
				Company_State_Code__c,
				Company_Street__c,
				Company_Street_Number__c,
				Company_Sub_Premise__c,
				Company_Time_Zone__c,
				Company_Type__c,
				Company_UTC_Offset__c,
				ConvertedAccountId,
				ConvertedContactId,
				ConvertedDate,
				ConvertedOpportunityId,
				Country,
				Country__c,
				Country_Code__c,
				CreatedById,
				CreatedDate,
				Email,
				Email_Addresses__c,
				EmailBouncedDate,
				EmailBouncedReason,
				Employees_Range__c,
				Enriched__c,
				Fax,
				FirstName,
				Fiscal_Year_Ends__c,
				Founded_Year__c,
				Full_Name__c,
				Gender__c,
				GeocodeAccuracy,
				HasOptedOutOfEmail,
				Id,
				Indexed_At__c,
				Industry,
				IsAdmin__c,
				IsEditor__c,
				IsViewer__c,
				IsContributor__c,
				IsConverted,
				IsDeleted,
				IsUnreadByOwner,
				Jigsaw,
				JigsawContactId,
				LastActivityDate,
				LastModifiedById,
				LastModifiedDate,
				LastName,
				LastReferencedDate,
				LastViewedDate,
				Latitude,
				LeadSource,
				Legacy_Lead_Source_March_2019__c,
				Legal_Name__c,
				LinkedIn__c,
				Location__c,
				Longitude,
				MasterRecordId,
				MiddleName,
				MobilePhone,
				Name,
				Newsletter_Opt_In__c,
				NumberOfEmployees,
				OwnerId,
				Person_External_ID__c,
				Personal_Website__c,
				Phone,
				Phone_Numbers__c,
				PhotoUrl,
				PostalCode,
				Project_Created_DT__c,
				Raised__c,
				Rating,
				Role__c,
				Salutation,
				Seniority__c,
				State,
				State__c,
				State_Code__c,
				Status,
				Street,
				Suffix,
				SystemModstamp,
				Tags__c,
				Technologies__c,
				Time_Zone__c,
				Title,
				Trial_Request_DT__c,
				Trial_Source__c,
				Trial_Usage_Score__c,
				UTC_Offset__c,
				VAT__c,
				Website
			FROM Lead
			WHERE IsConverted = FALSE AND Email = :email
		];
	}

	public static Lead getLeadByEmail2(String email) {
		List<Lead> leads = [
			SELECT
				Address,
				AnnualRevenue,
				City,
				City__c,
				Company,
				Company_Category_Industry__c,
				Company_Category_Industry_Group__c,
				Company_Category_Sector__c,
				Company_Category_Sub_Industry__c,
				User_PB_ID__c,
				Company_City__c,
				Company_Country__c,
				Company_Country_Code__c,
				Company_Description__c,
				Company_External_ID__c,
				Company_Indexed_At__c,
				Company_LinkedIn__c,
				Company_Location__c,
				Company_Logo__c,
				Company_Phone__c,
				Company_Postal_Code__c,
				Company_State__c,
				Company_State_Code__c,
				Company_Street__c,
				Company_Street_Number__c,
				Company_Sub_Premise__c,
				Company_Time_Zone__c,
				Company_Type__c,
				Company_UTC_Offset__c,
				ConvertedAccountId,
				ConvertedContactId,
				ConvertedDate,
				ConvertedOpportunityId,
				Country,
				Country__c,
				Country_Code__c,
				CreatedById,
				CreatedDate,
				Email,
				Email_Addresses__c,
				EmailBouncedDate,
				EmailBouncedReason,
				Employees_Range__c,
				Enriched__c,
				Fax,
				FirstName,
				Fiscal_Year_Ends__c,
				Founded_Year__c,
				Full_Name__c,
				Gender__c,
				GeocodeAccuracy,
				HasOptedOutOfEmail,
				Id,
				Indexed_At__c,
				Industry,
				IsAdmin__c,
				IsEditor__c,
				IsViewer__c,
				IsContributor__c,
				IsConverted,
				IsDeleted,
				IsUnreadByOwner,
				Jigsaw,
				JigsawContactId,
				LastActivityDate,
				LastModifiedById,
				LastModifiedDate,
				LastName,
				LastReferencedDate,
				LastViewedDate,
				Latitude,
				LeadSource,
				Legacy_Lead_Source_March_2019__c,
				Legal_Name__c,
				LinkedIn__c,
				Location__c,
				Longitude,
				MasterRecordId,
				MiddleName,
				MobilePhone,
				Name,
				Newsletter_Opt_In__c,
				NumberOfEmployees,
				OwnerId,
				Person_External_ID__c,
				Personal_Website__c,
				Phone,
				Phone_Numbers__c,
				PhotoUrl,
				PostalCode,
				Project_Created_DT__c,
				Raised__c,
				Rating,
				Role__c,
				Salutation,
				Seniority__c,
				State,
				State__c,
				State_Code__c,
				Status,
				Street,
				Suffix,
				SystemModstamp,
				Tags__c,
				Technologies__c,
				Time_Zone__c,
				Title,
				Trial_Request_DT__c,
				Trial_Source__c,
				Trial_Usage_Score__c,
				UTC_Offset__c,
				VAT__c,
				Website,
				cbit__Clearbit__c
			FROM Lead
			WHERE Email = :email
		];
		if (leads.isEmpty()) {
			throw new ProductboardException('Lead with email [' + email + '] was not found.', ApiConstants.CODE_FAILED_RECORD_NOT_FOUND);
		}
		if (leads.size() > 1) {
			throw new ProductboardException(
				'More leads with email [' +
				email +
				'] were found.',
				ApiConstants.CODE_FAILED_MORE_RECORDS_FOUND
			);
		}
		return leads.get(0);
	}

	public static List<Lead> getAllLeadsByEmail(String email) {
		return [
			SELECT
				Address,
				AnnualRevenue,
				City,
				City__c,
				Company,
				Company_Category_Industry__c,
				Company_Category_Industry_Group__c,
				Company_Category_Sector__c,
				Company_Category_Sub_Industry__c,
				Company_City__c,
				Company_Country__c,
				Company_Country_Code__c,
				Company_Description__c,
				Company_External_ID__c,
				Company_Indexed_At__c,
				Company_LinkedIn__c,
				Company_Location__c,
				Company_Logo__c,
				Company_Phone__c,
				Company_Postal_Code__c,
				Company_State__c,
				Company_State_Code__c,
				Company_Street__c,
				Company_Street_Number__c,
				Company_Sub_Premise__c,
				Company_Time_Zone__c,
				Company_Type__c,
				Company_UTC_Offset__c,
				ConvertedAccountId,
				ConvertedContactId,
				ConvertedDate,
				ConvertedOpportunityId,
				Country,
				Country__c,
				Country_Code__c,
				CreatedById,
				CreatedDate,
				Email,
				Email_Addresses__c,
				EmailBouncedDate,
				EmailBouncedReason,
				Employees_Range__c,
				Enriched__c,
				Fax,
				FirstName,
				Fiscal_Year_Ends__c,
				User_PB_ID__c,
				Founded_Year__c,
				Full_Name__c,
				Gender__c,
				GeocodeAccuracy,
				HasOptedOutOfEmail,
				Id,
				Indexed_At__c,
				Industry,
				IsAdmin__c,
				IsEditor__c,
				IsViewer__c,
				IsContributor__c,
				IsConverted,
				IsDeleted,
				IsUnreadByOwner,
				Jigsaw,
				JigsawContactId,
				LastActivityDate,
				LastModifiedById,
				LastModifiedDate,
				LastName,
				LastReferencedDate,
				LastViewedDate,
				Latitude,
				LeadSource,
				Legacy_Lead_Source_March_2019__c,
				Legal_Name__c,
				LinkedIn__c,
				Location__c,
				Longitude,
				MasterRecordId,
				MiddleName,
				MobilePhone,
				Name,
				Newsletter_Opt_In__c,
				NumberOfEmployees,
				OwnerId,
				Person_External_ID__c,
				Personal_Website__c,
				Phone,
				Phone_Numbers__c,
				PhotoUrl,
				PostalCode,
				Project_Created_DT__c,
				Raised__c,
				Rating,
				Role__c,
				Salutation,
				Seniority__c,
				State,
				State__c,
				State_Code__c,
				Status,
				Street,
				Suffix,
				SystemModstamp,
				Tags__c,
				Technologies__c,
				Time_Zone__c,
				Title,
				Trial_Request_DT__c,
				Trial_Source__c,
				Trial_Usage_Score__c,
				UTC_Offset__c,
				Trial_End_Date__c,
				VAT__c,
				Website
			FROM Lead
			WHERE Email = :email
		];
	}

	public static List<Lead> getLeadbyId(Id id) {
		return [
			SELECT
				Address,
				AnnualRevenue,
				City,
				City__c,
				Trial_End_Date__c,
				Company,
				Company_Category_Industry__c,
				Company_Category_Industry_Group__c,
				Company_Category_Sector__c,
				Company_Category_Sub_Industry__c,
				Company_City__c,
				Company_Country__c,
				Company_Country_Code__c,
				Company_Description__c,
				Company_External_ID__c,
				Company_Indexed_At__c,
				User_PB_ID__c,
				Company_LinkedIn__c,
				Company_Location__c,
				Company_Logo__c,
				Company_Phone__c,
				Company_Postal_Code__c,
				Company_State__c,
				Company_State_Code__c,
				Company_Street__c,
				Company_Street_Number__c,
				Company_Sub_Premise__c,
				Company_Time_Zone__c,
				Company_Type__c,
				Company_UTC_Offset__c,
				ConvertedAccountId,
				ConvertedContactId,
				ConvertedDate,
				ConvertedOpportunityId,
				Country,
				Country__c,
				Country_Code__c,
				CreatedById,
				CreatedDate,
				Email,
				Email_Addresses__c,
				EmailBouncedDate,
				EmailBouncedReason,
				Employees_Range__c,
				Enriched__c,
				Fax,
				FirstName,
				Fiscal_Year_Ends__c,
				Founded_Year__c,
				Full_Name__c,
				Gender__c,
				GeocodeAccuracy,
				HasOptedOutOfEmail,
				Id,
				Indexed_At__c,
				Industry,
				IsAdmin__c,
				IsEditor__c,
				IsViewer__c,
				IsContributor__c,
				IsConverted,
				IsDeleted,
				IsUnreadByOwner,
				Jigsaw,
				JigsawContactId,
				LastActivityDate,
				LastModifiedById,
				LastModifiedDate,
				LastName,
				LastReferencedDate,
				LastViewedDate,
				Latitude,
				LeadSource,
				Legacy_Lead_Source_March_2019__c,
				Legal_Name__c,
				LinkedIn__c,
				Location__c,
				Longitude,
				MasterRecordId,
				MiddleName,
				MobilePhone,
				Name,
				Newsletter_Opt_In__c,
				NumberOfEmployees,
				OwnerId,
				Person_External_ID__c,
				Personal_Website__c,
				Phone,
				Phone_Numbers__c,
				PhotoUrl,
				PostalCode,
				Project_Created_DT__c,
				Raised__c,
				Rating,
				Role__c,
				Salutation,
				Seniority__c,
				State,
				State__c,
				State_Code__c,
				Status,
				Street,
				Suffix,
				SystemModstamp,
				Tags__c,
				Technologies__c,
				Time_Zone__c,
				Title,
				Trial_Request_DT__c,
				Trial_Source__c,
				Trial_Usage_Score__c,
				UTC_Offset__c,
				VAT__c,
				Website
			FROM Lead
			WHERE Id = :id
		];
	}

	public static List<Lead> getLeadbyId2(Id id) {
		List<Lead> leads = [
			SELECT
				Address,
				AnnualRevenue,
				City,
				City__c,
				Company,
				Company_Category_Industry__c,
				Company_Category_Industry_Group__c,
				Company_Category_Sector__c,
				Company_Category_Sub_Industry__c,
				Company_City__c,
				Company_Country__c,
				Company_Country_Code__c,
				Company_Description__c,
				Company_External_ID__c,
				Company_Indexed_At__c,
				Company_LinkedIn__c,
				Company_Location__c,
				Trial_End_Date__c,
				Company_Logo__c,
				Company_Phone__c,
				Company_Postal_Code__c,
				User_PB_ID__c,
				Company_State__c,
				Company_State_Code__c,
				Company_Street__c,
				Company_Street_Number__c,
				Company_Sub_Premise__c,
				Company_Time_Zone__c,
				Company_Type__c,
				Company_UTC_Offset__c,
				ConvertedAccountId,
				ConvertedContactId,
				ConvertedDate,
				ConvertedOpportunityId,
				Country,
				Country__c,
				Country_Code__c,
				CreatedById,
				CreatedDate,
				Email,
				Email_Addresses__c,
				EmailBouncedDate,
				EmailBouncedReason,
				Employees_Range__c,
				Enriched__c,
				Fax,
				FirstName,
				Fiscal_Year_Ends__c,
				Founded_Year__c,
				Full_Name__c,
				Gender__c,
				GeocodeAccuracy,
				HasOptedOutOfEmail,
				Id,
				Indexed_At__c,
				Industry,
				IsAdmin__c,
				IsEditor__c,
				IsViewer__c,
				IsContributor__c,
				IsConverted,
				IsDeleted,
				IsUnreadByOwner,
				Jigsaw,
				JigsawContactId,
				LastActivityDate,
				LastModifiedById,
				LastModifiedDate,
				LastName,
				LastReferencedDate,
				LastViewedDate,
				Latitude,
				LeadSource,
				Legacy_Lead_Source_March_2019__c,
				Legal_Name__c,
				LinkedIn__c,
				Location__c,
				Longitude,
				MasterRecordId,
				MiddleName,
				MobilePhone,
				Name,
				Newsletter_Opt_In__c,
				NumberOfEmployees,
				OwnerId,
				Person_External_ID__c,
				Personal_Website__c,
				Phone,
				Phone_Numbers__c,
				PhotoUrl,
				PostalCode,
				Project_Created_DT__c,
				Raised__c,
				Rating,
				Role__c,
				Salutation,
				Seniority__c,
				State,
				State__c,
				State_Code__c,
				Status,
				Street,
				Suffix,
				SystemModstamp,
				Tags__c,
				Technologies__c,
				Time_Zone__c,
				Title,
				Trial_Request_DT__c,
				Trial_Source__c,
				Trial_Usage_Score__c,
				UTC_Offset__c,
				VAT__c,
				Website,
				cbit__Clearbit__c
			FROM Lead
			WHERE Id = :id
		];
		if (leads.isEmpty()) {
			throw new ProductboardException(
				'Lead for the project with lead ID [' +
				id +
				'] was not found.',
				ApiConstants.CODE_FAILED_RECORD_NOT_FOUND
			);
		}
		return leads;
	}

	public static List<Lead> getLeadsByListOfProjectUserIds(List<Id> pusIds) {
		List<Lead> leads = [
			SELECT
				Address,
				AnnualRevenue,
				City,
				City__c,
				Company,
				Company_Category_Industry__c,
				Company_Category_Industry_Group__c,
				Company_Category_Sector__c,
				Company_Category_Sub_Industry__c,
				Company_City__c,
				Company_Country__c,
				Company_Country_Code__c,
				Company_Description__c,
				Company_External_ID__c,
				Company_Indexed_At__c,
				Company_LinkedIn__c,
				Company_Location__c,
				Trial_End_Date__c,
				Company_Logo__c,
				Company_Phone__c,
				Company_Postal_Code__c,
				Company_State__c,
				Company_State_Code__c,
				Company_Street__c,
				Company_Street_Number__c,
				Company_Sub_Premise__c,
				Company_Time_Zone__c,
				Company_Type__c,
				Company_UTC_Offset__c,
				ConvertedAccountId,
				ConvertedContactId,
				ConvertedDate,
				ConvertedOpportunityId,
				Country,
				Country__c,
				Country_Code__c,
				User_PB_ID__c,
				CreatedById,
				CreatedDate,
				Email,
				Email_Addresses__c,
				EmailBouncedDate,
				EmailBouncedReason,
				Employees_Range__c,
				Enriched__c,
				Fax,
				FirstName,
				Fiscal_Year_Ends__c,
				Founded_Year__c,
				Full_Name__c,
				Gender__c,
				GeocodeAccuracy,
				HasOptedOutOfEmail,
				Id,
				Indexed_At__c,
				Industry,
				IsAdmin__c,
				IsEditor__c,
				IsViewer__c,
				IsContributor__c,
				IsConverted,
				IsDeleted,
				IsUnreadByOwner,
				Jigsaw,
				JigsawContactId,
				LastActivityDate,
				LastModifiedById,
				LastModifiedDate,
				LastName,
				LastReferencedDate,
				LastViewedDate,
				Latitude,
				LeadSource,
				Legacy_Lead_Source_March_2019__c,
				Legal_Name__c,
				LinkedIn__c,
				Location__c,
				Longitude,
				MasterRecordId,
				MiddleName,
				MobilePhone,
				Name,
				Newsletter_Opt_In__c,
				NumberOfEmployees,
				OwnerId,
				Person_External_ID__c,
				Personal_Website__c,
				Phone,
				Phone_Numbers__c,
				PhotoUrl,
				PostalCode,
				Project_Created_DT__c,
				Raised__c,
				Rating,
				Role__c,
				Salutation,
				Seniority__c,
				State,
				State__c,
				State_Code__c,
				Status,
				Street,
				Suffix,
				SystemModstamp,
				Tags__c,
				Technologies__c,
				Time_Zone__c,
				Title,
				Trial_Request_DT__c,
				Trial_Source__c,
				Trial_Usage_Score__c,
				UTC_Offset__c,
				VAT__c,
				Website
			FROM Lead
			WHERE Id IN :pusIds
		];
		if (leads.isEmpty()) {
			throw new ProductboardException('Lead for the project user was not found.', ApiConstants.CODE_FAILED_RECORD_NOT_FOUND);
		}
		return leads;
	}

	public static void upsertLeadRequest(Lead lead, TrialOps.LeadInfo info, Datetime now) {
		if (lead.Id == null) {
			lead.Email = info.userEmail.toLowerCase();
			lead.Company = 'Not provided';
			lead.LastName = 'Not provided';
			lead.Status = 'New';
			lead.Legacy_Lead_Source_March_2019__c = 'Web Sign Up';
		}

		lead.User_PB_ID__c = Double.valueOf(info.userId);
		if (info.spaceType == 'standalone_portal') {
			lead.Space_Type__c = 'Standalone Portal';
			lead.Portal_Source__c = getSource(info.spaceType, 'Request');
			lead.Portal_Request_DT__c = now;
		} else if (info.spaceType == 'starter') {
			lead.Space_Type__c = 'Starter';
			lead.Starter_Source__c = getSource(info.spaceType, 'Request');
			lead.Starter_Request_DT__c = now;
		} else {
			lead.Space_Type__c = 'Main';
			lead.Trial_Source__c = getSource(info.spaceType, 'Request');
			lead.Trial_Request_DT__c = now;
		}
	}

	public static void upsertLeadOwner(Lead lead, TrialOps.LeadInfo info, Datetime now) {
		if (lead.Id == null) {
			lead.Email = info.userEmail.toLowerCase();
			lead.LastName = 'Not provided';
			lead.Status = 'New';
			lead.Legacy_Lead_Source_March_2019__c = 'Web Sign Up';
		}

		lead.User_PB_ID__c = Double.valueOf(info.userId);
		lead.Project_Created_DT__c = now;

		//assign source and requet DT
		if (info.spaceType == 'standalone_portal') {
			lead.Space_Type__c = 'Standalone Portal';
			lead.Portal_Source__c = getSource(info.spaceType, 'Owner');
			if (lead.Portal_Request_DT__c == null) {
				lead.Portal_Request_DT__c = now;
			}
			lead.Portal_Activation_DT__c = now;
		} else if (info.spaceType == 'starter') {
			lead.Space_Type__c = 'Starter';
			lead.Starter_Source__c = getSource(info.spaceType, 'Owner');
			if (lead.Starter_Request_DT__c == null) {
				lead.Starter_Request_DT__c = now;
			}
			lead.Starter_Activation_DT__c = now;
		} else {
			lead.Space_Type__c = 'Main';
			lead.Trial_Source__c = getSource(info.spaceType, 'Owner');
			if (lead.Trial_Request_DT__c == null) {
				lead.Trial_Request_DT__c = now;
			}
			lead.Trial_Activation_DT__c = now;
			lead.isTrial__c = true;
			//assign Trial EndDate
			if (info.trialEndDate != null) {
				lead.Trial_End_Date__c = info.trialEndDate;
			}
		}

		//assignCompanyName
		if ((lead.Company == null || lead.Company == 'Not provided') && (info.company != null && info.company != '')) {
			lead.Company = info.company;
		} else if ((lead.Company == null || lead.Company == 'Not provided') && (info.company == null || info.company == '')) {
			lead.Company = 'Not provided';
		}

		//assignPhone
		if (info.phone != null && info.phone != '') {
			lead.Phone = info.phone;
		}

		//assignName
		if (info.fullName != null && info.fullName != '') {
			if (lead.Name == 'Not provided' || lead.Name == null || lead.Name == '[[unknown]]') {
				parseLeadFullName(info.fullName, lead);
			} else {
				lead.Full_Name__c = info.fullName;
			}
		}
	}

	public static void upsertLeadUser(Lead lead, String spaceType, String email, Double userId, Datetime now) {
		if (lead.Id == null) {
			lead.Email = email;
			lead.LastName = 'Not provided';
			lead.Company = 'Not provided';
			lead.Status = 'New';
			lead.Legacy_Lead_Source_March_2019__c = 'Account User';
		}

		lead.User_PB_ID__c = Double.valueOf(userId);
		lead.Project_Created_DT__c = now;

		if (spaceType == 'Standalone Portal') {
			lead.Space_Type__c = 'Standalone Portal';
			lead.Portal_Source__c = getSource(spaceType, 'User');
			lead.Portal_Request_DT__c = now;
			lead.Portal_Activation_DT__c = now;
			lead.isTrial__c = true;
		} else if (spaceType == 'Starter') {
			lead.Space_Type__c = 'Starter';
			lead.Starter_Source__c = getSource(spaceType, 'User');
			lead.Starter_Request_DT__c = now;
			lead.Starter_Activation_DT__c = now;
			lead.isTrial__c = true;
		} else {
			lead.Space_Type__c = 'Main';
			if (lead.Trial_Source__c == null || lead.Trial_Source__c.equals('Trial Request')) {
				lead.Trial_Source__c = getSource(spaceType, 'User');
			}
			lead.Trial_Request_DT__c = now;
			lead.Trial_Activation_DT__c = now;
		}
	}

	public static String getSource(String spaceType, String suffix) {
		if (spaceType == 'standalone_portal' || spaceType == 'Standalone Portal') {
			return 'Portal ' + suffix;
		} else if (spaceType == 'starter' || spaceType == 'Starter') {
			return 'Starter ' + suffix;
		} else {
			return 'Trial ' + suffix;
		}
	}

	public static void insertLead(Lead ld) {
		try {
			insert ld;
		} catch (DmlException e) {
			throw new ProductboardException('Insert Lead was ended with errors: ' + e.getMessage(), ApiConstants.CODE_FAILED_DML_ERROR);
		}
	}

	public static void updateLead(Lead ld) {
		try {
			update ld;
		} catch (DmlException e) {
			throw new ProductboardException('Update Lead was ended with errors: ' + e.getMessage(), ApiConstants.CODE_FAILED_DML_ERROR);
		}
	}

	public static void parseLeadFullName(String fullName, Lead lead) {
		// update name

		if (fullName.contains(' ')) {
			if (fullName.substringAfter(' ') == null || fullName.substringAfter(' ').equals('')) {
				lead.LastName = fullName.substringBefore(' ');
			} else {
				lead.FirstName = fullName.substringBefore(' ');
				lead.LastName = fullName.substringAfter(' ');
			}
		} else {
			lead.LastName = fullName;
		}
		lead.Full_Name__c = fullName;
	}
}