objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Contact_Apex_Trigger_Field__c</fullName>
        <label>Contact Apex Trigger Field</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Apex_Trigger_Field__c</fullName>
        <label>Opportunity Apex Trigger Field</label>
        <length>100</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Contact.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Trial_End_Date__c</fullName>
        <label>Trial End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Related_Account_Apex_Trigger_Field__c</fullName>
        <label>Related Account Apex Trigger Field</label>
        <length>100</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunity</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Trial_End_Date__c</fullName>
        <formula>If( IsPickVal(Type ,&quot;New Business&quot;) &amp;&amp;  Not(Contains(Project__r.Name ,&quot;Placeholder&quot;)), Project__r.Trial_End_Date__c ,Null)</formula>
        <inlineHelpText>Lookup to Project Trial End Date for New Business Opportunities (Excludes Placeholder Project)</inlineHelpText>
        <label>Trial End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Related_Account_Apex_Trigger_Field__c</fullName>
        <label>Related Account Apex Trigger Field</label>
        <length>100</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Trial_End_Date__c</fullName>
        <label>Trial End Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

classes/AccountToConOppUpdateTriggerTest.cls
@isTest 
private class AccountToConOppUpdateTriggerTest {

    @TestSetup
    private static void init(){
        DataFactory_TEST.init();
    }

	@isTest
	private static void testContacts() {
		Account a = new Account();
		a.Name = 'testAcc';
        insert a;

		Contact cont = new Contact();
		cont.LastName = 'Hopkins';
        cont.Accountid = a.id;
        cont.Trial_End_Date__c = Date.today().addDays(30);
        cont.Email = GeneralConfig_TEST.TEST_NEW_USER_EMAIL;
		insert cont;

        Product2 prod = [SELECT Id,Name FROM Product2 LIMIT 1];
        Project__c proj = DataFactory_TEST.createProject(a.Id,cont.Id,prod.Id);
        
        Opportunity opp = new Opportunity();
        opp.Project__c = proj.id;
        opp.Name = 'testAccOpp';
        opp.StageName = 'Free Trial';
        opp.CloseDate = System.today();
        
        
		
		opp.AccountId = a.Id;
		cont.AccountId = a.Id;
		opp.Account = a;

		insert opp;
		// end of init
		
		a.Opportunity_Apex_Trigger_Field__c = 'Something';
		update a;
		Test.startTest();
		Test.stopTest();
		
		// Opportunity testOpp = [SELECT Id,Name,Related_Account_Apex_Trigger_Field__c FROM Opportunity WHERE AccountId=:a.Id LIMIT 1];
		// System.assertEquals('Something',testOpp.Related_Account_Apex_Trigger_Field__c);
	}

	@isTest
	private static void testOpps() {
		Account a = new Account();
		a.Name = 'testAcc';
        insert a;

        Contact cont = new Contact();
        cont.LastName = 'Hopkins';
        cont.Accountid = a.id;
        cont.Trial_End_Date__c = Date.today().addDays(30);
        cont.Email = GeneralConfig_TEST.TEST_NEW_USER_EMAIL;
        insert cont;

        Product2 prod = [SELECT Id,Name FROM Product2 LIMIT 1];
        Project__c proj = DataFactory_TEST.createProject(a.Id,cont.Id,prod.Id);

		Opportunity opp = new Opportunity();
        opp.Project__c = proj.id;
		opp.Name = 'testAccOpp';
		opp.StageName = 'Free Trial';
		opp.CloseDate = System.today();
		

		opp.AccountId = a.Id;
		cont.AccountId = a.Id;
		opp.Account = a;


		insert opp;
		// end of init
		
		a.Contact_Apex_Trigger_Field__c = 'Something';
		update a;
		Test.startTest();
		Test.stopTest();
		
		// Contact testCon = [SELECT Id,Name,Related_Account_Apex_Trigger_Field__c FROM Contact WHERE AccountId=:a.Id LIMIT 1];
		// System.assertEquals('Something',testCon.Related_Account_Apex_Trigger_Field__c);
	}
}