objects/API_Request__c.object
<CustomObject>
    <label>API Request</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>API Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>API Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>hash__c</fullName>
        <label>hash</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>plan__c</fullName>
        <label>plan</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>phone__c</fullName>
        <label>phone</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Detail__c</fullName>
        <label>Detail</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Method__c</fullName>
        <label>Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>createNewProject</fullName>
                </value>
                <value>
                    <fullName>createTrialLead</fullName>
                </value>
                <value>
                    <fullName>updateBillingInformation</fullName>
                </value>
                <value>
                    <fullName>newUserEvent</fullName>
                </value>
                <value>
                    <fullName>removeUserEvent</fullName>
                </value>
                <value>
                    <fullName>changeRoleEvent</fullName>
                </value>
                <value>
                    <fullName>freezeUserEvent</fullName>
                </value>
                <value>
                    <fullName>unfreezeUserEvent</fullName>
                </value>
                <value>
                    <fullName>updateUserInfo</fullName>
                </value>
                <value>
                    <fullName>updateUserPbOptIn</fullName>
                </value>
                <value>
                    <fullName>updateTrialEndDate</fullName>
                </value>
                <value>
                    <fullName>deleteSpace</fullName>
                </value>
                <value>
                    <fullName>addSubscription</fullName>
                </value>
                <value>
                    <fullName>cancelSubscription</fullName>
                </value>
                <value>
                    <fullName>changePlan</fullName>
                </value>
                <value>
                    <fullName>updateUserFullName</fullName>
                </value>
                <value>
                    <fullName>updateUserEmail</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>biCity__c</fullName>
        <label>biCity</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccCity__c</fullName>
        <label>ccCity</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>userId__c</fullName>
        <label>userId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Success__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Success</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>biState__c</fullName>
        <label>biState</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccState__c</fullName>
        <label>ccState</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>company__c</fullName>
        <label>company</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>pbOptIn__c</fullName>
        <label>pbOptIn</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>teamUrl__c</fullName>
        <label>teamUrl</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>userId1__c</fullName>
        <label>userId1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>userId2__c</fullName>
        <label>userId2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>userId3__c</fullName>
        <label>userId3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UserRole__c</fullName>
        <label>UserRole</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>fullName__c</fullName>
        <label>fullName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>biAddress__c</fullName>
        <label>biAddress</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>biCountry__c</fullName>
        <label>biCountry</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccAddress__c</fullName>
        <label>ccAddress</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccCountry__c</fullName>
        <label>ccCountry</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>eventType__c</fullName>
        <label>eventType</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>frequency__c</fullName>
        <label>frequency</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>projectId__c</fullName>
        <label>projectId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>spaceType__c</fullName>
        <label>spaceType</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>userEmail__c</fullName>
        <label>userEmail</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>userEmail1__c</fullName>
        <label>userEmail1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>userEmail2__c</fullName>
        <label>userEmail2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>userEmail3__c</fullName>
        <label>userEmail3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>biVATNumber__c</fullName>
        <label>biVATNumber</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>planVersion__c</fullName>
        <label>planVersion</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>biPostalCode__c</fullName>
        <label>biPostalCode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccPostalCode__c</fullName>
        <label>ccPostalCode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>discountType__c</fullName>
        <label>discountType</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>trialEndDate__c</fullName>
        <label>trialEndDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Response_Code__c</fullName>
        <label>Response Code</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>amountOfUsers__c</fullName>
        <label>amountOfUsers</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>biCompanyName__c</fullName>
        <label>biCompanyName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>discountValue__c</fullName>
        <label>discountValue</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>activationDate__c</fullName>
        <label>activationDate</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ccBillingEmail__c</fullName>
        <label>ccBillingEmail</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>discountLength__c</fullName>
        <label>discountLength</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>billingInfoFlag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>billingInfoFlag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>discountSubtype__c</fullName>
        <label>discountSubtype</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>stripeInvoiceId__c</fullName>
        <label>stripeInvoiceId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Original_Request__c</fullName>
        <label>Original Request</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Response_Message__c</fullName>
        <label>Response Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>biAdditionalInfo__c</fullName>
        <label>biAdditionalInfo</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>userEmailsToActivate__c</fullName>
        <label>userEmailsToActivate</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

classes/ApiRequestController.cls
public class ApiRequestController {

    public static void logApiRequest(String jsonReq, String recordTypeName, Boolean success, String method, String detail, ApiResponse res) { 
        ApiResponseDTO responseDto = new ApiResponseDTO();
        responseDto.statusCode = res.statusCode;
        responseDto.statusMessage = res.statusMessage;
        logApiRequest(jsonReq,recordTypeName,success,method,detail,responseDto);
    }
    
    public static void logApiRequest(String jsonReq, String recordTypeName, Boolean success, String method, String detail, ApiResponseDTO res) { 
        API_Request__c ar = new API_Request__c();
        
        ar.RecordTypeId = Utils.getRecordTypeId('API_Request__c', recordTypeName);
        ar.Original_Request__c = jsonReq;
        ar.Method__c = method;
        ar.Success__c = success;
        ar.Detail__c = detail;
        ar.Response_Code__c = res.statusCode;
        ar.Response_Message__c = res.statusMessage;

        ApiRequestController.Wrapper obj = (ApiRequestController.Wrapper) JSON.deserialize(jsonReq, ApiRequestController.Wrapper.class);
        ar.activationDate__c = obj.activationDate;
        ar.biAdditionalInfo__c = obj.biAdditionalInfo;
        ar.biAddress__c = obj.biAddress;
        ar.biCity__c = obj.biCity;
        ar.biCompanyName__c = obj.biCompanyName;
        ar.biCountry__c = obj.biCountry;
        ar.biPostalCode__c = obj.biPostalCode;
        ar.biState__c = obj.biState;
        ar.biVATNumber__c = obj.biVATNumber;
        ar.ccAddress__c = obj.ccAddress;
        ar.ccBillingEmail__c = obj.ccBillingEmail;
        ar.ccCity__c = obj.ccCity;
        ar.ccCountry__c = obj.ccCountry;
        ar.ccPostalCode__c = obj.ccPostalCode;
        ar.ccState__c = obj.ccState;
        ar.company__c = obj.company;
        ar.eventType__c = obj.eventType;
        ar.fullName__c = obj.fullName;
        ar.UserRole__c = obj.UserRole;
        ar.pbOptIn__c = obj.pbOptIn;
        ar.phone__c = obj.phone;
        ar.projectId__c = obj.projectId;
        ar.teamUrl__c = obj.teamUrl;
        ar.trialEndDate__c = obj.trialEndDate;
        ar.userEmail__c = obj.userEmail;
        ar.userEmail1__c = obj.userEmail1;
        ar.userEmail2__c = obj.userEmail2;
        ar.userEmail3__c = obj.userEmail3;
        ar.userEmailsToActivate__c = String.valueOf(obj.userEmailsToActivate);
        ar.userId__c = obj.userId;
        ar.userId1__c = obj.userId1;
        ar.userId2__c = obj.userId2;
        ar.userId3__c = obj.userId3;
        ar.hash__c = obj.hash;
        ar.amountOfUsers__c = obj.amountOfUsers;
        ar.frequency__c = obj.frequency;
        ar.plan__c = obj.plan;
        ar.planVersion__c = obj.planVersion;
        ar.discountValue__c = obj.discountValue;
        ar.discountType__c = obj.discountType;
        ar.discountSubtype__c = obj.discountSubtype;
        ar.discountLength__c = obj.discountLength;
        ar.stripeInvoiceId__c = obj.stripeInvoiceId;
        ar.spaceType__c = obj.spaceType;
        if(obj.billingInfoFlag != null) ar.billingInfoFlag__c = obj.billingInfoFlag;

        insert ar;
    }
  
    public class Wrapper{
        public Datetime activationDate;
        public String biAdditionalInfo;
        public String biAddress;
        public String biCity;
        public String biCompanyName;
        public String biCountry;
        public String biPostalCode;
        public String biState;
        public String biVATNumber;
        public String ccAddress;
        public String ccBillingEmail;
        public String ccCity;
        public String ccCountry;
        public String ccPostalCode;
        public String ccState;
        public String company;
        public String eventType;
        public String fullName;
        public String UserRole;
        public String pbOptIn;
        public String phone;
        public String projectId;
        public String teamUrl;
        public Date trialEndDate;
        public String userEmail;
        public String userEmail1;
        public String userEmail2;
        public String userEmail3;
        public List<String> userEmailsToActivate;
        public String userId;
        public String userId1;
        public String userId2;
        public String userId3;
        public String hash;
        public Integer amountOfUsers;
        public String frequency;
        public String plan;
        public String planVersion;
        public String discountValue;
        public String discountType;
        public String discountSubtype;
        public String discountLength;
        public String stripeInvoiceId;
        public Boolean billingInfoFlag;
        public String spaceType;
    }
}