objects/Asset.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

objects/Contact.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Space_Type__c</fullName>
        <label>Space Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Space_Project_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_PB_ID__c</fullName>
        <externalId>true</externalId>
        <label>User PB ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project_Role__c</fullName>
        <label>Project Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Admin</fullName>
                </value>
                <value>
                    <fullName>Editor</fullName>
                </value>
                <value>
                    <fullName>Contributor</fullName>
                </value>
                <value>
                    <fullName>Viewer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Removed_From_Project_Date__c</fullName>
        <label>Removed From Project Date</label>
        <type>DateTime</type>
    </fields>
</CustomObject>

objects/Contract.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Active__c</fullName>
        <formula>AND(TODAY() &lt;= Contract_End_Date__c, 
TODAY() &gt;=  Contract_Start_Date__c,
NOT(ISPICKVAL(Status, &quot;Draft&quot;)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>ContractsProject</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/IntegrationLog__c.object
<CustomObject>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>IL-{YY}-{MM}-{DD}-{00000}</displayFormat>
        <label>Integration Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Method__c</fullName>
        <label>Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>reactivateTrial</fullName>
                </value>
                <value>
                    <fullName>createTrialLead</fullName>
                </value>
                <value>
                    <fullName>createNewProject</fullName>
                </value>
                <value>
                    <fullName>addNewUser</fullName>
                </value>
                <value>
                    <fullName>removeUser</fullName>
                </value>
                <value>
                    <fullName>changeRole</fullName>
                </value>
                <value>
                    <fullName>freezeUser</fullName>
                </value>
                <value>
                    <fullName>unfreezeUser</fullName>
                </value>
                <value>
                    <fullName>updateProjectName</fullName>
                </value>
                <value>
                    <fullName>updateTrialEndDate</fullName>
                </value>
                <value>
                    <fullName>deleteSpace</fullName>
                </value>
                <value>
                    <fullName>addSubscription</fullName>
                </value>
                <value>
                    <fullName>cancelSubscription</fullName>
                </value>
                <value>
                    <fullName>changePlan</fullName>
                </value>
                <value>
                    <fullName>updateBillingInformation</fullName>
                </value>
                <value>
                    <fullName>updateUserInfo</fullName>
                </value>
                <value>
                    <fullName>updateUserPbOptIn</fullName>
                </value>
                <value>
                    <fullName>eraseFailedLogs</fullName>
                </value>
                <value>
                    <fullName>eraseSuccesfulLogs</fullName>
                </value>
                <value>
                    <fullName>changeUserRole</fullName>
                </value>
                <value>
                    <fullName>disableUser</fullName>
                </value>
                <value>
                    <fullName>activateUser</fullName>
                </value>
                <value>
                    <fullName>updateUserEmail</fullName>
                </value>
                <value>
                    <fullName>updateUserFullName</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Success__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Success</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
</CustomObject>

objects/Lead.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Space_Type__c</fullName>
        <label>Space Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Space_Project_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_PB_ID__c</fullName>
        <externalId>true</externalId>
        <label>User PB ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active_Delete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Space_Type__c</fullName>
        <label>Space Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Space_Project_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Account_Name__c</fullName>
        <description>Lookup to Account</description>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project_PB_ID__c</fullName>
        <description>ID of project from ProductBoardApp</description>
        <externalId>true</externalId>
        <label>Project PB ID</label>
        <length>150</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

objects/Project_User__c.object
<CustomObject>
    <label>Project User</label>
    <nameField>
        <label>Project User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Project Users</relationshipLabel>
        <relationshipName>Project_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Project Users</relationshipLabel>
        <relationshipName>Project_Users</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project_Role__c</fullName>
        <label>Project Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>admin</fullName>
                </value>
                <value>
                    <fullName>editor</fullName>
                </value>
                <value>
                    <fullName>contributor</fullName>
                </value>
                <value>
                    <fullName>viewer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project_PB_ID__c</fullName>
        <formula>Project__r.Project_PB_ID__c</formula>
        <inlineHelpText>Project Productboard ID</inlineHelpText>
        <label>Project PB ID</label>
        <type>Text</type>
    </fields>
</CustomObject>

globalValueSets/Space_Project_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Main</fullName>
    </customValue>
    <customValue>
        <fullName>Standalone Portal</fullName>
    </customValue>
    <customValue>
        <fullName>Starter</fullName>
    </customValue>
    <masterLabel>Space/Project Type</masterLabel>
</GlobalValueSet>

classes/EventsOps.cls
global class EventsOps {

	global class EventInfo {
		webservice String eventType;
		webservice String projectId;
        webservice String userEmail;
		webservice String userId;
		webservice String userRole; 
    }

	webService static String newUserEvent(EventInfo newUserInfo) {
		return addNewUser(newUserInfo);
	}

	webService static String removeUserEvent(EventInfo removeUserInfo) {
		return updateProjectUser(removeUserInfo);
	}

	webService static String changeRoleEvent(EventInfo changeRoleInfo) {
		return updateProjectUser(changeRoleInfo);
	}

	webService static String freezeUserEvent(EventInfo freezeInfo) {
		return updateProjectUser(freezeInfo);
	}

	webService static String unfreezeUserEvent(EventInfo unfreezeInfo) {
		return updateProjectUser(unfreezeInfo);
	}

	// add new user 
	public static String addNewUser(EventInfo info) {
        IntegrationLog__c il = Utils.createIntegrationLog('EventsOps', 'addNewUser', JSON.serialize(info));
        Datetime now = Datetime.now();
        ApiResponseDTO response = new ApiResponseDTO();
        System.Savepoint sp = Database.setSavepoint();

        try{
            String pbNewUserEmail = info.userEmail.toLowerCase();
            Double userId = Double.valueOf(info.userId);

            List<Project__c> existingProjects = [SELECT Account_Name__c, Space_Type__c
                                                    FROM Project__c
                                                    WHERE Project_PB_ID__c = :info.projectId];
            Utils.checkEmptyUniqueList(existingProjects, 'projectId: ' + info.projectId);
            Project__c existingProject = existingProjects[0];
            il.Description__c += '\n- Project found. id: ' + existingProject.Id;
            
            List<Project_User__c> projectUsers = [SELECT Id 
                                                    FROM Project_User__c
                                                    WHERE Project__c = :existingProjects[0].Id AND Contact__r.User_PB_ID__c = :Double.valueOf(info.userId)];

            if(!projectUsers.isEmpty()){
                il.Description__c += '\n- ProjectUser found. count: ' + projectUsers.size();
                Project_User__c projectUser = projectUsers[0];
                ProjectUser_SERV.setValueForProjectUser(projectUser, null, info.userRole, null, null, null, now, 'Current', true);
                update projectUser;
                il.Description__c += '\n- ProjectUser updated. id: ' + projectUser.Id;
            } else {
                // new user lead creation
                Lead newUserLead = Lead_SERV.createOrUpdateTrialUser(existingProjects[0].Space_Type__c, pbNewUserEmail, userId, now, il);
                il.Description__c += '\n- Actual User Lead. id: ' + newUserLead.Id;

                List<Contact> contacts = [SELECT AccountId
                                            FROM Contact
                                            WHERE User_PB_ID__c = :userId];
                il.Description__c += '\n- Contacts found by userId. count: ' + contacts.size();
                if(contacts.isEmpty()){
                    contacts = [SELECT AccountId 
                                FROM Contact
                                WHERE User_PB_ID__c = null AND Email = :pbNewUserEmail];
                    il.Description__c += '\n- Contacts found by email. count: ' + contacts.size();
                }          

                Id accountIdForConversion = existingProject.Account_Name__c;
                Id contactIdForConversion;
                
                if (!contacts.isEmpty()) {
                    Contact contactForConversion = contacts[0];
                    contactForConversion.Removed_From_Project_Date__c = null;
                    contactForConversion.User_PB_ID__c = userId;
                    update contactForConversion;

                    contactIdForConversion = contactForConversion.Id;
                    accountIdForConversion = contactForConversion.AccountId;
                }
                il.Description__c += '\n- Data for conversion. contactId: ' + contactIdForConversion + ', accountId: ' + accountIdForConversion;
                
                Contact newUserContact = Lead_SERV.convertLead(newUserLead, accountIdForConversion, contactIdForConversion);
                il.Description__c += '\n- Contact after conversion. id: ' + newUserContact.Id;

                // new project user creation
                Project_User__c newProjectUser = new Project_User__c();
                ProjectUser_SERV.setValueForProjectUser(newProjectUser, pbNewUserEmail, info.userRole, existingProject, newUserContact, false, now, 'Current', true);
                insert newProjectUser;
                il.Description__c += '\n- New ProjectUser inserted. id: ' + newProjectUser.Id;
            }     

            ApiResponseDTO.createResponse(response, ApiConstants.CODE_SUCCESS, ApiConstants.MSG_SUCCESS_USER_NEW, null, null, null );
        } catch(ProductboardException e) {
            ApiResponseDTO.createResponse(response, e.status, e.getMessage(), il, null, null );
            Database.rollback(sp);
        } catch(Exception e) {
            il.Description__c += '\nFAILED - StackTrace: '+ e.getStackTraceString();
            ApiResponseDTO.createResponse(response, ApiConstants.CODE_FAILED_GENERAL, ApiConstants.MSG_FAILED_GENERAL, il, e.getMessage(), null );
            Database.rollback(sp); 
        } finally { 
            Utils.updateIntegrationLog(il, response);
            ApiRequestController.logApiRequest(JSON.serialize(info), 'EventInfo', il.Success__c, il.Method__c, il.Description__c, response);
        }   

        return JSON.serialize(response);
    }


    public static String updateProjectUser(EventInfo info){
        Integrationlog__c il = Utils.createIntegrationLog('EventsOps', info.eventType, JSON.serialize(info));
        ApiResponseDTO response = new ApiResponseDTO();
        System.Savepoint sp = Database.setSavepoint();

        try{
            // gets existing project, contract, account and asset
            List<Project__c> projects = [SELECT Id
                                        FROM Project__c
                                        WHERE Project_PB_ID__c = :info.projectId];
            Utils.checkEmptyUniqueList(projects, 'projectId: ' + info.projectId);
            Project__c project = projects[0];
            il.Description__c += '\n- Project found. id: ' + project.Id;

            // gets project user
            List<Project_User__c> projectUsers = [SELECT Id 
                                                FROM Project_User__c
                                                WHERE Project__c = :project.Id AND Contact__r.User_PB_ID__c = :Double.valueOf(info.userId)];
            /*temp commented due to inaccureate date - substitue by FORloop
            Utils.checkEmptyUniqueList(projectUsers, '');
            Project_User__c projectUser = projectUsers[0];
            il.Description__c += '\n- ProjectUser found. id: ' + projectUser.id;
            
            if (info.eventType == 'changeUserRole'){
                projectUser.Project_Role__c = info.userRole;
            }else if (info.eventType == 'disableUser' || info.eventType == 'removeUser'){
                projectUser.Active__c = false;
            }else if (info.eventType == 'activateUser'){
                projectUser.Active__c = true;
            }
            update projectUser;
            */
            //temp Substitution start
            if(projectUsers.isEmpty()) {
                String newUserResponse = addNewUser(info);
                il.Description__c += '\n- AddNewUser invoked. response: ' + newUserResponse;
                projectUsers = [SELECT Id 
                                FROM Project_User__c
                                WHERE Project__c = :project.Id AND Contact__r.User_PB_ID__c = :Double.valueOf(info.userId)];
                il.Description__c += '\n- ProjectUser found. count: ' + projectUsers.size();
            }

            String responseMessage;
            for(Project_User__c projectUser : projectUsers){
                il.Description__c += '\n- ProjectUser found. id: ' + projectUser.id;
                
                if (info.eventType == 'changeUserRole'){
                    ProjectUser_SERV.setValueForProjectUser(projectUser, null, info.userRole, null, null, null, null, 'Current', true);
                    responseMessage = ApiConstants.MSG_SUCCESS_USER_CHANGE;
                }else if (info.eventType == 'disableUser'){
                    ProjectUser_SERV.setValueForProjectUser(projectUser, null, null, null, null, null, null, 'Cancelled', false);
                    responseMessage = ApiConstants.MSG_SUCCESS_USER_FREEZE;
                }else if(info.eventType == 'removeUser'){
                    ProjectUser_SERV.setValueForProjectUser(projectUser, null, null, null, null, null, null, 'Cancelled', false);
                    responseMessage = ApiConstants.MSG_SUCCESS_USER_REMOVE;
                }else if (info.eventType == 'activateUser'){
                    ProjectUser_SERV.setValueForProjectUser(projectUser, null, null, null, null, null, null, 'Current', true);
                    responseMessage = ApiConstants.MSG_SUCCESS_USER_UNFREEZE;
                }
            }
            update projectUsers;
            //temp substitution edn
            il.Description__c += '\n- ProjectUser updated.';

            ApiResponseDTO.createResponse(response, ApiConstants.CODE_SUCCESS, responseMessage, null, null, null );
        } catch(ProductboardException e) {
            ApiResponseDTO.createResponse(response, e.status, e.getMessage(), il, null, null );
            Database.rollback(sp);
        } catch(Exception e) {
            il.Description__c += '\nFAILED - StackTrace: '+ e.getStackTraceString();
            ApiResponseDTO.createResponse(response, ApiConstants.CODE_FAILED_GENERAL, ApiConstants.MSG_FAILED_GENERAL, il, e.getMessage(), null );
            Database.rollback(sp); 
        } finally { 
            Utils.updateIntegrationLog(il, response);
            ApiRequestController.logApiRequest(JSON.serialize(info), 'EventInfo', il.Success__c, il.Method__c, il.Description__c, response);
        }  

         return JSON.serialize(response);
    }

}