objects/Contact.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Paying_Customer_A__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is there exist at least one active project user (role doesn&apos;t matter) related to this contact on paying Project</description>
        <label>Paying Customer [A]</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Paying_Customer_A_Last_Update__c</fullName>
        <description>temp. field - chech how the Paying customer has been updated</description>
        <label>Paying Customer [A] Last Update</label>
        <type>TextArea</type>
    </fields>
</CustomObject>

objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active_Delete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF(Current_Backend_Stage__c = &quot;Active Contract&quot; || Current_Backend_Stage__c = &quot;Active Subscription&quot;, 
if(ARR_New__c&gt;0, Current_Backend_Stage__c,
IF(Account_Name__r.Account_ARR__c &gt; 0 ||  Parent_Project__r.ARR_New__c &gt; 0, &quot;Subspace&quot;, 
IF(datevalue( etl_subscription_end_date__c) - today() &gt; 0, &quot;Check Data: 100% Discount?&quot;,&quot;Check Data-Churn?&quot;))),


Case ( Current_Backend_Stage__c,
&quot;Deleted&quot; , IF( Initial_ARR__c &gt; 0, &quot;Churned Customer&quot;,&quot;Deleted&quot;),
&quot;Churned Customer&quot;, If(Isblank( Parent_Project__c ), &quot;Churned Customer&quot;,&quot;Churned Subspace&quot;),
&quot;&quot;,IF(now()- CreatedDate &lt;1, &quot;New&quot;,&quot; - Missing&quot;),
 Current_Backend_Stage__c ))</formula>
        <inlineHelpText>Based on MRR &amp; Backend stage</inlineHelpText>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Deleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Cancelled__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>not correct? Checked for paying active subscriptions</inlineHelpText>
        <label>Cancelled_Delete</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

objects/Project_User__c.object
<CustomObject>
    <label>Project User</label>
    <nameField>
        <label>Project User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Project Users</relationshipLabel>
        <relationshipName>Project_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Project Users</relationshipLabel>
        <relationshipName>Project_Users</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Cancelled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Cancelled</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

classes/updatePayingCustomerOnCurrentContacts.cls
global class updatePayingCustomerOnCurrentContacts implements Database.Batchable<SObject> {
	
	global updatePayingCustomerOnCurrentContacts() {
		
	}
	
	/**
	 * @description gets invoked when the batch job starts
	 * @param context contains the job ID
	 * @returns the record set as a QueryLocator object that will be batched for execution
	 */ 
	global Database.QueryLocator start(Database.BatchableContext context) {
		List<Project_User__c> activePusOnPayingProject =  [select Contact__r.id from Project_User__c WHERE Active__c=true AND Project__r.status__c='Paying' AND Project__r.cancelled__c=false AND Project__r.deleted__c=false];
		List<id> payingContactId = new List<id>();
		for (project_user__c pu : activePusOnPayingProject) {
			payingContactId.add(pu.contact__r.id);
		}
		String query = 'Select Paying_Customer_A__c from contact where id IN :payingContactId AND Paying_Customer_A__c= false';
		return Database.getQueryLocator(query);	
	}

	/**
	 * @description gets invoked when the batch job executes and operates on one batch of records. Contains or calls the main execution logic for the batch job.
	 * @param context contains the job ID
	 * @param scope contains the batch of records to process.
	 */ 
   	global void execute(Database.BatchableContext context, List<Contact> scope) {
		List<Contact> conToUpdate = scope;
	
		for (Contact c : conToUpdate) {
			c.Paying_Customer_A__c = true;	
			c.Paying_Customer_A_Last_Update__c = 'Batch, new value: true ' + Datetime.now();
		}
		update conToUpdate;


	}
	
	/**
	 * @description gets invoked when the batch job finishes. Place any clean up code in this method.
	 * @param context contains the job ID
	 */ 
	global void finish(Database.BatchableContext context) {
		
	}
}