objects/ContractProvisioningWebhookAuthorization__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Authorization for automated space contract provisioning</description>
    <label>ContractProvisioningWebhookAuthorization</label>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type of authorization</description>
        <label>Type</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <description>Value of the authorization field</description>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
</CustomObject>

classes/Webhook.cls
public class Webhook implements HttpCalloutMock {

    public static HttpRequest request;
    public static HttpResponse response;

    public HTTPResponse respond(HTTPRequest req) {
        request = req;
        response = new HttpResponse();
        response.setStatusCode(200);
        return response;
    }

    public static String jsonContent(List<Object> triggerNew, List<Object> triggerOld) {
        String newObjects = '[]';
        if (triggerNew != null) {
            newObjects = JSON.serialize(triggerNew);
        }

        String oldObjects = '[]';
        if (triggerOld != null) {
            oldObjects = JSON.serialize(triggerOld);
        }

        String userId = JSON.serialize(UserInfo.getUserId());

        String content = '{"new": ' + newObjects + ', "old": ' + oldObjects + ', "userId": ' + userId + '}';
        return content;
    }

    @future(callout=true)
    public static void callout(String url, String content) {

        if (Test.isRunningTest()) {
            Test.setMock(HttpCalloutMock.class, new Webhook());
        }

        Http h = new Http();

        String authorizationHeader = [
            SELECT Value__c FROM ContractProvisioningWebhookAuthorization__c WHERE Type__c = 'header' LIMIT 1
        ]?.Value__c;
        if (authorizationHeader == NULL) {
        	authorizationHeader = 'authorizationHeaderNotFound';
    	}
        HttpRequest req = new HttpRequest();
        req.setEndpoint(url);
        req.setMethod('POST');
        req.setHeader('Content-Type', 'application/json');
        req.setHeader('Authorization', authorizationHeader);
        req.setBody(content);

        h.send(req);
    }

}