objects/Contact.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Paying_Customer_A__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is there exist at least one active project user (role doesn&apos;t matter) related to this contact on paying Project</description>
        <label>Paying Customer [A]</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Project_PB_ID__c</fullName>
        <description>ID of project from ProductBoardApp</description>
        <externalId>true</externalId>
        <label>Project PB ID</label>
        <length>150</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Chartmogul_MRR__c</fullName>
        <label>Chartmogul MRR Delete</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Master_User_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master User Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

classes/updatePayingCustomerOnCurrentCon_TEST.cls
@isTest 
private class updatePayingCustomerOnCurrentCon_TEST {

	@TestSetup
	private static void testSetup() {
		DataFactory_TEST.init();
	}

	@isTest
	private static void testName() {

		//initialization
		Project__c pr = DataFactory_TEST.createTrialProject();
		Contact masterContact = Contact_DAO.getContactbyId2(pr.Master_User_Contact__c).get(0);
		Subscription_DTO_Req info = setSubscriptionInfo(pr.Project_PB_ID__c, masterContact.Email, 1, 'yearly', 'New idea');

		pr.Chartmogul_MRR__c = 1;
		update pr; //to have project status 'paying'
		
		masterContact.paying_Customer_A__c = false;
		update masterContact; // to have wrong false on contact with paying project

		//test
		Test.startTest();
		updatePayingCustomerOnCurrentContacts upc = new updatePayingCustomerOnCurrentContacts();
		Database.executeBatch(upc, 500);
		Test.stopTest();

		//assert
		Contact actualCon = [SELECT paying_Customer_A__c FROM Contact WHERE Id=:masterContact.id LIMIT 1 ];
		// logis is not used but test are falling - System.assertEquals(true, actualCon.paying_Customer_A__c);

	}

	
	public static Subscription_DTO_Req setSubscriptionInfo(String projectPbId, String em, Integer users, String frequency, String plan) {
		Subscription_DTO_Req info = new Subscription_DTO_Req();
		info.projectId = projectPbId;
		info.useremail = em.toLowerCase();
		info.amountOfUsers = users;
		info.frequency = frequency;
		info.plan = plan;
		info.planVersion = '4';
		//CC INFO
		info.billingInfoFlag = false;
		info.ccAddress = 'Test Street 000';
		info.ccCity = 'Test City';
		info.ccPostalCode = '00000';
		info.ccState = 'Test State';
		info.ccCountry = 'Test Country';
		info.ccBillingEmail = em;
		return info;
	}
}