objects/Contract.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Active__c</fullName>
        <formula>AND(TODAY() &lt;= Contract_End_Date__c, 
TODAY() &gt;=  Contract_Start_Date__c,
NOT(ISPICKVAL(Status, &quot;Draft&quot;)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>ContractsProject</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cancelled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Cancelled</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active_Delete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Updated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Updated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Cancelled__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>not correct? Checked for paying active subscriptions</inlineHelpText>
        <label>Cancelled_Delete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PB_Account_Searched__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PB Account Searched</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Current_Backend_Stage__c</fullName>
        <externalId>true</externalId>
        <label>Current Backend Stage</label>
        <length>200</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Project_User__c.object
<CustomObject>
    <label>Project User</label>
    <nameField>
        <label>Project User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Project Users</relationshipLabel>
        <relationshipName>Project_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <formula>Contact__r.Email</formula>
        <label>Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Project Users</relationshipLabel>
        <relationshipName>Project_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Project Users</relationshipLabel>
        <relationshipName>Project_Users</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Updated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Updated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Cancelled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Cancelled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>User_Score__c</fullName>
        <defaultValue>0</defaultValue>
        <label>User Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Master_User__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Master User</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>User_Status__c</fullName>
        <label>User Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Current</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project_Role__c</fullName>
        <label>Project Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>admin</fullName>
                </value>
                <value>
                    <fullName>editor</fullName>
                </value>
                <value>
                    <fullName>contributor</fullName>
                </value>
                <value>
                    <fullName>viewer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Added_Date__c</fullName>
        <label>User Added Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Trial_Usage_Score__c</fullName>
        <formula>Lead__r.Trial_Usage_Score__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Trial Usage Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>User_Removed_Date__c</fullName>
        <label>User Removed Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>PB_Account_Searched__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PB Account Searched</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SystemAccScriptUpdated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>SystemAccScriptUpdated</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

classes/ProjectUser_DAO.cls
public class ProjectUser_DAO {

	public static List<Project_User__c> getProjectUsersByLeadEmail(String email) {
		List<Project_User__c> projectUsers = [SELECT Active__c, /*Cancelled__c,*/ CreatedById, CreatedDate, Email__c,
		                                      Id, IsDeleted, LastActivityDate, LastModifiedById, LastModifiedDate,
		                                      LastReferencedDate, LastViewedDate, Lead__c, Master_User__c, Name,
		                                      Project_Role__c, Project__c, SystemModstamp, Trial_Usage_Score__c,
		                                      User_Added_Date__c, User_Removed_Date__c, User_Score__c, User_Status__c, Contact__c
		                                      FROM Project_User__c
		                                      WHERE Name = :email];
		return projectUsers;
	}

	public static List<Project_User__c> getProjectUsersByProjectId(Id projectId) {
		List<Project_User__c> projectUsers = [SELECT Active__c, /*Cancelled__c,*/ CreatedById, CreatedDate, Email__c,
		                                      Id, IsDeleted, LastActivityDate, LastModifiedById, LastModifiedDate,
		                                      LastReferencedDate, LastViewedDate, Lead__c, Master_User__c, Name,
		                                      Project_Role__c, Project__c, SystemModstamp, Trial_Usage_Score__c,
		                                      User_Added_Date__c, User_Removed_Date__c, User_Score__c, User_Status__c, Contact__c
		                                      FROM Project_User__c
		                                      WHERE Project__c = :projectId];
		return projectUsers;
	}

	public static List<Project_User__c> getProjectUsersByProjectId2(Id projectId) {
		List<Project_User__c> projectUsers = [SELECT Active__c, /*Cancelled__c,*/ CreatedById, CreatedDate, Email__c,
		                                      Id, IsDeleted, LastActivityDate, LastModifiedById, LastModifiedDate,
		                                      LastReferencedDate, LastViewedDate, Lead__c, Master_User__c, Name,
		                                      Project_Role__c, Project__c, SystemModstamp, Trial_Usage_Score__c,
		                                      User_Added_Date__c, User_Removed_Date__c, User_Score__c, User_Status__c, Contact__c,
											  PB_Account_Searched__c, Updated__c
		                                      FROM Project_User__c
		                                      WHERE Project__c = :projectId];
		if (projectUsers.isEmpty()) {
			throw new ProductboardException('No Project users were found for project Id: [' + projectId + ']', ApiConstants.CODE_FAILED_RECORD_NOT_FOUND);
		}
		return projectUsers;
	}

	public static List<Project_User__c> getProjectUsersByListOfProjectIds(List<Id> projectIds) {
		List<Project_User__c> projectUsers = [SELECT Active__c, /*Cancelled__c,*/ CreatedById, CreatedDate, Email__c,
		                                      Id, IsDeleted, LastActivityDate, LastModifiedById, LastModifiedDate,
		                                      LastReferencedDate, LastViewedDate, Lead__c, Master_User__c, Name,
		                                      Project_Role__c, Project__c, SystemModstamp, Trial_Usage_Score__c,
		                                      User_Added_Date__c, User_Removed_Date__c, User_Score__c, User_Status__c, Contact__c
		                                      FROM Project_User__c
		                                      WHERE Project__c IN :projectIds];
		if (projectUsers.isEmpty()) {
			throw new ProductboardException('No Project users were found for project Ids: [' + projectIds + ']', ApiConstants.CODE_FAILED_RECORD_NOT_FOUND);
		} 
		return projectUsers;
	}

	public static List<Project_User__c> getProjectUsersWithLimit(Integer pusLimit) {
		List<Project_User__c> projectUsers = [SELECT Active__c, /*Cancelled__c,*/ CreatedById, CreatedDate, Email__c,
		                                      Id, IsDeleted, LastActivityDate, LastModifiedById, LastModifiedDate,
		                                      LastReferencedDate, LastViewedDate, Lead__c, Master_User__c, Name,
		                                      Project_Role__c, Project__c, SystemModstamp, Trial_Usage_Score__c,
		                                      User_Added_Date__c, User_Removed_Date__c, User_Score__c, User_Status__c, Contact__c,
		                                      SystemAccScriptUpdated__c
		                                      FROM Project_User__c
		                                      WHERE Contact__c != null
		                                      //AND Master_User__c = false
		                                      AND Project__c != null
		                                      AND SystemAccScriptUpdated__c = false
		                                      LIMIT :pusLimit];
		if (projectUsers.isEmpty()) {
			throw new ProductboardException('No Project users were found for update.', 1);
		}
		return projectUsers;
	}

	public static List<Project_User__c> getProjectUsersWithLimit(List<Id> ids, Integer pusLimit) {
		List<Project_User__c> projectUsers = [SELECT Active__c, /*Cancelled__c,*/ CreatedById, CreatedDate, Email__c,
		                                      Id, IsDeleted, LastActivityDate, LastModifiedById, LastModifiedDate,
		                                      LastReferencedDate, LastViewedDate, Lead__c, Master_User__c, Name,
		                                      Project_Role__c, Project__c, SystemModstamp, Trial_Usage_Score__c,
		                                      User_Added_Date__c, User_Removed_Date__c, User_Score__c, User_Status__c, Contact__c,
		                                      SystemAccScriptUpdated__c
		                                      FROM Project_User__c
		                                      WHERE Id IN :ids
		                                      LIMIT :pusLimit];
		if (projectUsers.isEmpty()) {
			throw new ProductboardException('No Project users were found for update.', 1);
		}
		return projectUsers;
	}
    /*
	public static List<Project_User__c> getUsersOfPayingProjectByContact(Id conId) {
		List<Project_User__c> pusOfPayingProject = [SELECT Active__c,  CreatedById, CreatedDate, Email__c,
													Id, IsDeleted, LastActivityDate, LastModifiedById, LastModifiedDate,
													LastReferencedDate, LastViewedDate, Lead__c, Master_User__c, Name,
													Project_Role__c, Project__c, SystemModstamp, Trial_Usage_Score__c,
													User_Added_Date__c, User_Removed_Date__c, User_Score__c, User_Status__c, Contact__c
													FROM Project_User__c
													WHERE (Project__r.Current_Backend_Stage__c= 'Active Contract'OR
															Project__r.Current_Backend_Stage__c= 'Active Subscription' OR
															Project__r.Current_Backend_Stage__c= 'Subspace') AND
															Contact__c = :conId AND Active__c = true];
	
		return pusOfPayingProject;
	}
    */


	public static void insertProjectUser(Project_User__c prju) {

		try {
			insert prju;
		}
		catch(DmlException e) {
			throw new ProductboardException('Insert Project User ended with errors: ' + e.getMessage(), ApiConstants.CODE_FAILED_DML_ERROR);
		}
	}

	public static void updateProjectUser(Project_User__c prju) {

		try {
			update prju;
		}
		catch(DmlException e) {
			throw new ProductboardException('Update Project User ended with errors: ' + e.getMessage(), ApiConstants.CODE_FAILED_DML_ERROR);
		}

	}

	public static void updateProjectUserList(List<Project_User__c> prju) {

		try {
			update prju;
		}
		catch(DmlException e) {
			throw new ProductboardException('Update Project User ended with errors: ' + e.getMessage(), ApiConstants.CODE_FAILED_DML_ERROR);
		}

	}


}