objects/Contact.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Paying_Customer_A__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is there exist at least one active project user (role doesn&apos;t matter) related to this contact on paying Project</description>
        <label>Paying Customer [A]</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Paying_Customer_A_Last_Update__c</fullName>
        <description>temp. field - chech how the Paying customer has been updated</description>
        <label>Paying Customer [A] Last Update</label>
        <type>TextArea</type>
    </fields>
</CustomObject>

objects/Contract.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>ContractsProject</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Current_Backend_Stage__c</fullName>
        <externalId>true</externalId>
        <label>Current Backend Stage</label>
        <length>200</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Project_User__c.object
<CustomObject>
    <label>Project User</label>
    <nameField>
        <label>Project User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Project Users</relationshipLabel>
        <relationshipName>Project_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Project Users</relationshipLabel>
        <relationshipName>Project_Users</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

classes/UpdatePayingCustomerOnContact_BATCH.cls
global class UpdatePayingCustomerOnContact_BATCH implements Database.Batchable<SObject> {
	
	private string phase; //phase1 - set all contact to from true to false, phase 2 set paying to TRUE
	private Boolean newValue;

	global UpdatePayingCustomerOnContact_BATCH(string phaseFromTrigger) {
		phase = phaseFromTrigger;
		if(phase == 'phase1'){
			newValue = false;
		} else if(phase == 'phase2'){
			newValue = true;
		}
	}
	
	/**
	 * @description gets invoked when the batch job starts
	 * @param context contains the job ID
	 * @returns the record set as a QueryLocator object that will be batched for execution
	 */ 
	global Database.QueryLocator start(Database.BatchableContext context) {
		String query;

		if(phase == 'phase1'){
		//set all true to false
			query = 'SELECT Paying_Customer_A__c,Paying_Customer_A_Last_Update__c FROM contact WHERE Paying_Customer_A__c = true';
		} else if (phase == 'phase2'){
		//change paying to true
			List<Project_User__c> activePusOnPayingProject = [SELECT Contact__r.id 
															FROM Project_User__c 
															WHERE (Project__r.Current_Backend_Stage__c = 'Active Contract' OR
																	Project__r.Current_Backend_Stage__c = 'Active Subscription' OR
																	Project__r.Current_Backend_Stage__c = 'Subspace')];
			List<id> payingContactId = new List<id>();
			for (project_user__c pu : activePusOnPayingProject) {
				payingContactId.add(pu.contact__r.id);
			}
			query = 'SELECT Paying_Customer_A__c,Paying_Customer_A_Last_Update__c FROM contact WHERE id IN :payingContactId';
		}

		return Database.getQueryLocator(query);
	}

	/**
	 * @description gets invoked when the batch job executes and operates on one batch of records. Contains or calls the main execution logic for the batch job.
	 * @param context contains the job ID
	 * @param scope contains the batch of records to process.
	 */ 
   	global void execute(Database.BatchableContext context, List<Contact> scope) {
		List<Contact> conToUpdate = scope;
		for (Contact c : conToUpdate) {
			c.Paying_Customer_A__c = newValue;	
			c.Paying_Customer_A_Last_Update__c = 'Batch, New value: ' + newValue + ', TimeStamp: ' + Datetime.now();
		}
		update conToUpdate;

	}
	
	/**
	 * @description gets invoked when the batch job finishes. Place any clean up code in this method.
	 * @param context contains the job ID
	 */ 
	global void finish(Database.BatchableContext context) {
	
	}
}