objects/Contact.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Project_Role__c</fullName>
        <label>Project Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Admin</fullName>
                </value>
                <value>
                    <fullName>Editor</fullName>
                </value>
                <value>
                    <fullName>Contributor</fullName>
                </value>
                <value>
                    <fullName>Viewer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active_Delete</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

objects/Project_User__c.object
<CustomObject>
    <label>Project User</label>
    <nameField>
        <label>Project User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Project Users</relationshipLabel>
        <relationshipName>Project_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Project Users</relationshipLabel>
        <relationshipName>Project_Users</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Master_User__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Master User</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>User_Status__c</fullName>
        <label>User Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Current</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project_Role__c</fullName>
        <label>Project Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>admin</fullName>
                </value>
                <value>
                    <fullName>editor</fullName>
                </value>
                <value>
                    <fullName>contributor</fullName>
                </value>
                <value>
                    <fullName>viewer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Added_Date__c</fullName>
        <label>User Added Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>User_Removed_Date__c</fullName>
        <label>User Removed Date</label>
        <type>DateTime</type>
    </fields>
</CustomObject>

classes/ProjectUser_SERV.cls
public class ProjectUser_SERV {

	public static void setValueForProjectUser(Project_User__c projectUser,
												String userEmail,
												String role,
												Project__c project,
												Contact userContact,
												Boolean isMaster,
												Datetime now,
												String userStatus,
												Boolean isActive
	) {

		if(userEmail != null) projectUser.Name = userEmail;
		if(role != null) projectUser.Project_Role__c = role;
		if(project != null) projectUser.Project__c = project.Id;
		if(userContact != null) projectUser.Contact__c = userContact.Id;
		if(isActive != null) projectUser.Active__c = isActive;
		if(userStatus != null) projectUser.User_Status__c = userStatus;
		if(now != null) projectUser.User_Added_Date__c = now;
		if(isMaster != null) projectUser.Master_User__c = isMaster;
		if(userStatus == 'Cancelled') projectUser.User_Removed_Date__c = now;
		if(userStatus == 'Current') projectUser.User_Removed_Date__c = null;
	}

}