objects/Contact.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Trial_End_Date__c</fullName>
        <label>Trial End Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

objects/IntegrationLog__c.object
<CustomObject>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>IL-{YY}-{MM}-{DD}-{00000}</displayFormat>
        <label>Integration Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunity</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Trial_End_Date__c</fullName>
        <formula>If( IsPickVal(Type ,&quot;New Business&quot;) &amp;&amp;  Not(Contains(Project__r.Name ,&quot;Placeholder&quot;)), Project__r.Trial_End_Date__c ,Null)</formula>
        <inlineHelpText>Lookup to Project Trial End Date for New Business Opportunities (Excludes Placeholder Project)</inlineHelpText>
        <label>Trial End Date</label>
        <type>Date</type>
    </fields>
    <recordTypes>
        <fullName>Self_Service</fullName>
        <active>true</active>
        <businessProcess>Self Service</businessProcess>
        <description>Non Sales Opportunities</description>
        <label>Self Service</label>
    </recordTypes>
</CustomObject>

objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active_Delete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Team_URL__c</fullName>
        <description>URL of project website</description>
        <label>Team URL</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Trial_End_Date__c</fullName>
        <label>Trial End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Master_User_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master User Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

classes/ProjectOps_SERV.cls
public class ProjectOps_SERV {
	public static void updateProjectName(String newProjectName, String projectId, IntegrationLog__c il) {
		if (newProjectName == null || projectId == null) {
			il.Description__c += '\nFAILED - Invalid parameters';
			throw new ProductboardException(ApiConstants.MSG_FAILED_PARAMETERS, ApiConstants.CODE_FAILED_PARAMETERS);
		} else {
			Project__c existingProject = Project_DAO.getProjectByPBIdWithExc(projectId);
			il.Description__c += '\n- Project found. id: ' + existingProject.Id;
			existingProject.Name = newProjectName + '.productboard.com';
			existingProject.Team_URL__c = newProjectName + '.productboard.com';
			update existingProject;
			il.Description__c += '\n- Project updated.';
		}
	}

	public static void updateTrialEndDate(Date trialEndDate, String projectId, IntegrationLog__c il) {
		Project__c existingProject = Project_DAO.getProjectByPBIdWithExc(projectId);
		il.Description__c += '\n- Project found. id: ' + existingProject.Id;
		Contact existingContact = Contact_DAO.getContactbyId2(existingProject.Master_User_Contact__c)[0];
		il.Description__c += '\n- Contact found. id: ' + existingContact.Id;
		List<Opportunity> existingOpportunities = Opportunity_DAO.getOpenOpportunitiesByProjectId(existingProject.id);
		il.Description__c += '\n- Opportunity found. count: ' + existingOpportunities.size();

		existingContact.Trial_End_Date__c = trialEndDate;
		existingProject.Trial_End_Date__c = trialEndDate;
		if (trialEndDate != null) {
			existingProject.Active__c = true;
		}

		update existingProject;
		il.Description__c += '\n- Project updated.';
		update existingContact;
		il.Description__c += '\n- Contact updated.';

		if (trialEndDate != null) {
			Opportunity opp = new Opportunity();
			if (!existingOpportunities.isEmpty()) {
				opp = getProjectOpportunity(existingOpportunities);
				il.Description__c += '\n- Existing opportunity. id: ' + opp.id;
			} else {
				opp.Project__c = existingProject.Id;
				opp.AccountId = existingContact.AccountId;
				opp.CloseDate = trialEndDate;
				opp.RecordTypeId = OpportunityRecordTypes.self_service;
				opp.Type = 'New Business';
				opp.Name = existingContact.Name + ', ' + Datetime.now();
				opp.StageName = 'Free Trial';
				insert opp;
				il.Description__c += '\n- New Opportunity created. id: ' + opp.Id;
			}
		}
	}

	public static Opportunity getProjectOpportunity(List<Opportunity> opps) {
		Id techUserId = [SELECT Id FROM User WHERE UserName LIKE 'technical-pb@enehano.cz%'].Id;
		Opportunity opp = new Opportunity();
		for (integer i = 0; i < opps.size(); i++) {
			if (i == opps.size() - 1) {
				opp = opps[i];
			} else {
				if (opps[i].OwnerId != techUserId) {
					opp = opps[i];
				}
			}
		}
		return opp;
	}
}