objects/Contact.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Space_Type__c</fullName>
        <label>Space Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Space_Project_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_PB_ID__c</fullName>
        <externalId>true</externalId>
        <label>User PB ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Trial_Source__c</fullName>
        <label>Trial Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Trial Request</fullName>
                </value>
                <value>
                    <fullName>Trial Owner</fullName>
                </value>
                <value>
                    <fullName>Trial User</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Portal_Source__c</fullName>
        <label>Portal Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Portal_Source</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Starter_Source__c</fullName>
        <label>Starter Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Starter_Source</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Trial_End_Date__c</fullName>
        <label>Trial End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Trial_Request_DT__c</fullName>
        <label>Trial Request Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Portal_Request_DT__c</fullName>
        <label>Portal Request DT</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Starter_Request_DT__c</fullName>
        <label>Starter Request DT</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Starter_Activation_DT__c</fullName>
        <label>Starter Activation DT</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Legacy_Lead_Source_March_2019__c</fullName>
        <description>Since LeadSource field is populated by Marketo, a value in this field is original one before Marketo</description>
        <label>Legacy Lead Source (March 2019)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Account User</fullName>
                </value>
                <value>
                    <fullName>Event/Webinar</fullName>
                </value>
                <value>
                    <fullName>Google AdWords</fullName>
                </value>
                <value>
                    <fullName>Newsletter</fullName>
                </value>
                <value>
                    <fullName>Paid Ad</fullName>
                </value>
                <value>
                    <fullName>Referral/Partner</fullName>
                </value>
                <value>
                    <fullName>Referral: Existing Customer</fullName>
                </value>
                <value>
                    <fullName>Sales Outbound</fullName>
                </value>
                <value>
                    <fullName>Trade Show/Sponsorships</fullName>
                </value>
                <value>
                    <fullName>Web Sign Up</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Ad - AdWords</fullName>
                </value>
                <value>
                    <fullName>Ad - Facebook</fullName>
                </value>
                <value>
                    <fullName>Ad - LinkedIn</fullName>
                </value>
                <value>
                    <fullName>Ad - Twitter</fullName>
                </value>
                <value>
                    <fullName>Ad - Quora</fullName>
                </value>
                <value>
                    <fullName>Ad - Media Sponsorship</fullName>
                </value>
                <value>
                    <fullName>Ad - Taboola</fullName>
                </value>
                <value>
                    <fullName>Ad - Outbrain</fullName>
                </value>
                <value>
                    <fullName>Content - Case Study</fullName>
                </value>
                <value>
                    <fullName>Content - eBook</fullName>
                </value>
                <value>
                    <fullName>Content - One Pager</fullName>
                </value>
                <value>
                    <fullName>Content - Webinar</fullName>
                </value>
                <value>
                    <fullName>Content - Video</fullName>
                </value>
                <value>
                    <fullName>Content - Sweepstakes</fullName>
                </value>
                <value>
                    <fullName>Event - Conference</fullName>
                </value>
                <value>
                    <fullName>Event - Happy Hour</fullName>
                </value>
                <value>
                    <fullName>Prospecting - LinkedIn</fullName>
                </value>
                <value>
                    <fullName>Prospecting - Scraping</fullName>
                </value>
                <value>
                    <fullName>Referral - Client</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

objects/IntegrationLog__c.object
<CustomObject>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>IL-{YY}-{MM}-{DD}-{00000}</displayFormat>
        <label>Integration Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
</CustomObject>

objects/Lead.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Full_Name__c</fullName>
        <label>Full Name</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Space_Type__c</fullName>
        <label>Space Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Space_Project_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_PB_ID__c</fullName>
        <externalId>true</externalId>
        <label>User PB ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Trial_Source__c</fullName>
        <label>Trial Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Trial Request</fullName>
                </value>
                <value>
                    <fullName>Trial User</fullName>
                </value>
                <value>
                    <fullName>Trial Owner</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Portal_Source__c</fullName>
        <label>Portal Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Portal_Source</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Starter_Source__c</fullName>
        <label>Starter Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Starter_Source</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Trial_End_Date__c</fullName>
        <label>Trial End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Trial_Request_DT__c</fullName>
        <description>Datetime when user requests a trial</description>
        <label>Trial Request Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Portal_Request_DT__c</fullName>
        <label>Portal Request DT</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Starter_Request_DT__c</fullName>
        <label>Starter Request DT</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Starter_Activation_DT__c</fullName>
        <label>Starter Activation DT</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Legacy_Lead_Source_March_2019__c</fullName>
        <description>Since LeadSource will be filling by Maketo, This field contains original value of leadSource before Marketo has been implemented</description>
        <label>Legacy Lead Source (March 2019)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Account User</fullName>
                </value>
                <value>
                    <fullName>Event/Webinar</fullName>
                </value>
                <value>
                    <fullName>Google AdWords</fullName>
                </value>
                <value>
                    <fullName>Newsletter</fullName>
                </value>
                <value>
                    <fullName>Paid Ad</fullName>
                </value>
                <value>
                    <fullName>Referral/Partner</fullName>
                </value>
                <value>
                    <fullName>Referral: Existing Customer</fullName>
                </value>
                <value>
                    <fullName>Sales Outbound</fullName>
                </value>
                <value>
                    <fullName>Trade Show/Sponsorships</fullName>
                </value>
                <value>
                    <fullName>Web Sign Up</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Ad - AdWords</fullName>
                </value>
                <value>
                    <fullName>Ad - Facebook</fullName>
                </value>
                <value>
                    <fullName>Ad - LinkedIn</fullName>
                </value>
                <value>
                    <fullName>Ad - Twitter</fullName>
                </value>
                <value>
                    <fullName>Ad - Quora</fullName>
                </value>
                <value>
                    <fullName>Ad - Media Sponsorship</fullName>
                </value>
                <value>
                    <fullName>Ad - Taboola</fullName>
                </value>
                <value>
                    <fullName>Ad - Outbrain</fullName>
                </value>
                <value>
                    <fullName>Content - Case Study</fullName>
                </value>
                <value>
                    <fullName>Content - eBook</fullName>
                </value>
                <value>
                    <fullName>Content - One Pager</fullName>
                </value>
                <value>
                    <fullName>Content - Webinar</fullName>
                </value>
                <value>
                    <fullName>Content - Video</fullName>
                </value>
                <value>
                    <fullName>Content - Sweepstakes</fullName>
                </value>
                <value>
                    <fullName>Event - Conference</fullName>
                </value>
                <value>
                    <fullName>Event - Happy Hour</fullName>
                </value>
                <value>
                    <fullName>Prospecting - LinkedIn</fullName>
                </value>
                <value>
                    <fullName>Prospecting - Scraping</fullName>
                </value>
                <value>
                    <fullName>Referral - Client</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

globalValueSets/Portal_Source.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Portal Request</fullName>
    </customValue>
    <customValue>
        <fullName>Portal Owner</fullName>
    </customValue>
    <customValue>
        <fullName>Portal User</fullName>
    </customValue>
    <masterLabel>Portal Source</masterLabel>
</GlobalValueSet>

globalValueSets/Space_Project_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Main</fullName>
    </customValue>
    <customValue>
        <fullName>Standalone Portal</fullName>
    </customValue>
    <customValue>
        <fullName>Starter</fullName>
    </customValue>
    <masterLabel>Space/Project Type</masterLabel>
</GlobalValueSet>

globalValueSets/Starter_Source.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Starter Request</fullName>
    </customValue>
    <customValue>
        <fullName>Starter Owner</fullName>
    </customValue>
    <customValue>
        <fullName>Starter User</fullName>
    </customValue>
    <masterLabel>Starter Source</masterLabel>
</GlobalValueSet>

classes/Lead_SERV.cls
public class Lead_SERV {
	public static List<Lead> getUnconvertedLeadsByEmailWithoutLeadSource(String email, String legacyLeadSource) {
		List<Lead> leads = Lead_DAO.getUnconvertedLeadsByEmail(email);

		List<Lead> result = new List<Lead>();
		for (Lead lead : leads) {
			if (lead.Legacy_Lead_Source_March_2019__c != null) {
				if (lead.Legacy_Lead_Source_March_2019__c != legacyLeadSource) {
					result.add(lead);
				}
			} else {
				result.add(lead);
			}
		}

		return result;
	}

	public static List<lead> getExistingLeadsByUserId(Double userId) {
		return [
			SELECT
				Trial_Source__c,
				IsConverted,
				Company,
				Email,
				User_PB_ID__c,
				Legacy_Lead_Source_March_2019__c,
				Trial_End_Date__c,
				Trial_Request_DT__c,
				Portal_Request_DT__c,
				Portal_Source__c,
				Space_Type__c,
				Starter_Source__c,
				Starter_Request_DT__c,
				Starter_Activation_DT__c
			FROM Lead
			WHERE User_PB_ID__c = :userId AND IsConverted = FALSE
		];
	}
	public static List<lead> getExistingLeadsByEmail(String email) {
		return [
			SELECT
				Trial_Source__c,
				IsConverted,
				Company,
				Email,
				User_PB_ID__c,
				Legacy_Lead_Source_March_2019__c,
				Trial_End_Date__c,
				Trial_Request_DT__c,
				Portal_Request_DT__c,
				Portal_Source__c,
				Space_Type__c,
				Starter_Source__c,
				Starter_Request_DT__c,
				Starter_Activation_DT__c
			FROM Lead
			WHERE Email = :email AND User_PB_ID__c = NULL AND IsConverted = FALSE
		];
	}

	public static String activateStarterLead(String userId) {
		List<Lead> existingLeads = getExistingLeadsByUserId(Double.valueOf(userId));
		if (existingLeads.size() > 1) {
			throw new ProductboardException(
				'There are multiple Leads associated with the userId ' +
				userId +
				'. Please dedupe the Salesforce data first.'
			);
		} else if (existingLeads.size() < 1) {
			throw new ProductboardException('No Lead associated with the userId ' + userId + ' found.');
		} else {
			Lead lead = existingLeads.get(0);
			lead.Starter_Activation_DT__c = Datetime.now();
			Lead_DAO.updateLead(lead);
			return lead.Id;
		}
	}

	public static List<Contact> getExistingContactsByUserId(Double userId) {
		return [SELECT Id FROM Contact WHERE User_PB_ID__c = :userId];
	}

	public static Lead createOrUpdateTrialRequest(TrialOps.LeadInfo info, Datetime now, IntegrationLog__c il) {
		Lead lead = new Lead();
		String email = info.userEmail.toLowerCase();
		Double userId = Double.valueOf(info.userId);

		if (email == null || email.equals('') || userId == null) {
			il.Description__c += '\nFAILED - Invalid parameters';
			throw new ProductboardException(ApiConstants.MSG_FAILED_GENERAL, ApiConstants.CODE_FAILED_PARAMETERS);
		}

		List<Lead> existingLeads = getExistingLeadsByUserId(userId);
		il.Description__c += '\n- Existing Leads. count: ' + existingLeads.size();

		if (existingLeads.isEmpty()) {
			existingLeads = getExistingLeadsByEmail(email);
			il.Description__c += '\n- Lead found by Email. count: ' + existingLeads.size();
		}

		List<Contact> existingContacts = getExistingContactsByUserId(userId);
		il.Description__c += '\n- Existing Contacts. count: ' + existingContacts.size();

		if (existingContacts.isEmpty()) {
			if (!existingLeads.isEmpty()) {
				lead = existingLeads[0];
				il.Description__c += '\n- Existing Lead. id: ' + lead.id;
			}
			Lead_DAO.upsertLeadRequest(lead, info, now);
			upsert lead;
			il.Description__c += '\n- Lead Upserted. id: ' + lead.id;
		} else {
			il.Description__c += '\n- Existing Contacts. id[0]: ' + existingContacts[0].Id;
		}
		return lead;
	}

	public static Lead createOrUpdateTrialOwner(TrialOps.LeadInfo info, Datetime now, IntegrationLog__c il) {
		Lead lead = new Lead();
		String email = info.userEmail.toLowerCase();
		Double userId = Double.valueOf(info.userId);

		List<Lead> existingLeads = getExistingLeadsByUserId(userId);
		il.Description__c += '\n- Lead found by Id. count: ' + existingLeads.size();
		if (existingLeads.isEmpty()) {
			existingLeads = getExistingLeadsByEmail(email);
			il.Description__c += '\n- Lead found by Email. count: ' + existingLeads.size();
		}

		if (!existingLeads.isEmpty()) {
			lead = existingLeads[0];
			il.Description__c += '\n- Existing lead. id: ' + lead.id;
		}

		Lead_DAO.upsertLeadOwner(lead, info, now);
		upsert lead;
		il.Description__c += '\n- Lead Upserted. id: ' + lead.id;

		return lead;
	}

	public static Lead createOrUpdateTrialUser(String spaceType, String email, Double userId, Datetime now, IntegrationLog__c il) {
		Lead lead = new Lead();
		List<Lead> existingLeads = getExistingLeadsByUserId(userId);
		il.Description__c += '\n- Lead found by Id. count: ' + existingLeads.size();
		if (existingLeads.isEmpty()) {
			existingLeads = getExistingLeadsByEmail(email);
			il.Description__c += '\n- Lead found by Email. count: ' + existingLeads.size();
		}

		if (!existingLeads.isEmpty()) {
			lead = existingLeads.get(0);
			il.Description__c += '\n- Existing lead. id: ' + lead.id;
		}
		Lead_DAO.upsertLeadUser(lead, spaceType, email, userId, now);
		upsert lead;
		il.Description__c += '\n- Lead Upserted. id: ' + lead.id;

		return lead;
	}

	public static void parseLeadFullName(String fullName, Lead lead) {
		// update name

		if (fullName.contains(' ')) {
			if (fullName.substringAfter(' ') == null || fullName.substringAfter(' ').equals('')) {
				lead.LastName = fullName.substringBefore(' ');
			} else {
				lead.FirstName = fullName.substringBefore(' ');
				lead.LastName = fullName.substringAfter(' ');
			}
		} else {
			lead.LastName = fullName;
		}
		lead.Full_Name__c = fullName;
	}

	public static Contact convertLead(Lead l, Id accountId, Id contactId) {
		Contact returnContact;
		if (l.IsConverted == false) {
			Database.LeadConvert ld = new Database.LeadConvert();
			ld.setLeadId(l.Id);
			if (accountId != null)
				ld.setAccountId(accountId);
			if (contactId != null) {
				ld.setContactId(contactId);
			} else {
				List<Contact> existingContacts = Contact_DAO.getContactsByEmail(l.Email);
				if (!existingContacts.isEmpty())
					ld.setContactId(existingContacts[0].Id);
			}
			LeadStatus leadStatus = [SELECT Id, MasterLabel FROM LeadStatus WHERE IsConverted = TRUE LIMIT 1];
			ld.setConvertedStatus(leadStatus.MasterLabel);
			ld.setDoNotCreateOpportunity(true);
			Database.LeadConvertResult Leadconverts = Database.convertLead(ld);

			returnContact = Contact_DAO.getContactbyId2(Leadconverts.getContactId())[0];
		} else {
			returnContact = Contact_DAO.getContactbyId(l.ConvertedContactId)[0];
		}
		return returnContact;
	}

	public static String getSource(String spaceType, String suffix) {
		if (spaceType == 'standalone_portal' || spaceType == 'Standalone Portal') {
			return 'Portal ' + suffix;
		} else if (spaceType == 'starter' || spaceType == 'Starter') {
			return 'Starter ' + suffix;
		} else {
			return 'Trial ' + suffix;
		}
	}
}