objects/Contact.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Space_Type__c</fullName>
        <label>Space Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Space_Project_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Trial_End_Date__c</fullName>
        <label>Trial End Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Space_Type__c</fullName>
        <label>Space Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Space_Project_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Product</description>
        <label>Plan</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_PB_ID__c</fullName>
        <description>ID of project from ProductBoardApp</description>
        <externalId>true</externalId>
        <label>Project PB ID</label>
        <length>150</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Trial_End_Date__c</fullName>
        <label>Trial End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Master_User_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master User Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

globalValueSets/Space_Project_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Main</fullName>
    </customValue>
    <customValue>
        <fullName>Standalone Portal</fullName>
    </customValue>
    <customValue>
        <fullName>Starter</fullName>
    </customValue>
    <masterLabel>Space/Project Type</masterLabel>
</GlobalValueSet>

classes/SubscriptionOpsTest.cls
@isTest
public class SubscriptionOpsTest {
    
    @testSetup static void initsObjects() {
		DataFactory_TEST.init();
	}

	@isTest
	private static void testInitObjects() {
		Test.startTest();
		System.assertEquals(5, [select Id from Product2].size());
		System.assertEquals(15, [select Id from PricebookEntry].size());
		System.assertEquals(2, [select Id from Pricebook2].size());
		Test.stopTest();
	}

	@isTest
	private static void testSubscribeNewIdeaNoDiscountYearly() {
		Project__c pr = DataFactory_TEST.createTrialProject();
		Contact masterContact = Contact_DAO.getContactbyId2(pr.Master_User_Contact__c)[0];

		Test.startTest();
		Subscription_DTO_Req info = DataFactory_TEST.setSubscriptionInfo(pr.Project_PB_ID__c, masterContact.Email, 1, 'yearly', 'New idea');
		String response = SubscriptionOps.addSubscription(info);
        Test.stopTest();
        
        ApiResponseDTO res = (ApiResponseDTO) JSON.deserialize(response, ApiResponseDTO.class);
        System.assertEquals(ApiConstants.CODE_SUCCESS, res.statusCode);
	}

    private static void testCancelSubscriptionYearlyNoDiscount() {
		Project__c pr = DataFactory_TEST.createTrialProject();
		Contact masterContact = Contact_DAO.getContactbyId2(pr.Master_User_Contact__c).get(0);

		
		Subscription_DTO_Req info = DataFactory_TEST.setSubscriptionInfo(pr.Project_PB_ID__c, masterContact.Email, 1, 'yearly', 'New idea');
		String response0 = SubscriptionOps.addSubscription(info);
		
		Test.startTest();
		Subscription_DTO_Req cancelInfo = DataFactory_TEST.setCancelSubscriptionInfo(masterContact.Email, pr.Project_PB_ID__c);
		String response = SubscriptionOps.cancelSubscription(cancelInfo);
        Test.stopTest();
        
        ApiResponseDTO res = (ApiResponseDTO) JSON.deserialize(response, ApiResponseDTO.class);
        System.assertEquals(ApiConstants.CODE_SUCCESS, res.statusCode);
        System.assertEquals(ApiConstants.MSG_SUCCESS_SUBSCRIPTION_CANCELATION, res.statusMessage);
    }
    
    @isTest
    private static void testChangeDowngrade() {
        Project__c pr = DataFactory_TEST.createProjectWithAssetWithDiscount('Startup','yearly', 1, 'credit', null, null, 500, null, null);
        
        Test.startTest();
        Subscription_DTO_Req info = DataFactory_TEST.setChangePlanInfo('yearly', pr.Project_PB_ID__c, 'New idea', '4');
        String response = SubscriptionOps.changePlan(info);
        Test.stopTest();

        ApiResponseDTO res = (ApiResponseDTO) JSON.deserialize(response, ApiResponseDTO.class);
        System.assertEquals(ApiConstants.CODE_SUCCESS, res.statusCode);
        System.assertEquals(ApiConstants.MSG_SUCCESS_SUBSCRIPTION_CHANGE, res.statusMessage);
    }

	@isTest
	private static void testUpgradeToTrial() {
		Project__c pr = DataFactory_TEST.createStarterProject();

		Test.startTest();
		Subscription_DTO_Req info = DataFactory_TEST.setChangePlanInfo('', pr.Project_PB_ID__c, 'Trial', '');
		String response = SubscriptionOps.changePlan(info);
		Test.stopTest();

		ApiResponseDTO res = (ApiResponseDTO) JSON.deserialize(response, ApiResponseDTO.class);
		System.assertEquals(ApiConstants.CODE_SUCCESS, res.statusCode);
		System.assertEquals(ApiConstants.MSG_SUCCESS_SUBSCRIPTION_CHANGE, res.statusMessage);
		pr = [ SELECT  Space_Type__c,
				Master_User_Contact__c,
				Name,
				Product_Name__c,
				Trial_End_Date__c
		FROM Project__c
		WHERE Id = :pr.Id
		];
		System.assertEquals('Main', pr.Space_Type__c);
		System.assertEquals(Datetime.now().addDays(14).date(), pr.Trial_End_Date__c);
	}

	@isTest
	private static void testDowngradeToStarter() {
		Project__c pr = DataFactory_TEST.createTrialProject();

		Test.startTest();
		Subscription_DTO_Req info = DataFactory_TEST.setChangePlanInfo('', pr.Project_PB_ID__c, 'Starter', '');
		String response = SubscriptionOps.changePlan(info);
		Test.stopTest();

		ApiResponseDTO res = (ApiResponseDTO) JSON.deserialize(response, ApiResponseDTO.class);
		System.assertEquals(ApiConstants.CODE_SUCCESS, res.statusCode);
		System.assertEquals(ApiConstants.MSG_SUCCESS_SUBSCRIPTION_CHANGE, res.statusMessage);

		pr = [ SELECT  Space_Type__c,
						Master_User_Contact__c,
						Name,
						Product_Name__c,
						Trial_End_Date__c
				FROM Project__c
				WHERE Id = :pr.Id
		];
		System.assertEquals('Starter', pr.Space_Type__c);
		System.assertEquals(null, pr.Trial_End_Date__c);
	}

}