objects/IntegrationLog__c.object
<CustomObject>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>IL-{YY}-{MM}-{DD}-{00000}</displayFormat>
        <label>Integration Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>TrialOps</fullName>
                </value>
                <value>
                    <fullName>UpdateProjectName</fullName>
                </value>
                <value>
                    <fullName>UpdateTrialEndDate</fullName>
                </value>
                <value>
                    <fullName>DeleteProject</fullName>
                </value>
                <value>
                    <fullName>SubscriptionOps</fullName>
                </value>
                <value>
                    <fullName>UpdateBillingInformation</fullName>
                </value>
                <value>
                    <fullName>EventsOps</fullName>
                </value>
                <value>
                    <fullName>UpdateUserFullName</fullName>
                </value>
                <value>
                    <fullName>UpdateUserEmail</fullName>
                </value>
                <value>
                    <fullName>UserOps</fullName>
                </value>
                <value>
                    <fullName>ProjectOps</fullName>
                </value>
                <value>
                    <fullName>EraseOldIntegrationLogs</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Method__c</fullName>
        <label>Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>reactivateTrial</fullName>
                </value>
                <value>
                    <fullName>createTrialLead</fullName>
                </value>
                <value>
                    <fullName>createNewProject</fullName>
                </value>
                <value>
                    <fullName>addNewUser</fullName>
                </value>
                <value>
                    <fullName>removeUser</fullName>
                </value>
                <value>
                    <fullName>changeRole</fullName>
                </value>
                <value>
                    <fullName>freezeUser</fullName>
                </value>
                <value>
                    <fullName>unfreezeUser</fullName>
                </value>
                <value>
                    <fullName>updateProjectName</fullName>
                </value>
                <value>
                    <fullName>updateTrialEndDate</fullName>
                </value>
                <value>
                    <fullName>deleteSpace</fullName>
                </value>
                <value>
                    <fullName>addSubscription</fullName>
                </value>
                <value>
                    <fullName>cancelSubscription</fullName>
                </value>
                <value>
                    <fullName>changePlan</fullName>
                </value>
                <value>
                    <fullName>updateBillingInformation</fullName>
                </value>
                <value>
                    <fullName>updateUserInfo</fullName>
                </value>
                <value>
                    <fullName>updateUserPbOptIn</fullName>
                </value>
                <value>
                    <fullName>eraseFailedLogs</fullName>
                </value>
                <value>
                    <fullName>eraseSuccesfulLogs</fullName>
                </value>
                <value>
                    <fullName>changeUserRole</fullName>
                </value>
                <value>
                    <fullName>disableUser</fullName>
                </value>
                <value>
                    <fullName>activateUser</fullName>
                </value>
                <value>
                    <fullName>updateUserEmail</fullName>
                </value>
                <value>
                    <fullName>updateUserFullName</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Success__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Success</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Response_Code__c</fullName>
        <label>Response Code</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Response_Message__c</fullName>
        <label>Response Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Method_Parameters__c</fullName>
        <label>Method Parameters</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
</CustomObject>

classes/Utils.cls
public class Utils {
    
    public static Id getRecordTypeId(String objectName, String recordTypeName) {
        return Schema.getGlobalDescribe().get(objectName).getDescribe().getRecordTypeInfosByName().get(recordTypeName).getRecordTypeId();
    }

    public static IntegrationLog__c createIntegrationLog(String className, String methodName, String jsonRequest){
        IntegrationLog__c il = new IntegrationLog__c();
        il.Class__c = className;
        il.Method__c = methodName;
        il.Success__c = false;
        il.Description__c = '' ;
        il.Method_Parameters__c = jsonRequest;
        insert il;
        return il;
    }

    public static void updateIntegrationLog(IntegrationLog__c il, ApiResponseDTO response){
        if(response.statusCode == 200) il.Success__c = true;
        il.Response_Message__c = response.statusMessage;
        il.Response_Code__c = response.statusCode;
        update il;
    }
    public static void updateIntegrationLog(IntegrationLog__c il, ApiResponse response){
        if(response.statusCode == 200) il.Success__c = true;
        il.Response_Message__c = response.statusMessage;
        il.Response_Code__c = response.statusCode;
        update il;
    }

    public static void checkEmptyList(List<SObject> objList, String errorMessageAppendix){
		if(objList.isEmpty()) throw new ProductboardException(objList.getSObjectType().getDescribe().getLabel() + ' was not found.' + errorMessageAppendix, ApiConstants.CODE_FAILED_RECORD_NOT_FOUND);
    }
    
    public static void checkEmptyUniqueList(List<SObject> objList, String errorMessageAppendix){
        if(objList.isEmpty()) throw new ProductboardException(objList.getSObjectType().getDescribe().getLabel() + ' was not found.' + errorMessageAppendix, ApiConstants.CODE_FAILED_RECORD_NOT_FOUND);
        if(objList.size() > 1) throw new ProductboardException('More '  + objList.getSObjectType().getDescribe().getLabelPlural() + ' were found.' + errorMessageAppendix, ApiConstants.CODE_FAILED_MORE_RECORDS_FOUND);
	}
}