objects/IntegrationLog__c.object
<CustomObject>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>IL-{YY}-{MM}-{DD}-{00000}</displayFormat>
        <label>Integration Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>TrialOps</fullName>
                </value>
                <value>
                    <fullName>UpdateProjectName</fullName>
                </value>
                <value>
                    <fullName>UpdateTrialEndDate</fullName>
                </value>
                <value>
                    <fullName>DeleteProject</fullName>
                </value>
                <value>
                    <fullName>SubscriptionOps</fullName>
                </value>
                <value>
                    <fullName>UpdateBillingInformation</fullName>
                </value>
                <value>
                    <fullName>EventsOps</fullName>
                </value>
                <value>
                    <fullName>UpdateUserFullName</fullName>
                </value>
                <value>
                    <fullName>UpdateUserEmail</fullName>
                </value>
                <value>
                    <fullName>UserOps</fullName>
                </value>
                <value>
                    <fullName>ProjectOps</fullName>
                </value>
                <value>
                    <fullName>EraseOldIntegrationLogs</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Method__c</fullName>
        <label>Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>reactivateTrial</fullName>
                </value>
                <value>
                    <fullName>createTrialLead</fullName>
                </value>
                <value>
                    <fullName>createNewProject</fullName>
                </value>
                <value>
                    <fullName>addNewUser</fullName>
                </value>
                <value>
                    <fullName>removeUser</fullName>
                </value>
                <value>
                    <fullName>changeRole</fullName>
                </value>
                <value>
                    <fullName>freezeUser</fullName>
                </value>
                <value>
                    <fullName>unfreezeUser</fullName>
                </value>
                <value>
                    <fullName>updateProjectName</fullName>
                </value>
                <value>
                    <fullName>updateTrialEndDate</fullName>
                </value>
                <value>
                    <fullName>deleteSpace</fullName>
                </value>
                <value>
                    <fullName>addSubscription</fullName>
                </value>
                <value>
                    <fullName>cancelSubscription</fullName>
                </value>
                <value>
                    <fullName>changePlan</fullName>
                </value>
                <value>
                    <fullName>updateBillingInformation</fullName>
                </value>
                <value>
                    <fullName>updateUserInfo</fullName>
                </value>
                <value>
                    <fullName>updateUserPbOptIn</fullName>
                </value>
                <value>
                    <fullName>eraseFailedLogs</fullName>
                </value>
                <value>
                    <fullName>eraseSuccesfulLogs</fullName>
                </value>
                <value>
                    <fullName>changeUserRole</fullName>
                </value>
                <value>
                    <fullName>disableUser</fullName>
                </value>
                <value>
                    <fullName>activateUser</fullName>
                </value>
                <value>
                    <fullName>updateUserEmail</fullName>
                </value>
                <value>
                    <fullName>updateUserFullName</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Success__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Success</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Method_Parameters__c</fullName>
        <label>Method Parameters</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
</CustomObject>

classes/EraseOldIntegrationLogs_TEST.cls
@isTest 
private class EraseOldIntegrationLogs_TEST {

    @testSetup
    static void testSetup() {
        List<IntegrationLog__c> ilList = new List<IntegrationLog__c>();
        for (Integer i = 0; i < 3; i++){
            IntegrationLog__c ilSuc = new IntegrationLog__c();
            ilSuc.Class__c = 'EventsOps';
            ilSuc.Success__c = true;
            ilSuc.Method_Parameters__c = 'param1: "' + i + '"';
            ilSuc.Description__c = 'Logs description inserted.';
            ilSuc.Method__c ='addNewUser';
            ilList.add(ilSuc);

            IntegrationLog__c ilFai = new IntegrationLog__c();
            ilFai.Class__c = 'EventsOps';
            ilFai.Success__c = false;
            ilFai.Method_Parameters__c = 'param1: "' + i + '"';
            ilFai.Description__c = 'Logs description inserted.';
            ilFai.Method__c ='addNewUser';
            ilList.add(ilFai);
        }
        insert ilList;
        System.debug('ilList--->' + ilList );
    }

    @isTest
    private static void eraseSuccesfullLogs() {
        System.Test.startTest(); 
        EraseOldIntegrationLogs myBatch = new EraseOldIntegrationLogs(0,true);
        Id batchId = Database.executeBatch(myBatch);
        System.Test.stopTest();
        //zkontrolovat jestli 0 v erase old znamena vsechny.. nebo je problem s casem
        List<IntegrationLog__c> resultSuccesful = [SELECT id,Method__c FROM IntegrationLog__c WHERE Success__c = true];
        List<IntegrationLog__c> resultFailed = [SELECT id,Method__c FROM IntegrationLog__c WHERE Success__c = false];
        System.debug('resultSuccesful--->' + resultSuccesful);
        System.debug('resultFailed--->' + resultFailed);
        System.assertEquals(1, resultSuccesful.size());
        System.assertEquals('eraseSuccesfulLogs', resultSuccesful[0].Method__c);
        System.assertEquals(3, resultFailed.size());
    }

    @isTest
    private static void eraseFailedLogs() {
        System.Test.startTest(); 
        EraseOldIntegrationLogs myBatch = new EraseOldIntegrationLogs(0,false);
        Id batchId = Database.executeBatch(myBatch);
        System.Test.stopTest();

        List<IntegrationLog__c> resultSuccesful = [SELECT id,Method__c FROM IntegrationLog__c WHERE Success__c = true];
        List<IntegrationLog__c> resultFailed = [SELECT id,Method__c FROM IntegrationLog__c WHERE Success__c = false];
        System.debug('resultSuccesful--->' + resultSuccesful);
        System.debug('resultFailed--->' + resultFailed);

        System.assertEquals(0, resultFailed.size());
        System.assertEquals('eraseFailedLogs', resultSuccesful[3].Method__c);
        System.assertEquals(4, resultSuccesful.size());

    }
}