objects/IntegrationLog__c.object
<CustomObject>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>IL-{YY}-{MM}-{DD}-{00000}</displayFormat>
        <label>Integration Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>TrialOps</fullName>
                </value>
                <value>
                    <fullName>UpdateProjectName</fullName>
                </value>
                <value>
                    <fullName>UpdateTrialEndDate</fullName>
                </value>
                <value>
                    <fullName>DeleteProject</fullName>
                </value>
                <value>
                    <fullName>SubscriptionOps</fullName>
                </value>
                <value>
                    <fullName>UpdateBillingInformation</fullName>
                </value>
                <value>
                    <fullName>EventsOps</fullName>
                </value>
                <value>
                    <fullName>UpdateUserFullName</fullName>
                </value>
                <value>
                    <fullName>UpdateUserEmail</fullName>
                </value>
                <value>
                    <fullName>UserOps</fullName>
                </value>
                <value>
                    <fullName>ProjectOps</fullName>
                </value>
                <value>
                    <fullName>EraseOldIntegrationLogs</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Method__c</fullName>
        <label>Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>reactivateTrial</fullName>
                </value>
                <value>
                    <fullName>createTrialLead</fullName>
                </value>
                <value>
                    <fullName>createNewProject</fullName>
                </value>
                <value>
                    <fullName>addNewUser</fullName>
                </value>
                <value>
                    <fullName>removeUser</fullName>
                </value>
                <value>
                    <fullName>changeRole</fullName>
                </value>
                <value>
                    <fullName>freezeUser</fullName>
                </value>
                <value>
                    <fullName>unfreezeUser</fullName>
                </value>
                <value>
                    <fullName>updateProjectName</fullName>
                </value>
                <value>
                    <fullName>updateTrialEndDate</fullName>
                </value>
                <value>
                    <fullName>deleteSpace</fullName>
                </value>
                <value>
                    <fullName>addSubscription</fullName>
                </value>
                <value>
                    <fullName>cancelSubscription</fullName>
                </value>
                <value>
                    <fullName>changePlan</fullName>
                </value>
                <value>
                    <fullName>updateBillingInformation</fullName>
                </value>
                <value>
                    <fullName>updateUserInfo</fullName>
                </value>
                <value>
                    <fullName>updateUserPbOptIn</fullName>
                </value>
                <value>
                    <fullName>eraseFailedLogs</fullName>
                </value>
                <value>
                    <fullName>eraseSuccesfulLogs</fullName>
                </value>
                <value>
                    <fullName>changeUserRole</fullName>
                </value>
                <value>
                    <fullName>disableUser</fullName>
                </value>
                <value>
                    <fullName>activateUser</fullName>
                </value>
                <value>
                    <fullName>updateUserEmail</fullName>
                </value>
                <value>
                    <fullName>updateUserFullName</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Success__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Success</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Method_Parameters__c</fullName>
        <label>Method Parameters</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
</CustomObject>

classes/EraseOldIntegrationLogs.cls
global class EraseOldIntegrationLogs implements Database.Batchable<SObject> {
    
    private Integer erasePeriodInDays; // 0 = today and before
    private Boolean eraseStatus; 
    
    global EraseOldIntegrationLogs(Integer periodInDays, boolean successStatus) {
        erasePeriodInDays = periodInDays;
        eraseStatus = successStatus;
    }
    
    /**
     * @description gets invoked when the batch job starts
     * @param context contains the job ID
     * @returns the record set as a QueryLocator object that will be batched for execution
     */ 
    global Database.QueryLocator start(Database.BatchableContext context) {
        return Database.getQueryLocator('SELECT Id FROM IntegrationLog__c WHERE createdDate <= LAST_N_DAYS:' + erasePeriodInDays + ' AND Success__c = ' + eraseStatus);
    }

    /**
     * @description gets invoked when the batch job executes and operates on one batch of records. Contains or calls the main execution logic for the batch job.
     * @param context contains the job ID
     * @param scope contains the batch of records to process.
     */ 
    global void execute(Database.BatchableContext context, List<IntegrationLog__c> scope) {
        delete scope;
    }
    
    /**
     * @description gets invoked when the batch job finishes. Place any clean up code in this method.
     * @param context contains the job ID
     */ 
    global void finish(Database.BatchableContext context) {
        IntegrationLog__c il = new IntegrationLog__c();
        String method;
        if(eraseStatus) method = 'eraseSuccesfulLogs';
        if(!eraseStatus) method = 'eraseFailedLogs';
        il.Class__c = 'EraseOldIntegrationLogs';
        il.Success__c = true;
        il.Method_Parameters__c = 'erasePeriodInDays: "' + erasePeriodInDays + '"' + '\n' + 'eraseStatus: "' + eraseStatus + '"';
        il.Description__c = 'Logs have been sucessfully erased.';
        il.Method__c = method;
        insert il;
    }
}