objects/IntegrationLog__c.object
<CustomObject>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>IL-{YY}-{MM}-{DD}-{00000}</displayFormat>
        <label>Integration Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
</CustomObject>

objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active_Delete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Deleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Deleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Team_URL__c</fullName>
        <description>URL of project website</description>
        <label>Team URL</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cancelled__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>not correct? Checked for paying active subscriptions</inlineHelpText>
        <label>Cancelled_Delete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Product</description>
        <label>Plan</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Project_User__c.object
<CustomObject>
    <label>Project User</label>
    <nameField>
        <label>Project User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Project Users</relationshipLabel>
        <relationshipName>Project_Users</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Cancelled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Cancelled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>User_Status__c</fullName>
        <label>User Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Current</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

classes/DeleteProject_SERV.cls
public class DeleteProject_SERV {

	public static void markProjectAndPusAsDeleted(Project__c deletedProject, String hash, IntegrationLog__c il) {		
		Product2 projectPlan = null;
		if(deletedProject.Product_Name__c != null) projectPlan = Product2_DAO.getProduct2ById2(deletedProject.Product_Name__c);
		il.Description__c += '\n- ProjectPlan.';
		
		if (projectPlan == null || projectPlan.Name.equals('Trial') || deletedProject.Cancelled__c == true) {
			setProjectAsDeleted(deletedProject, hash, il);
			setProjectUsersAsDeleted(deletedProject, il);
		} else {
            il.Description__c += '\nFAILED - Project is not in Trial or has an active subscription. Project was not deleted!';
            throw new ProductboardException(ApiConstants.MSG_FAILED_PROJECT_NOT_DELETED, ApiConstants.CODE_FAILED_PROJECT_NOT_DELETED);
        }
	}
	
	public static void setProjectAsDeleted(Project__c pr, String hash, IntegrationLog__c il) {
		pr.Deleted__c = true;		
		String oldName = pr.Name.substringBefore('.');		
		pr.Name = oldName + '-deleted-' + hash + '.productboard.com';
		pr.Team_URL__c = oldName + '-deleted-' + hash + '.productboard.com';	
		pr.Active__c = false;
		update pr;
		il.Description__c += '\n- Project marked as deleted.';
	}

	public static void setProjectUsersAsDeleted(Project__c pr, IntegrationLog__c il) {
		List<Project_User__c> projectUsers = ProjectUser_DAO.getProjectUsersByProjectId2(pr.Id);
		List<Project_User__c> puList = new List<Project_User__c>();
		for (Project_User__c pu : projectUsers) {
			pu.User_Status__c = 'Deleted';
			pu.Active__c = false;
			puList.add(pu);
			il.Description__c += '\n- ProjectUser to delete. id: ' + pu.Id;
		}
		update puList;
		il.Description__c += '\n- ProjectUsers marked as deleted';
	}

	

}