objects/IntegrationLog__c.object
<CustomObject>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>IL-{YY}-{MM}-{DD}-{00000}</displayFormat>
        <label>Integration Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Method__c</fullName>
        <label>Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>reactivateTrial</fullName>
                </value>
                <value>
                    <fullName>createTrialLead</fullName>
                </value>
                <value>
                    <fullName>createNewProject</fullName>
                </value>
                <value>
                    <fullName>addNewUser</fullName>
                </value>
                <value>
                    <fullName>removeUser</fullName>
                </value>
                <value>
                    <fullName>changeRole</fullName>
                </value>
                <value>
                    <fullName>freezeUser</fullName>
                </value>
                <value>
                    <fullName>unfreezeUser</fullName>
                </value>
                <value>
                    <fullName>updateProjectName</fullName>
                </value>
                <value>
                    <fullName>updateTrialEndDate</fullName>
                </value>
                <value>
                    <fullName>deleteSpace</fullName>
                </value>
                <value>
                    <fullName>addSubscription</fullName>
                </value>
                <value>
                    <fullName>cancelSubscription</fullName>
                </value>
                <value>
                    <fullName>changePlan</fullName>
                </value>
                <value>
                    <fullName>updateBillingInformation</fullName>
                </value>
                <value>
                    <fullName>updateUserInfo</fullName>
                </value>
                <value>
                    <fullName>updateUserPbOptIn</fullName>
                </value>
                <value>
                    <fullName>eraseFailedLogs</fullName>
                </value>
                <value>
                    <fullName>eraseSuccesfulLogs</fullName>
                </value>
                <value>
                    <fullName>changeUserRole</fullName>
                </value>
                <value>
                    <fullName>disableUser</fullName>
                </value>
                <value>
                    <fullName>activateUser</fullName>
                </value>
                <value>
                    <fullName>updateUserEmail</fullName>
                </value>
                <value>
                    <fullName>updateUserFullName</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Success__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Success</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
</CustomObject>

classes/UserOps.cls
global class UserOps {

	webService static String updateUserPbOptIn(UserOps_DTO_req info) {
        IntegrationLog__c il = Utils.createIntegrationLog('UserOps', 'updateUserPbOptIn', JSON.serialize(info)); 
        ApiResponseDTO response = new ApiResponseDTO();
        System.Savepoint sp = Database.setSavepoint();

        try {
            if (info.pbOptIn == null || info.userId == null) {
                il.Description__c += '\nFAILED - Invalid parameters';
                throw new ProductboardException(ApiConstants.MSG_FAILED_PARAMETERS, ApiConstants.CODE_FAILED_PARAMETERS);
            }
			UserOps_SERV.updateUserPbOptIn(info.fullName, Double.valueOf(info.userId), info.pbOptIn, il);
            ApiResponseDTO.createResponse(response, ApiConstants.CODE_SUCCESS, ApiConstants.MSG_SUCCESS_USER_OPT_IN_UPDATE, null, null, null );
        } catch(ProductboardException e) {
            ApiResponseDTO.createResponse(response, e.status, e.getMessage(), il, null, null );
            Database.rollback(sp);
        } catch(Exception e) {
            il.Description__c += '\nFAILED - StackTrace: '+ e.getStackTraceString();
            ApiResponseDTO.createResponse(response, ApiConstants.CODE_FAILED_GENERAL, ApiConstants.MSG_FAILED_GENERAL, il, e.getMessage(), null );
            Database.rollback(sp); 
        } finally { 
            Utils.updateIntegrationLog(il, response);
            ApiRequestController.logApiRequest(JSON.serialize(info), 'UserOps_DTO_req', il.Success__c, il.Method__c, il.Description__c, response);
        }   

        return JSON.serialize(response);
    }
    
    webService static String updateUserFullName(UserOps_DTO_req info) {
        IntegrationLog__c il = Utils.createIntegrationLog('UserOps', 'updateUserFullName', JSON.serialize(info)); 
        ApiResponseDTO response = new ApiResponseDTO();
        System.Savepoint sp = Database.setSavepoint();

		try {
            if (info.fullName == null || info.userId == null) {
                il.Description__c += '\nFAILED - Invalid parameters';
                throw new ProductboardException(ApiConstants.MSG_FAILED_PARAMETERS, ApiConstants.CODE_FAILED_PARAMETERS);
            }
		    UserOps_SERV.updateUserFullName(info.fullName, Double.valueOf(info.userId), il);
            ApiResponseDTO.createResponse(response, ApiConstants.CODE_SUCCESS, ApiConstants.MSG_SUCCESS_USER_NAME_UPDATE, null, null, null );
	    } catch(ProductboardException e) {
            ApiResponseDTO.createResponse(response, e.status, e.getMessage(), il, null, null );
            Database.rollback(sp);
        } catch(Exception e) {
            il.Description__c += '\nFAILED - StackTrace: '+ e.getStackTraceString();
            ApiResponseDTO.createResponse(response, ApiConstants.CODE_FAILED_GENERAL, ApiConstants.MSG_FAILED_GENERAL, il, e.getMessage(), null );
            Database.rollback(sp); 
        } finally { 
            Utils.updateIntegrationLog(il, response);
            ApiRequestController.logApiRequest(JSON.serialize(info), 'UserOps_DTO_req', il.Success__c, il.Method__c, il.Description__c, response);
        }    

        return JSON.serialize(response);
    }

    webService static String updateUserEmail(UserOps_DTO_req info) {
        IntegrationLog__c il = Utils.createIntegrationLog('UserOps', 'updateUserEmail', JSON.serialize(info)); 
        ApiResponseDTO response = new ApiResponseDTO();
        System.Savepoint sp = Database.setSavepoint();

        try {
            if (info.userEmail == null || info.userId == null) {
                il.Description__c += '\nFAILED - Invalid parameters';
                throw new ProductboardException(ApiConstants.MSG_FAILED_PARAMETERS, ApiConstants.CODE_FAILED_PARAMETERS);
            }
            UserOps_SERV.updateUserEmail(info.userEmail.toLowerCase(), Double.valueOf(info.userId), il);
            ApiResponseDTO.createResponse(response, ApiConstants.CODE_SUCCESS, ApiConstants.MSG_SUCCESS_USER_EMAIL_UPDATE, null, null, null );
        } catch(ProductboardException e) {
            ApiResponseDTO.createResponse(response, e.status, e.getMessage(), il, null, null );
            Database.rollback(sp);
        } catch(Exception e) {
            il.Description__c += '\nFAILED - StackTrace: '+ e.getStackTraceString();
            ApiResponseDTO.createResponse(response, ApiConstants.CODE_FAILED_GENERAL, ApiConstants.MSG_FAILED_GENERAL, il, e.getMessage(), null );
            Database.rollback(sp); 
        } finally { 
            Utils.updateIntegrationLog(il, response);
            ApiRequestController.logApiRequest(JSON.serialize(info), 'UserOps_DTO_req', il.Success__c, il.Method__c, il.Description__c, response);
        }   
        return JSON.serialize(response);
    }
}