objects/IntegrationLog__c.object
<CustomObject>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>IL-{YY}-{MM}-{DD}-{00000}</displayFormat>
        <label>Integration Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Method__c</fullName>
        <label>Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>reactivateTrial</fullName>
                </value>
                <value>
                    <fullName>createTrialLead</fullName>
                </value>
                <value>
                    <fullName>createNewProject</fullName>
                </value>
                <value>
                    <fullName>addNewUser</fullName>
                </value>
                <value>
                    <fullName>removeUser</fullName>
                </value>
                <value>
                    <fullName>changeRole</fullName>
                </value>
                <value>
                    <fullName>freezeUser</fullName>
                </value>
                <value>
                    <fullName>unfreezeUser</fullName>
                </value>
                <value>
                    <fullName>updateProjectName</fullName>
                </value>
                <value>
                    <fullName>updateTrialEndDate</fullName>
                </value>
                <value>
                    <fullName>deleteSpace</fullName>
                </value>
                <value>
                    <fullName>addSubscription</fullName>
                </value>
                <value>
                    <fullName>cancelSubscription</fullName>
                </value>
                <value>
                    <fullName>changePlan</fullName>
                </value>
                <value>
                    <fullName>updateBillingInformation</fullName>
                </value>
                <value>
                    <fullName>updateUserInfo</fullName>
                </value>
                <value>
                    <fullName>updateUserPbOptIn</fullName>
                </value>
                <value>
                    <fullName>eraseFailedLogs</fullName>
                </value>
                <value>
                    <fullName>eraseSuccesfulLogs</fullName>
                </value>
                <value>
                    <fullName>changeUserRole</fullName>
                </value>
                <value>
                    <fullName>disableUser</fullName>
                </value>
                <value>
                    <fullName>activateUser</fullName>
                </value>
                <value>
                    <fullName>updateUserEmail</fullName>
                </value>
                <value>
                    <fullName>updateUserFullName</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Success__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Success</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
</CustomObject>

objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Deleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Deleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
</CustomObject>

classes/ProjectOps.cls
global class ProjectOps {
	global class ProjectInfo {
		webService String teamUrl;
		webService String projectId;
		webService Date trialEndDate;
		webService String hash;
	}

	webService static String updateProjectName(ProjectInfo info) {
		IntegrationLog__c il = Utils.createIntegrationLog('ProjectOps', 'updateProjectName', JSON.serialize(info));
		ApiResponseDTO response = new ApiResponseDTO();
		System.Savepoint sp = Database.setSavepoint();

		try {
			ProjectOps_SERV.updateProjectName(info.teamUrl, info.projectId, il);
			ApiResponseDTO.createResponse(
				response,
				ApiConstants.CODE_SUCCESS,
				ApiConstants.MSG_SUCCESS_PROJECT_NAME_UPDATE,
				null,
				null,
				null
			);
		} catch (ProductboardException e) {
			ApiResponseDTO.createResponse(response, e.status, e.getMessage(), il, null, null);
			Database.rollback(sp);
		} catch (Exception e) {
			il.Description__c += '\nFAILED - StackTrace: ' + e.getStackTraceString();
			ApiResponseDTO.createResponse(
				response,
				ApiConstants.CODE_FAILED_GENERAL,
				ApiConstants.MSG_FAILED_GENERAL,
				il,
				e.getMessage(),
				null
			);
			Database.rollback(sp);
		} finally {
			Utils.updateIntegrationLog(il, response);
			ApiRequestController.logApiRequest(
				JSON.serialize(info),
				'ProjectInfo',
				il.Success__c,
				il.Method__c,
				il.Description__c,
				response
			);
		}
		return JSON.serialize(response);
	}

	webService static String deleteSpace(ProjectInfo info) {
		IntegrationLog__c il = Utils.createIntegrationLog('ProjectOps', 'deleteSpace', JSON.serialize(info));
		ApiResponseDTO response = new ApiResponseDTO();
		System.Savepoint sp = Database.setSavepoint();

		try {
			Project__c deletedProject = Project_DAO.getProjectByPBIdWithExc(info.projectId);
			il.Description__c += '\n- Project found. id: ' + deletedProject.Id;

			if (deletedProject.Deleted__c) {
				il.Description__c += '\n- Project has been already deleted.';
			} else {
				DeleteProject_SERV.markProjectAndPusAsDeleted(deletedProject, info.hash, il);
			}
			ApiResponseDTO.createResponse(response, ApiConstants.CODE_SUCCESS, ApiConstants.MSG_SUCCESS_PROJECT_DELETE, null, null, null);
		} catch (ProductboardException e) {
			ApiResponseDTO.createResponse(response, e.status, e.getMessage(), il, null, null);
			Database.rollback(sp);
		} catch (Exception e) {
			il.Description__c += '\nFAILED - StackTrace: ' + e.getStackTraceString();
			ApiResponseDTO.createResponse(
				response,
				ApiConstants.CODE_FAILED_GENERAL,
				ApiConstants.MSG_FAILED_GENERAL,
				il,
				e.getMessage(),
				null
			);
			Database.rollback(sp);
		} finally {
			Utils.updateIntegrationLog(il, response);
			ApiRequestController.logApiRequest(
				JSON.serialize(info),
				'ProjectInfo',
				il.Success__c,
				il.Method__c,
				il.Description__c,
				response
			);
		}

		return JSON.serialize(response);
	}

	webService static String updateTrialEndDate(ProjectInfo info) {
		IntegrationLog__c il = Utils.createIntegrationLog('ProjectOps', 'updateTrialEndDate', JSON.serialize(info));
		ApiResponseDTO response = new ApiResponseDTO();
		System.Savepoint sp = Database.setSavepoint();

		try {
			ProjectOps_SERV.updateTrialEndDate(info.trialEndDate, info.projectId, il);
			ApiResponseDTO.createResponse(
				response,
				ApiConstants.CODE_SUCCESS,
				ApiConstants.MSG_SUCCESS_TRIAL_END_DATE_UPDATE,
				null,
				null,
				null
			);
		} catch (ProductboardException e) {
			ApiResponseDTO.createResponse(response, e.status, e.getMessage(), il, null, null);
			Database.rollback(sp);
		} catch (Exception e) {
			il.Description__c += '\nFAILED - StackTrace: ' + e.getStackTraceString();
			ApiResponseDTO.createResponse(
				response,
				ApiConstants.CODE_FAILED_GENERAL,
				ApiConstants.MSG_FAILED_GENERAL,
				il,
				e.getMessage(),
				null
			);
			Database.rollback(sp);
		} finally {
			Utils.updateIntegrationLog(il, response);
			ApiRequestController.logApiRequest(
				JSON.serialize(info),
				'ProjectInfo',
				il.Success__c,
				il.Method__c,
				il.Description__c,
				response
			);
		}

		return JSON.serialize(response);
	}
}