objects/IntegrationLog__c.object
<CustomObject>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>IL-{YY}-{MM}-{DD}-{00000}</displayFormat>
        <label>Integration Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
</CustomObject>

objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>BI_City__c</fullName>
        <label>BI City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CC_City__c</fullName>
        <label>CC City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BI_State__c</fullName>
        <label>BI State</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CC_State__c</fullName>
        <label>CC State</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BI_Address__c</fullName>
        <label>BI Address</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BI_Country__c</fullName>
        <label>BI Country</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CC_Address__c</fullName>
        <label>CC Address</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CC_Country__c</fullName>
        <label>CC Country</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>BI_VAT_Number__c</fullName>
        <label>BI VAT Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BI_Postal_Code__c</fullName>
        <label>BI Postal Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CC_Postal_Code__c</fullName>
        <label>CC Postal Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BI_Company_Name__c</fullName>
        <label>BI Company Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CC_Billing_Email__c</fullName>
        <label>CC Billing Email</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BI_Additional_Info__c</fullName>
        <label>BI Additional Info</label>
        <length>100</length>
        <type>Text</type>
    </fields>
</CustomObject>

classes/UpdateBillingInformation_SERV.cls
public class UpdateBillingInformation_SERV {
	public static void updateBillingFields(BillingInfo info, IntegrationLog__c il) {
		Project__c existingProject = Project_DAO.getProjectByPBIdWithExc(info.projectId);
		il.Description__c += '\n- Project found. id: ' + existingProject.id;
		existingProject.CC_Address__c = info.ccAddress;
		existingProject.CC_City__c = info.ccCity;
		existingProject.CC_Postal_Code__c = info.ccPostalCode;
		existingProject.CC_State__c = info.ccState;
		existingProject.CC_Country__c = info.ccCountry;
		existingProject.CC_Billing_Email__c = info.ccBillingEmail;
		existingProject.BI_Company_Name__c = info.biCompanyName;
		existingProject.BI_Address__c = info.biAddress;
		existingProject.BI_City__c = info.biCity;
		existingProject.BI_Postal_Code__c = info.biPostalCode;
		existingProject.BI_State__c = info.biState;
		existingProject.BI_Country__c = info.biCountry;
		existingProject.BI_VAT_Number__c = info.biVATNumber;
		existingProject.BI_Additional_Info__c = info.biAdditionalInfo;
		update existingProject;
		il.Description__c += '\n- Project updated.';
	}
}