objects/Lead.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Space_Type__c</fullName>
        <label>Space Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Space_Project_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_PB_ID__c</fullName>
        <externalId>true</externalId>
        <label>User PB ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Trial_Source__c</fullName>
        <label>Trial Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Trial Request</fullName>
                </value>
                <value>
                    <fullName>Trial User</fullName>
                </value>
                <value>
                    <fullName>Trial Owner</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Starter_Activation_DT__c</fullName>
        <label>Starter Activation DT</label>
        <type>DateTime</type>
    </fields>
</CustomObject>

objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Space_Type__c</fullName>
        <label>Space Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Space_Project_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project_PB_ID__c</fullName>
        <description>ID of project from ProductBoardApp</description>
        <externalId>true</externalId>
        <label>Project PB ID</label>
        <length>150</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Master_User_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master User Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Project_User__c.object
<CustomObject>
    <label>Project User</label>
    <nameField>
        <label>Project User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Project Users</relationshipLabel>
        <relationshipName>Project_Users</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User_Score__c</fullName>
        <defaultValue>0</defaultValue>
        <label>User Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project_PB_ID__c</fullName>
        <formula>Project__r.Project_PB_ID__c</formula>
        <inlineHelpText>Project Productboard ID</inlineHelpText>
        <label>Project PB ID</label>
        <type>Text</type>
    </fields>
</CustomObject>

globalValueSets/Space_Project_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Main</fullName>
    </customValue>
    <customValue>
        <fullName>Standalone Portal</fullName>
    </customValue>
    <customValue>
        <fullName>Starter</fullName>
    </customValue>
    <masterLabel>Space/Project Type</masterLabel>
</GlobalValueSet>

classes/TrialOpsTest.cls
@isTest
global class TrialOpsTest {
	@TestSetup
	private static void testSetup() {
		DataFactory_TEST.init();
	}

	@IsTest
	public static void testStarterActivation() {
		TrialOps.LeadInfo leadInfo = new TrialOps.LeadInfo();
		leadInfo.spaceType = 'starter';
		leadInfo.userEmail = 'test@test.test';
		leadInfo.userId = '1';

		Lead lead = new Lead();
		lead.User_PB_ID__c = Double.valueOf(leadInfo.userId);
		lead.Email = leadInfo.userEmail;
		lead.Space_Type__c = leadInfo.spaceType;
		lead.LastName = 'Test';
		lead.Company = 'Test Comp';
		insert lead;

		Test.startTest();
		TrialOps.activateStarterLead(leadInfo);
		Test.stopTest();

		// check master lead
		Lead[] l = [SELECT Id, Email, Starter_Activation_DT__c FROM Lead WHERE Email = 'test@test.test'];
		System.assertEquals(1, l.size());
		System.assertNotEquals(null, l.get(0).Starter_Activation_DT__c, 'Starter activation timestamp should be populated.');
	}

	testMethod static void testTrialOps() {
		TrialOps.LeadInfo leadInfo = new TrialOps.LeadInfo();
		leadInfo.spaceType = 'main';
		leadInfo.userEmail = 'test@test.test';
		leadInfo.userId = '1';
		TrialOps.createTrialLead(leadInfo);

		// check master lead
		Lead[] l = [SELECT Id, Email FROM Lead WHERE Email = 'test@test.test'];
		System.assertEquals(l.size(), 1);

		leadInfo.fullName = 'TestTest';
		leadInfo.phone = '123465798';
		leadInfo.userEmail = 'test@test.test';
		leadInfo.userId = '1';
		leadInfo.trialEndDate = Date.today();
		leadInfo.projectId = '1111111111111111111';
		leadInfo.teamUrl = 'test';
		leadInfo.userEmail1 = 'test1@test1.test';
		leadInfo.userId1 = '111';
		leadInfo.userEmail2 = 'test2@test2.test';
		leadInfo.userId2 = '222';

		TrialOps.createNewProject(leadInfo);

		// check created project
		Project__c[] p = [SELECT Id, Master_User_Lead__c FROM Project__c WHERE Project_PB_ID__c = '1111111111111111111'];
		System.assertEquals(p.size(), 1);

		Project_User__c[] pu = [
			SELECT Id, User_Score__c
			FROM Project_User__c
			WHERE Name IN ('test@test.test', 'test1@test1.test', 'test2@test2.test', 'test3@test3.test')
			ORDER BY Name
		];

		System.assertEquals(pu.size(), 3);
	}

	testMethod static void testTrialOpsExistingUsers() {
		String email = 'test@test.test';
		String userId = GeneralConfig_TEST.TEST_USER_PB_ID;
		Lead newLead = new Lead();
		newLead.Space_Type__c = 'main';
		newLead.Email = email;
		newLead.LastName = 'Not provided';
		newLead.Company = 'Not provided';
		newLead.user_PB_ID__c = double.valueof(userId);
		insert newLead;

		TrialOps.LeadInfo leadInfo = new TrialOps.LeadInfo();
		leadInfo.spaceType = 'main';
		leadInfo.userEmail = email;
		leadInfo.userId = userId;
		TrialOps.createTrialLead(leadInfo);

		// check master lead
		Lead l = [SELECT Trial_Source__c FROM Lead WHERE User_PB_ID__c = :double.valueof(userId)];
		System.assertEquals(l.Trial_Source__c, 'Trial Request');

		leadInfo.fullName = 'Test Test';
		leadInfo.phone = '123465798';
		leadInfo.userEmail = email;
		leadInfo.userId = '1';
		leadInfo.trialEndDate = Date.today();
		leadInfo.projectId = '11111111111111111111';
		leadInfo.teamUrl = 'test';
		leadInfo.userEmail1 = 'test1@test1.test';
		leadInfo.userId1 = '111';

		TrialOps.createNewProject(leadInfo);

		// check created project
		Project__c[] p = [SELECT Id, Master_User_Lead__c FROM Project__c WHERE Project_PB_ID__c = '11111111111111111111'];
		System.assertEquals(p.size(), 1);

		// check created project users
		Project_User__c[] pu = [
			SELECT Id
			FROM Project_User__c
			WHERE Name IN ('test@test.test', 'test1@test1.test', 'test2@test2.test', 'test3@test3.test')
			ORDER BY Name
		];
		System.assertEquals(pu.size(), 2);
	}
}