objects/Opportunity.object
<CustomObject>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunity</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account_Name__c</fullName>
        <formula>Account.Name</formula>
        <label>Account Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_PB_ID__c</fullName>
        <formula>Project__r.Project_PB_ID__c</formula>
        <inlineHelpText>lookup to project PB ID</inlineHelpText>
        <label>Project PB ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trial_End_Date__c</fullName>
        <formula>If( IsPickVal(Type ,&quot;New Business&quot;) &amp;&amp;  Not(Contains(Project__r.Name ,&quot;Placeholder&quot;)), Project__r.Trial_End_Date__c ,Null)</formula>
        <inlineHelpText>Lookup to Project Trial End Date for New Business Opportunities (Excludes Placeholder Project)</inlineHelpText>
        <label>Trial End Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Self Service</fullName>
                    <default>true</default>
                    <label>Self Service</label>
                </value>
                <value>
                    <fullName>Manual</fullName>
                </value>
                <value>
                    <fullName>Subproject</fullName>
                    <label>Subspace</label>
                </value>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>Custom</fullName>
                    <isActive>false</isActive>
                    <label>Custom</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active_Delete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF(Current_Backend_Stage__c = &quot;Active Contract&quot; || Current_Backend_Stage__c = &quot;Active Subscription&quot;, 
if(ARR_New__c&gt;0, Current_Backend_Stage__c,
IF(Account_Name__r.Account_ARR__c &gt; 0 ||  Parent_Project__r.ARR_New__c &gt; 0, &quot;Subspace&quot;, 
IF(datevalue( etl_subscription_end_date__c) - today() &gt; 0, &quot;Check Data: 100% Discount?&quot;,&quot;Check Data-Churn?&quot;))),


Case ( Current_Backend_Stage__c,
&quot;Deleted&quot; , IF( Initial_ARR__c &gt; 0, &quot;Churned Customer&quot;,&quot;Deleted&quot;),
&quot;Churned Customer&quot;, If(Isblank( Parent_Project__c ), &quot;Churned Customer&quot;,&quot;Churned Subspace&quot;),
&quot;&quot;,IF(now()- CreatedDate &lt;1, &quot;New&quot;,&quot; - Missing&quot;),
 Current_Backend_Stage__c ))</formula>
        <inlineHelpText>Based on MRR &amp; Backend stage</inlineHelpText>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Deleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Updated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Updated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date_Delete</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Team_URL__c</fullName>
        <description>URL of project website</description>
        <label>Team URL</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cancelled__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>not correct? Checked for paying active subscriptions</inlineHelpText>
        <label>Cancelled_Delete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Initial Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account_Name__c</fullName>
        <description>Lookup to Account</description>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Created_Date__c</fullName>
        <label>Project Created Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Product</description>
        <label>Plan</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Health_status__c</fullName>
        <label>Health status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Positive</fullName>
                </value>
                <value>
                    <fullName>Neutral</fullName>
                </value>
                <value>
                    <fullName>Negative</fullName>
                </value>
                <value>
                    <fullName>Dark</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project_PB_ID__c</fullName>
        <description>ID of project from ProductBoardApp</description>
        <externalId>true</externalId>
        <label>Project PB ID</label>
        <length>150</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Parent_Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Child_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Trial_End_Date__c</fullName>
        <label>Trial End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PB_Account_Name__c</fullName>
        <label>PB Account Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Master_User_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master User Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number_of_admins__c</fullName>
        <label>Number of admins_Delete(Rollup)</label>
        <summaryFilterItems>
            <field>Project_User__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Project_User__c.Project_Role__c</field>
            <operation>equals</operation>
            <value>admin</value>
        </summaryFilterItems>
        <summaryForeignKey>Project_User__c.Project__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Account_Not_Found__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Account Not Found_Delete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Number_of_editors__c</fullName>
        <label>Number of editors_Delete(Rollup)</label>
        <summaryFilterItems>
            <field>Project_User__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Project_User__c.Project_Role__c</field>
            <operation>equals</operation>
            <value>editor</value>
        </summaryFilterItems>
        <summaryForeignKey>Project_User__c.Project__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Number_of_viewers__c</fullName>
        <label>Number of viewers_Delete(Rollup)</label>
        <summaryFilterItems>
            <field>Project_User__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Project_User__c.Project_Role__c</field>
            <operation>equals</operation>
            <value>viewer</value>
        </summaryFilterItems>
        <summaryForeignKey>Project_User__c.Project__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Master_User_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master User Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PB_Account_Searched__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PB Account Searched</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Total_Project_Score__c</fullName>
        <label>Total Project Score</label>
        <summarizedField>Project_User__c.User_Score__c</summarizedField>
        <summaryForeignKey>Project_User__c.Project__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Number_of_contributors__c</fullName>
        <label>Number of contributors_Delete(Rollup)</label>
        <summaryFilterItems>
            <field>Project_User__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Project_User__c.Project_Role__c</field>
            <operation>equals</operation>
            <value>contributor</value>
        </summaryFilterItems>
        <summaryForeignKey>Project_User__c.Project__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Project_Activation_Date__c</fullName>
        <label>Project Activation Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Number_of_admins_editors__c</fullName>
        <label>Number of admins/editors_Delete(Rollup)</label>
        <summaryFilterItems>
            <field>Project_User__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Project_User__c.Project_Role__c</field>
            <operation>equals</operation>
            <value>admin, editor</value>
        </summaryFilterItems>
        <summaryForeignKey>Project_User__c.Project__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
</CustomObject>

classes/ExpireTrialBatch.cls
global class ExpireTrialBatch implements Database.Batchable<SObject> {
	
	global ExpireTrialBatch() {
		
	}
	
	/**
	 * @description gets invoked when the batch job starts
	 * @param context contains the job ID
	 * @returns the record set as a QueryLocator object that will be batched for execution
	 */ 
	global Database.QueryLocator start(Database.BatchableContext BC) {
		Date today = Date.today();
		Id trialId = Product2_DAO.getTrialProduct().Id;
        String query = 'SELECT Account_Name__c, Account_Not_Found__c, Active__c, Cancelled__c, Created_Date__c, Deleted__c, Description__c, End_Date__c, Health_status__c, Id, Master_User_Contact__c, Master_User_Lead__c, Name, Number_of_admins__c, Number_of_admins_editors__c, Number_of_contributors__c, Number_of_editors__c, Number_of_viewers__c, Opportunity__c, PB_Account_Name__c, PB_Account_Searched__c, Parent_Project__c, Product_Name__c, Project_Activation_Date__c, Project_PB_ID__c, Status__c, Team_URL__c, Total_Project_Score__c, Trial_End_Date__c, Type__c, Updated__c FROM Project__c WHERE Active__c = true AND Trial_End_Date__c < :today AND Deleted__c = false AND Product_Name__c = :trialId';
        return Database.getQueryLocator(query);
	}

	/**
	 * @description gets invoked when the batch job executes and operates on one batch of records. Contains or calls the main execution logic for the batch job.
	 * @param context contains the job ID
	 * @param scope contains the batch of records to process.
	 */ 
   	global void execute(Database.BatchableContext BC, List<Project__c> scope) {
	    List<Project__c> upProjects = new List<Project__c>();
		List<Id> oppsToUpdateIds = new List<Id>();
        for(Project__c project : scope) {
			 oppsToUpdateIds.add(project.Opportunity__c);
             project.Active__c = false;
			 upProjects.add(project);
        }
		List<Opportunity> oppsToUpdate = Opportunity_DAO.getOppsByListOfIds(oppsToUpdateIds);
		for(Opportunity opp : oppsToUpdate) {
			opp.StageName = 'Trial Expired';
		}

		update oppsToUpdate;
		update upProjects;
	}
	
	/**
	 * @description gets invoked when the batch job finishes. Place any clean up code in this method.
	 * @param context contains the job ID
	 */ 
	global void finish(Database.BatchableContext BC) {
		
	}
}