objects/Opportunity.object
<CustomObject>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>ARR__c</fullName>
        <formula>IF(IsPickVal( RevRec_Type__c ,&quot;Non-Recurring&quot;),0,

IF ( TotalOpportunityQuantity &gt; 0,
IF ( Price_Book__c = &quot;monthly&quot;,
IF(Amount / TotalOpportunityQuantity &gt; 209, Amount- NRR_Amount__c  , (Amount-NRR_Amount__c)*12), Amount-NRR_Amount__c),Amount-NRR_Amount__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>ARR Calculation, for Monthly price books with per-unit pricing is &lt; 209, amount * 12
$0 for Subscription type=&quot;Non-Recurring&quot;</inlineHelpText>
        <label>ARR</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MRR__c</fullName>
        <formula>ARR__c / 12</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>ARR formula field / 12</inlineHelpText>
        <label>MRR</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunity</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subtype__c</fullName>
        <description>Identifying opportunities for user and system</description>
        <label>Subtype</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>User</fullName>
                    <default>true</default>
                    <label>User</label>
                </value>
                <value>
                    <fullName>System</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Price_Book__c</fullName>
        <formula>Pricebook2.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Price Book</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Loss_Reason__c</fullName>
        <label>Loss Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Lost to Competitor [pb]</fullName>
                </value>
                <value>
                    <fullName>No Decision / Ghosting</fullName>
                </value>
                <value>
                    <fullName>No Budget / Lost Funding</fullName>
                </value>
                <value>
                    <fullName>Price</fullName>
                    <label>Pricing (Cost)</label>
                </value>
                <value>
                    <fullName>Feature Gap [pb]</fullName>
                </value>
                <value>
                    <fullName>Tool Consolidation [pb]</fullName>
                </value>
                <value>
                    <fullName>Timing</fullName>
                </value>
                <value>
                    <fullName>Duplicate account_opportunity</fullName>
                    <label>Duplicate account/opportunity</label>
                </value>
                <value>
                    <fullName>Sales declined</fullName>
                </value>
                <value>
                    <fullName>Does not meet ICP</fullName>
                </value>
                <value>
                    <fullName>Self Service Subscribed</fullName>
                </value>
                <value>
                    <fullName>Sales Decline after/during DM</fullName>
                </value>
                <value>
                    <fullName>Automatic - Space Deleted/Expired</fullName>
                </value>
                <value>
                    <fullName>Adoption (Usage) [pb]</fullName>
                </value>
                <value>
                    <fullName>Lack of Value (Outcomes) [pb]</fullName>
                </value>
                <value>
                    <fullName>Out of Business/Acquired</fullName>
                </value>
                <value>
                    <fullName>Champion Change</fullName>
                </value>
                <value>
                    <fullName>Performance [pb]</fullName>
                </value>
                <value>
                    <fullName>Usability [pb]</fullName>
                </value>
                <value>
                    <fullName>Customer Experience [pb]</fullName>
                </value>
                <value>
                    <fullName>No Data</fullName>
                </value>
                <value>
                    <fullName>Security [pb]</fullName>
                </value>
                <value>
                    <fullName>Project on hold</fullName>
                </value>
                <value>
                    <fullName>Reason Missing</fullName>
                </value>
                <value>
                    <fullName>Legal/Security Issue [pb]</fullName>
                </value>
                <value>
                    <fullName>Left Company</fullName>
                </value>
                <value>
                    <fullName>Change Management</fullName>
                </value>
                <value>
                    <fullName>Alternate Need</fullName>
                </value>
                <value>
                    <fullName>Trial Loss Reason</fullName>
                </value>
                <value>
                    <fullName>Trial Created Unintentionally</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Budget_Confirmed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Budget Confirmed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Discovery_Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Discovery Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ROI_Analysis_Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ROI Analysis Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity_Internal_ID__c</fullName>
        <displayFormat>{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>Opportunity Internal ID</label>
        <type>AutoNumber</type>
    </fields>
</CustomObject>

objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>ARR__c</fullName>
        <formula>If( Chartmogul_ARR__c &gt;0, Chartmogul_ARR__c,
If( Prior_ARR__c &gt; 0, Prior_ARR__c,
IF( Maximum_ARR__c &gt; 0,  Maximum_ARR__c, null)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>User Prior or Max ARR if Chartmogul ARR = 0</inlineHelpText>
        <label>ARR_Delete</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MRR__c</fullName>
        <inlineHelpText>MRR updated from ETL.</inlineHelpText>
        <label>MRR</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Price_Book__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Cycle</label>
        <referenceTo>Pricebook2</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

classes/Opportunity_DAO.cls
public class Opportunity_DAO {

	public static List<Opportunity> getOppsByListOfIds(List<Id> ids) {
		List<Opportunity> opps = [SELECT AccountId, Amount, ARR__c, Budget_Confirmed__c, CampaignId, CloseDate, ContractId, CreatedById,
		                          CreatedDate, Description, Discovery_Completed__c, Fiscal, FiscalQuarter, FiscalYear, ForecastCategory, ForecastCategoryName,
		                          HasOpenActivity, HasOpportunityLineItem, HasOverdueTask, Id, IsClosed, IsDeleted, IsWon, LastActivityDate, LastModifiedById,
		                          LastModifiedDate, LastReferencedDate, LastViewedDate, LeadSource, Loss_Reason__c, MRR__c, Name, NextStep, Opportunity_Internal_ID__c,
		                          OwnerId, Pricebook2Id, Price_Book__c, Probability, RecordTypeId, ROI_Analysis_Completed__c, StageName, Subtype__c,
		                          SyncedQuoteId, SystemModstamp, Type
		                          FROM Opportunity
		                          WHERE Id IN :ids];

		return opps;
	}

	public static List<Opportunity> getOppsBySetOfIds(Set<Id> ids) {
		List<Opportunity> opps = [SELECT AccountId, Amount, ARR__c, Budget_Confirmed__c, CampaignId, CloseDate, ContractId, CreatedById,
		                          CreatedDate, Description, Discovery_Completed__c, Fiscal, FiscalQuarter, FiscalYear, ForecastCategory, ForecastCategoryName,
		                          HasOpenActivity, HasOpportunityLineItem, HasOverdueTask, Id, IsClosed, IsDeleted, IsWon, LastActivityDate, LastModifiedById,
		                          LastModifiedDate, LastReferencedDate, LastViewedDate, LeadSource, Loss_Reason__c, MRR__c, Name, NextStep, Opportunity_Internal_ID__c,
		                          OwnerId, Pricebook2Id, Price_Book__c, Probability, RecordTypeId, ROI_Analysis_Completed__c, StageName, Subtype__c,
		                          SyncedQuoteId, SystemModstamp, Type
		                          FROM Opportunity
		                          WHERE Id IN :ids];

		return opps;
	}

	public static List<Opportunity> getOpportunityByProjectId(Id projId) {
		return [SELECT AccountId, Amount, ARR__c, Budget_Confirmed__c, CampaignId, CloseDate, ContractId, CreatedById,
		                          CreatedDate, Description, Discovery_Completed__c, Fiscal, FiscalQuarter, FiscalYear, ForecastCategory, ForecastCategoryName,
		                          HasOpenActivity, HasOpportunityLineItem, HasOverdueTask, Id, IsClosed, IsDeleted, IsWon, LastActivityDate, LastModifiedById,
		                          LastModifiedDate, LastReferencedDate, LastViewedDate, LeadSource, Loss_Reason__c, MRR__c, Name, NextStep, Opportunity_Internal_ID__c,
		                          OwnerId, Pricebook2Id, Price_Book__c, Probability, RecordTypeId, ROI_Analysis_Completed__c, StageName, Subtype__c,
		                          SyncedQuoteId, SystemModstamp, Type
		                          FROM Opportunity
		                          WHERE Project__c = :projId ORDER BY CreatedDate ASC];
	}

	public static List<Opportunity> getOpenOpportunitiesByProjectId(Id projId) {
		return [
			SELECT OwnerId
			FROM Opportunity
			WHERE Project__c = :projId AND IsClosed = false
			ORDER BY CreatedDate ASC
		];
	}

	public static void insertOpportunity(Opportunity opp) {
		try {
			insert opp;
		}
		catch(DmlException e) {
			throw new ProductboardException('Insert Opportunity was ended with errors: ' + e.getMessage(), ApiConstants.CODE_FAILED_DML_ERROR);
		}
	}

}