objects/Product2.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Admins__c</fullName>
        <description>Number of admins allowed for currrent service</description>
        <label>Admins</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Editors__c</fullName>
        <description>Number of editors allowed for current service</description>
        <label>Editors</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Support__c</fullName>
        <description>Support type</description>
        <label>Support</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Basic</fullName>
                </value>
                <value>
                    <fullName>Priority</fullName>
                </value>
                <value>
                    <fullName>Premium</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Viewers__c</fullName>
        <description>Number of viewers allowed for current service.</description>
        <label>Viewers</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Products__c</fullName>
        <description>Number of products allowed for current service</description>
        <label>Products</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contributors__c</fullName>
        <description>Number of contributors allowed for current service</description>
        <label>Contributors</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Response_Time__c</fullName>
        <label>Response Time</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>12h</fullName>
                </value>
                <value>
                    <fullName>24h</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Support_Hours__c</fullName>
        <label>Support Hours</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>8/5</fullName>
                </value>
                <value>
                    <fullName>24/5</fullName>
                </value>
                <value>
                    <fullName>24/7</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

classes/Product2_DAO.cls
public class Product2_DAO {
	public static List<Product2> getProduct2ById(Id product2Id) {
		return [
			SELECT
				Admins__c,
				Contributors__c,
				CreatedById,
				CreatedDate,
				Description,
				DisplayUrl,
				Editors__c,
				ExternalDataSourceId,
				ExternalId,
				Family,
				Id,
				IsActive,
				IsDeleted,
				LastModifiedById,
				LastModifiedDate,
				LastReferencedDate,
				LastViewedDate,
				Name,
				ProductCode,
				Products__c,
				QuantityUnitOfMeasure,
				Response_Time__c,
				/*StockKeepingUnit,*/ Support_Hours__c,
				Support__c,
				SystemModstamp,
				Viewers__c
			FROM Product2
			WHERE Id = :product2Id
		];
	}

	public static Product2 getProduct2ById2(Id product2Id) {
		List<Product2> products = [
			SELECT
				Admins__c,
				Contributors__c,
				CreatedById,
				CreatedDate,
				Description,
				DisplayUrl,
				Editors__c,
				ExternalDataSourceId,
				ExternalId,
				Family,
				Id,
				IsActive,
				IsDeleted,
				LastModifiedById,
				LastModifiedDate,
				LastReferencedDate,
				LastViewedDate,
				Name,
				ProductCode,
				Products__c,
				QuantityUnitOfMeasure,
				Response_Time__c,
				/*StockKeepingUnit,*/ Support_Hours__c,
				Support__c,
				SystemModstamp,
				Viewers__c
			FROM Product2
			WHERE Id = :product2Id
		];

		if (products.isEmpty()) {
			throw new ProductboardException(
				'No product with ID [ ' +
				product2Id +
				' ] was found.',
				ApiConstants.CODE_FAILED_RECORD_NOT_FOUND
			);
		}
		if (products.size() > 1) {
			throw new ProductboardException(
				'More than 1 product with ID [ ' +
				product2Id +
				' ] was found.',
				ApiConstants.CODE_FAILED_MORE_RECORDS_FOUND
			);
		}
		return products.get(0);
	}

	public static Product2 getProduct2ByIdEventsOps(Id product2Id) {
		Product2 returnProduct = null;
		List<Product2> products = [
			SELECT
				Admins__c,
				Contributors__c,
				CreatedById,
				CreatedDate,
				Description,
				DisplayUrl,
				Editors__c,
				ExternalDataSourceId,
				ExternalId,
				Family,
				Id,
				IsActive,
				IsDeleted,
				LastModifiedById,
				LastModifiedDate,
				LastReferencedDate,
				LastViewedDate,
				Name,
				ProductCode,
				Products__c,
				QuantityUnitOfMeasure,
				Response_Time__c,
				/*StockKeepingUnit,*/ Support_Hours__c,
				Support__c,
				SystemModstamp,
				Viewers__c
			FROM Product2
			WHERE Id = :product2Id
		];

		if (products.size() > 1) {
			throw new ProductboardException(
				'More than 1 product with ID [ ' +
				product2Id +
				' ] was found.',
				ApiConstants.CODE_FAILED_MORE_RECORDS_FOUND
			);
		}
		if (products.size() == 1) {
			returnProduct = products.get(0);
		}
		return returnProduct;
	}

	public static Product2 getTrialProduct() {
		Product2 trial = [SELECT Id, Name, Family FROM Product2 WHERE Name = 'Trial' LIMIT 1];
		return trial;
	}

	public static Product2 getStarterProduct() {
		Product2 starter = [SELECT Id, Name, Family FROM Product2 WHERE Name = 'Starter' LIMIT 1];
		return starter;
	}

	public static Product2 getProductByPlanAndVersion(String plan, String planVersion, Id productId) {
		List<Product2> pbProduct;
		if (plan != null && planVersion != null) {
			pbProduct = [SELECT Id, Name, Family FROM Product2 WHERE Name = :plan AND Family = :planVersion AND IsActive = TRUE LIMIT 1];
		} else if (plan != null && planVersion == null) {
			pbProduct = [SELECT Id, Name, Family FROM Product2 WHERE Name = :plan AND Family = 'Custom Plans' AND IsActive = TRUE LIMIT 1];
		} else {
			pbProduct = [SELECT Id, Name, Family FROM Product2 WHERE Id = :productId AND IsActive = TRUE LIMIT 1];
		}
		if (pbProduct.isEmpty()) {
			throw new ProductboardException(
				'No product was found for plan [ ' +
				plan +
				' ] and plan version [ ' +
				planVersion +
				' ].',
				ApiConstants.CODE_FAILED_RECORD_NOT_FOUND
			);
		}

		return pbProduct.get(0);
	}

	public static void insertProducts(List<Product2> prods) {
		try {
			insert prods;
			System.debug('Product2_DAO: insert - List of products was successfully inserted.');
		} catch (DmlException e) {
			System.debug('Product2_DAO: insert - List of products ended with errors');
			throw new ProductboardException(
				'Insert list of products was ended with errors: ' + e.getMessage(),
				ApiConstants.CODE_FAILED_DML_ERROR
			);
		}
	}
}