objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active_Delete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Cancelled__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>not correct? Checked for paying active subscriptions</inlineHelpText>
        <label>Cancelled_Delete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Account_Name__c</fullName>
        <description>Lookup to Account</description>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Created_Date__c</fullName>
        <label>Project Created Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Project_PB_ID__c</fullName>
        <description>ID of project from ProductBoardApp</description>
        <externalId>true</externalId>
        <label>Project PB ID</label>
        <length>150</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

objects/Project_User__c.object
<CustomObject>
    <label>Project User</label>
    <nameField>
        <label>Project User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Project Users</relationshipLabel>
        <relationshipName>Project_Users</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Cancelled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Cancelled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>User_Status__c</fullName>
        <label>User Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Current</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project_PB_ID__c</fullName>
        <formula>Project__r.Project_PB_ID__c</formula>
        <inlineHelpText>Project Productboard ID</inlineHelpText>
        <label>Project PB ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Added_Date__c</fullName>
        <label>User Added Date</label>
        <type>DateTime</type>
    </fields>
</CustomObject>

classes/MigrationTest.cls
@isTest
private class MigrationTest {
    
    static testMethod void testOnUpdate() {
        // set records
        Project__c project = new Project__c();
        project.Name = 'Test project';
        project.Project_PB_ID__c = '123'; 
        project.Active__c = false;
		project.Account_Name__c = DataFactory_TEST.createTestAccount().Id;
        insert project;
        
        Project_User__c user1 = new Project_User__c();
        user1.Name = 'Test Name';
        user1.Project__c = project.Id;
        user1.Active__c = false;
        insert user1;
        
        Project_User__c user2 = new Project_User__c();
        user2.Name = 'Test Name';
        user2.Project__c = project.Id;
        user2.Active__c = false;
        insert user2;
        
        // call test
        Migration.updateProjectUsers();
        
        // get records
        List<Project_User__c> projectUsers = [Select Id,User_Status__c, Active__c, User_Added_Date__c from Project_User__c where Id =:user1.Id or Id =:user2.Id]; 
        Project__c updatedProject = [Select Id, Created_Date__c, Active__c, Cancelled__c from Project__c where Id =:project.Id];
        
        // assert
        for (Project_User__c eachProjectUser : projectUsers) {
        	System.assertEquals('Current', eachProjectUser.User_Status__c);
            System.assertEquals(true, eachProjectUser.Active__c);
            System.assertNotEquals(null, eachProjectUser.User_Added_Date__c);
        }
        System.assertEquals(true, updatedProject.Active__c);
        System.assertNotEquals(null, updatedProject.Created_Date__c);
    }
    
}