objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Trial_End_Date__c</fullName>
        <label>Trial End Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

classes/ExpireTrial_TEST.cls
@isTest 
private class ExpireTrial_TEST {
	
	@TestSetup
	private static void testSetup() {
		DataFactory_TEST.init();
	}

	@isTest
	private static void testScheduleExpireTrial() {
		ExpireTrialSchedulable sch = new ExpireTrialSchedulable();
		String schTime = '0 0 23 * * ?';
		System.schedule('Expire Trial Test Scheduler',schTime,sch);
	}

	@isTest
	private static void testExpireTrialBatch() {
		Project__c pr = DataFactory_TEST.createTrialProject();
		pr.Trial_End_Date__c = Date.today().addDays(-20);
		update pr;


		ExpireTrialBatch etb = new ExpireTrialBatch();
		database.executeBatch(etb,100);
	}

}