objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>BI_City__c</fullName>
        <label>BI City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CC_City__c</fullName>
        <label>CC City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BI_State__c</fullName>
        <label>BI State</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CC_State__c</fullName>
        <label>CC State</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BI_Address__c</fullName>
        <label>BI Address</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BI_Country__c</fullName>
        <label>BI Country</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CC_Address__c</fullName>
        <label>CC Address</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CC_Country__c</fullName>
        <label>CC Country</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BI_VAT_Number__c</fullName>
        <label>BI VAT Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_PB_ID__c</fullName>
        <description>ID of project from ProductBoardApp</description>
        <externalId>true</externalId>
        <label>Project PB ID</label>
        <length>150</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>BI_Postal_Code__c</fullName>
        <label>BI Postal Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CC_Postal_Code__c</fullName>
        <label>CC Postal Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BI_Company_Name__c</fullName>
        <label>BI Company Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CC_Billing_Email__c</fullName>
        <label>CC Billing Email</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BI_Additional_Info__c</fullName>
        <label>BI Additional Info</label>
        <length>100</length>
        <type>Text</type>
    </fields>
</CustomObject>

classes/UpdateBillingInformationTest.cls
@isTest
private class UpdateBillingInformationTest {
	@testSetup
	static void initsObjects() {
		DataFactory_TEST.init();
	}

	@isTest
	private static void testInvalidProjectId() {
		String response = UpdateBillingInformation.updateBillingInformation(UpdateBillingInformationTest_SERV.setUpBillingInfo(null, true));
		ApiResponseDTO res = (ApiResponseDTO) JSON.deserialize(response, ApiResponseDTO.class);
		System.assertEquals(ApiConstants.CODE_FAILED_RECORD_NOT_FOUND, res.statusCode);
	}

	@isTest
	private static void testBillingInfoUpdate() {
		Project__c pr = DataFactory_TEST.createProjectWithAssetNoDiscount('New idea', 'yearly', 1);

		String response = UpdateBillingInformation.updateBillingInformation(
			UpdateBillingInformationTest_SERV.setUpBillingInfo(pr.Project_PB_ID__c, true)
		);

		Project__c actualProject = Project_DAO.getProjectByPBIdWithExc(pr.Project_PB_ID__c);
		ApiResponseDTO res = (ApiResponseDTO) JSON.deserialize(response, ApiResponseDTO.class);
		System.assertEquals(ApiConstants.CODE_SUCCESS, res.statusCode);
		System.assertEquals(ApiConstants.MSG_SUCCESS_BILLING_INFO_UPDATE, res.statusMessage);
		System.assertEquals('Test Street 123', actualProject.CC_Address__c);
		System.assertEquals('test@test.test', actualProject.CC_Billing_Email__c);
		System.assertEquals('Test City', actualProject.CC_City__c);
		System.assertEquals('Test Country', actualProject.CC_Country__c);
		System.assertEquals('12300', actualProject.CC_Postal_Code__c);
		System.assertEquals('Test State', actualProject.CC_State__c);
		System.assertEquals('Test billing additional information.', actualProject.BI_Additional_Info__c);
		System.assertEquals('Company Street 321', actualProject.BI_Address__c);
		System.assertEquals('Company City', actualProject.BI_City__c);
		System.assertEquals('Test Company', actualProject.BI_Company_Name__c);
		System.assertEquals('Company Country', actualProject.BI_Country__c);
		System.assertEquals('32100', actualProject.BI_Postal_Code__c);
		System.assertEquals('Company State', actualProject.BI_State__c);
		System.assertEquals('123465789', actualProject.BI_VAT_Number__c);
	}
}