objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Paid__c</fullName>
        <formula>ARR_New__c  &gt; 0</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Paid?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Self Service</fullName>
                    <default>true</default>
                    <label>Self Service</label>
                </value>
                <value>
                    <fullName>Manual</fullName>
                </value>
                <value>
                    <fullName>Subproject</fullName>
                    <label>Subspace</label>
                </value>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>Custom</fullName>
                    <isActive>false</isActive>
                    <label>Custom</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active_Delete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF(Current_Backend_Stage__c = &quot;Active Contract&quot; || Current_Backend_Stage__c = &quot;Active Subscription&quot;, 
if(ARR_New__c&gt;0, Current_Backend_Stage__c,
IF(Account_Name__r.Account_ARR__c &gt; 0 ||  Parent_Project__r.ARR_New__c &gt; 0, &quot;Subspace&quot;, 
IF(datevalue( etl_subscription_end_date__c) - today() &gt; 0, &quot;Check Data: 100% Discount?&quot;,&quot;Check Data-Churn?&quot;))),


Case ( Current_Backend_Stage__c,
&quot;Deleted&quot; , IF( Initial_ARR__c &gt; 0, &quot;Churned Customer&quot;,&quot;Deleted&quot;),
&quot;Churned Customer&quot;, If(Isblank( Parent_Project__c ), &quot;Churned Customer&quot;,&quot;Churned Subspace&quot;),
&quot;&quot;,IF(now()- CreatedDate &lt;1, &quot;New&quot;,&quot; - Missing&quot;),
 Current_Backend_Stage__c ))</formula>
        <inlineHelpText>Based on MRR &amp; Backend stage</inlineHelpText>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BI_City__c</fullName>
        <label>BI City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Counter__c</fullName>
        <formula>1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Counter</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Deleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Deleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Updated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Updated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date_Delete</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Team_URL__c</fullName>
        <description>URL of project website</description>
        <label>Team URL</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cancelled__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>not correct? Checked for paying active subscriptions</inlineHelpText>
        <label>Cancelled_Delete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Account_ID__c</fullName>
        <formula>Account_Name__r.Id</formula>
        <label>Account ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BI_Address__c</fullName>
        <label>BI Address</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BI_Country__c</fullName>
        <label>BI Country</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price_Book__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Cycle</label>
        <referenceTo>Pricebook2</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Account_Name__c</fullName>
        <description>Lookup to Account</description>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Created_Date__c</fullName>
        <label>Project Created Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Product</description>
        <label>Plan</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Health_status__c</fullName>
        <label>Health status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Positive</fullName>
                </value>
                <value>
                    <fullName>Neutral</fullName>
                </value>
                <value>
                    <fullName>Negative</fullName>
                </value>
                <value>
                    <fullName>Dark</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project_PB_ID__c</fullName>
        <description>ID of project from ProductBoardApp</description>
        <externalId>true</externalId>
        <label>Project PB ID</label>
        <length>150</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>BI_Postal_Code__c</fullName>
        <label>BI Postal Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Chartmogul_MRR__c</fullName>
        <label>Chartmogul MRR Delete</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Chartmogul_URL__c</fullName>
        <label>Chartmogul URL Delete</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Parent_Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Child_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Trial_End_Date__c</fullName>
        <label>Trial End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BI_Company_Name__c</fullName>
        <label>BI Company Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Chartmogul_Plan__c</fullName>
        <label>Chartmogul Plan Delete</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PB_Account_Name__c</fullName>
        <label>PB Account Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Master_User_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master User Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number_of_admins__c</fullName>
        <label>Number of admins_Delete(Rollup)</label>
        <summaryFilterItems>
            <field>Project_User__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Project_User__c.Project_Role__c</field>
            <operation>equals</operation>
            <value>admin</value>
        </summaryFilterItems>
        <summaryForeignKey>Project_User__c.Project__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Account_Not_Found__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Account Not Found_Delete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Chartmogul_Status__c</fullName>
        <label>Chartmogul Status Delete</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Number_of_editors__c</fullName>
        <label>Number of editors_Delete(Rollup)</label>
        <summaryFilterItems>
            <field>Project_User__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Project_User__c.Project_Role__c</field>
            <operation>equals</operation>
            <value>editor</value>
        </summaryFilterItems>
        <summaryForeignKey>Project_User__c.Project__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Number_of_viewers__c</fullName>
        <label>Number of viewers_Delete(Rollup)</label>
        <summaryFilterItems>
            <field>Project_User__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Project_User__c.Project_Role__c</field>
            <operation>equals</operation>
            <value>viewer</value>
        </summaryFilterItems>
        <summaryForeignKey>Project_User__c.Project__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>BI_Additional_Info__c</fullName>
        <label>BI Additional Info</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GoodData_Dashboard__c</fullName>
        <label>GoodData Dashboard</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Project_Name_Short__c</fullName>
        <formula>left(Name,FIND(&quot;.&quot;, Name)-1)</formula>
        <label>Project Name (Short)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status_Carbon_Copy__c</fullName>
        <description>Copied version of Status formula field. For use w/ rollup fields on Account Object</description>
        <label>Prior Status</label>
        <length>99</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Master_User_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master User Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PB_Account_Searched__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PB Account Searched</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Total_Project_Score__c</fullName>
        <label>Total Project Score</label>
        <summarizedField>Project_User__c.User_Score__c</summarizedField>
        <summaryForeignKey>Project_User__c.Project__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Backend_Company_name__c</fullName>
        <label>Backend Company name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Backend_Stage__c</fullName>
        <externalId>true</externalId>
        <label>Current Backend Stage</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscription_End_Date__c</fullName>
        <label>Subscription End Date_Delete</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Number_of_contributors__c</fullName>
        <label>Number of contributors_Delete(Rollup)</label>
        <summaryFilterItems>
            <field>Project_User__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Project_User__c.Project_Role__c</field>
            <operation>equals</operation>
            <value>contributor</value>
        </summaryFilterItems>
        <summaryForeignKey>Project_User__c.Project__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Project_Activation_Date__c</fullName>
        <label>Project Activation Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Subscription_Start_Date__c</fullName>
        <label>Subscription Start Date_Delete</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Chartmogul_Billing_Cycle__c</fullName>
        <label>Chartmogul billing cycle Delete</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Number_of_admins_editors__c</fullName>
        <label>Number of admins/editors_Delete(Rollup)</label>
        <summaryFilterItems>
            <field>Project_User__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Project_User__c.Project_Role__c</field>
            <operation>equals</operation>
            <value>admin, editor</value>
        </summaryFilterItems>
        <summaryForeignKey>Project_User__c.Project__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Watchdog_Properly_Active__c</fullName>
        <formula>and(
Chartmogul_MRR__c &gt;0,
Status__c &lt;&gt; &quot;Paying&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Watchdog - Properly Active_Delete</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

classes/Project_DAO.cls
public class Project_DAO {
	public static List<Project__c> getProjectById(Id projectId) {
		return [
			SELECT
				Account_Name__c,
				Active__c,
				Cancelled__c,
				CreatedById,
				CreatedDate,
				Created_Date__c,
				Deleted__c,
				End_Date__c,
				Id,
				IsDeleted,
				LastModifiedById,
				LastModifiedDate,
				LastReferencedDate,
				LastViewedDate,
				Master_User_Contact__c,
				Master_User_Lead__c,
				Name,
				Product_Name__c,
				Project_PB_ID__c,
				Price_Book__c,
				Price_Book__r.name,
				Subscription_Start_Date__c,
				Subscription_End_Date__c,
				SystemModstamp,
				Team_URL__c,
				Total_Project_Score__c,
				Trial_End_Date__c
			FROM Project__c
			WHERE Id = :projectId
		];
	}

	public static List<Project__c> getProjectByProductboardProjectId(String projectPbId) {
		return [
			SELECT
				Account_Name__c,
				Active__c,
				Cancelled__c,
				CreatedById,
				CreatedDate,
				Created_Date__c,
				Deleted__c,
				End_Date__c,
				Id,
				IsDeleted,
				LastModifiedById,
				LastModifiedDate,
				LastReferencedDate,
				LastViewedDate,
				Master_User_Contact__c,
				Master_User_Lead__c,
				Name,
				Product_Name__c,
				Project_PB_ID__c,
				Price_Book__c,
				Subscription_Start_Date__c,
				Subscription_End_Date__c,
				SystemModstamp,
				Team_URL__c,
				Total_Project_Score__c,
				Trial_End_Date__c
			FROM Project__c
			WHERE Project_PB_ID__c = :projectPbId
		];
	}

	public static Project__c getProjectByPBIdWithExc(String projectPbId) {
		List<Project__c> projects = [
			SELECT
				/*allFields*/ Id,
				IsDeleted,
				Name,
				CreatedDate,
				CreatedById,
				LastModifiedDate,
				LastModifiedById,
				SystemModstamp,
				LastViewedDate,
				LastReferencedDate,
				Account_Name__c,
				Master_User_Lead__c,
				Product_Name__c,
				Project_PB_ID__c,
				Team_URL__c,
				Total_Project_Score__c,
				Active__c,
				Cancelled__c,
				Created_Date__c,
				End_Date__c,
				Trial_End_Date__c,
				Deleted__c,
				Master_User_Contact__c,
				Parent_Project__c,
				Description__c,
				Health_status__c,
				Number_of_admins__c,
				Number_of_contributors__c,
				Number_of_editors__c,
				Number_of_viewers__c,
				Account_Not_Found__c,
				PB_Account_Name__c,
				PB_Account_Searched__c,
				Updated__c,
				Project_Activation_Date__c,
				Type__c,
				Number_of_admins_editors__c,
				Status__c,
				Project_Name_Short__c,
				Paid__c,
				Status_Carbon_Copy__c,
				Account_ID__c,
				Counter__c,
				Chartmogul_Plan__c,
				Watchdog_Properly_Active__c,
				Chartmogul_Billing_Cycle__c,
				GoodData_Dashboard__c,
				Chartmogul_MRR__c,
				Chartmogul_URL__c,
				Chartmogul_Status__c,
				Current_Backend_Stage__c,
				Backend_Company_name__c,
				Price_Book__c,
				Subscription_Start_Date__c,
				Subscription_End_Date__c,
				BI_Additional_Info__c,
				BI_Address__c,
				BI_City__c,
				BI_Company_Name__c,
				BI_Country__c,
				BI_Postal_Code__c,
				BI_State__c,
				BI_VAT_Number__c,
				CC_Address__c,
				CC_Billing_Email__c,
				CC_Country__c,
				CC_City__c,
				CC_Postal_Code__c,
				CC_State__c
			FROM Project__c
			WHERE Project_PB_ID__c = :projectPbId
		];
		if (projects.isEmpty()) {
			throw new ProductboardException(
				'Project for project PB ID [' +
				projectPbId +
				'] was not found.',
				ApiConstants.CODE_FAILED_RECORD_NOT_FOUND
			);
		}
		if (projects.size() > 1) {
			throw new ProductboardException(
				'More than 1 projects for ID [' +
				projectPbId +
				'] were found.',
				ApiConstants.CODE_FAILED_MORE_RECORDS_FOUND
			);
		}
		return projects.get(0);
	}

	public static Project__c getProjectByIdWithExc(Id projectId) {
		List<Project__c> projects = [
			SELECT
				Account_Name__c,
				Active__c,
				Cancelled__c,
				CreatedById,
				CreatedDate,
				Created_Date__c,
				Deleted__c,
				End_Date__c,
				Id,
				IsDeleted,
				LastModifiedById,
				LastModifiedDate,
				LastReferencedDate,
				LastViewedDate,
				Master_User_Contact__c,
				Master_User_Lead__c,
				Name,
				Product_Name__c,
				Project_PB_ID__c,
				Price_Book__c,
				Subscription_Start_Date__c,
				Subscription_End_Date__c,
				SystemModstamp,
				Team_URL__c,
				Total_Project_Score__c,
				Trial_End_Date__c
			FROM Project__c
			WHERE Id = :projectId
		];

		if (projects.isEmpty()) {
			throw new ProductboardException(
				'Project for projectId [' +
				projectId +
				'] was not found.',
				ApiConstants.CODE_FAILED_RECORD_NOT_FOUND
			);
		}
		if (projects.size() > 1) {
			throw new ProductboardException(
				'More than 1 projects for projectId [' +
				projectId +
				'] were found.',
				ApiConstants.CODE_FAILED_MORE_RECORDS_FOUND
			);
		}
		return projects.get(0);
	}

	public static List<Project__c> getProjectsByListOfIds(List<Id> projectIds) {
		List<Project__c> projects = [
			SELECT
				Account_Name__c,
				Active__c,
				Cancelled__c,
				CreatedById,
				CreatedDate,
				Created_Date__c,
				Deleted__c,
				End_Date__c,
				Id,
				IsDeleted,
				LastModifiedById,
				LastModifiedDate,
				LastReferencedDate,
				LastViewedDate,
				Master_User_Contact__c,
				Master_User_Lead__c,
				Name,
				Product_Name__c,
				Project_PB_ID__c,
				Price_Book__c,
				Subscription_Start_Date__c,
				Subscription_End_Date__c,
				SystemModstamp,
				Team_URL__c,
				Total_Project_Score__c,
				Trial_End_Date__c
			FROM Project__c
			WHERE Id IN :projectIds
		];
		if (projects.isEmpty()) {
			throw new ProductboardException('No Projects were found for the project user!', ApiConstants.CODE_FAILED_RECORD_NOT_FOUND);
		}
		return projects;
	}

	public static List<Project__c> getProjectsByListOfMasterContactIds(List<Id> masterContactIds) {
		List<Project__c> projects = [
			SELECT
				Account_Name__c,
				Active__c,
				Cancelled__c,
				CreatedById,
				CreatedDate,
				Created_Date__c,
				Deleted__c,
				End_Date__c,
				Id,
				IsDeleted,
				LastModifiedById,
				LastModifiedDate,
				LastReferencedDate,
				LastViewedDate,
				Master_User_Contact__c,
				Master_User_Lead__c,
				Name,
				Product_Name__c,
				Project_PB_ID__c,
				Price_Book__c,
				Subscription_Start_Date__c,
				Subscription_End_Date__c,
				SystemModstamp,
				Team_URL__c,
				Total_Project_Score__c,
				Trial_End_Date__c
			FROM Project__c
			WHERE Master_User_Contact__c IN :masterContactIds
		];
		if (projects.isEmpty()) {
			throw new ProductboardException('No Projects were found.', ApiConstants.CODE_FAILED_RECORD_NOT_FOUND);
		}
		return projects;
	}

	public static void insertProject(Project__c prj) {
		try {
			insert prj;
		} catch (DmlException e) {
			throw new ProductboardException('Insert Project was ended with errors: ' + e.getMessage(), ApiConstants.CODE_FAILED_DML_ERROR);
		}
	}

	public static void updateProject(Project__c prj) {
		try {
			update prj;
		} catch (DmlException e) {
			throw new ProductboardException('Update Project was ended with errors: ' + e.getMessage(), ApiConstants.CODE_FAILED_DML_ERROR);
		}
	}
}